In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler,StandardScaler

import geopandas as gpd

%matplotlib inline
pd.set_option('display.max_columns', None)

# 1. Import Data

## 1.1 Population per Age

In [2]:
OA_sex_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Sex_per_OA.csv")
OA_sex_df.head()

,Output Areas Code,Output Areas,Sex (2 categories) Code,Sex (2 categories),Observation
0,E00000001,E00000001,1,Female,75
1,E00000001,E00000001,2,Male,101
2,E00000003,E00000003,1,Female,123
3,E00000003,E00000003,2,Male,135
4,E00000005,E00000005,1,Female,52

In [3]:
OA_sex_df_P = pd.pivot_table(OA_sex_df, values='Observation', index=['Output Areas Code'], columns=['Sex (2 categories)'], aggfunc=np.sum)
OA_sex_df_P['total_population'] = OA_sex_df_P['Female'] + OA_sex_df_P['Male']
OA_sex_df_P = OA_sex_df_P.reset_index()
#renaming
OA_sex_df_P.rename(columns = {'Female':'female_population', 
                              'Male':'male_population'
                             }, inplace = True)

OA_sex_df_P.head()

Sex (2 categories),Output Areas Code,female_population,male_population,total_population
0,E00000001,75,101,176
1,E00000003,123,135,258
2,E00000005,52,60,112
3,E00000007,67,77,144
4,E00000010,71,107,178

### 2.1.1 Population by Passport per OA

In [4]:
OA_passports_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Passports per OA.csv")
OA_passports_df.head()

,Output Areas Code,Output Areas,Passports held (27 categories) Code,Passports held (27 categories),Observation
0,E00000001,E00000001,-8,Does not apply,0
1,E00000001,E00000001,1,Europe: United Kingdom,141
2,E00000001,E00000001,2,Europe: Ireland,1
3,E00000001,E00000001,3,Europe: Other Europe: EU Member countries: France,3
4,E00000001,E00000001,4,Europe: Other Europe: EU Member countries: Ger...,9

In [5]:
OA_passports_df_P = pd.pivot_table(OA_passports_df, values='Observation', index=['Output Areas Code'], columns=['Passports held (27 categories)'], aggfunc=np.sum)
OA_passports_df_P['african'] = OA_passports_df_P['Africa: Central and Western Africa'] + OA_passports_df_P['Africa: North Africa'] + OA_passports_df_P['Africa: South and Eastern Africa']
OA_passports_df_P['british_overseas_territories'] = OA_passports_df_P['British Overseas Territories']
OA_passports_df_P['antarctica_and_oceania_including_australasia'] = OA_passports_df_P['Antarctica and Oceania, including Australasia']
OA_passports_df_P['europe'] = OA_passports_df_P['Europe: Other Europe: EU Member countries: France'] + OA_passports_df_P['Europe: Other Europe: EU Member countries: Germany']+ OA_passports_df_P['Europe: Other Europe: EU Member countries: Italy']+ OA_passports_df_P['Europe: Other Europe: EU Member countries: Lithuania']+ OA_passports_df_P['Europe: Other Europe: EU Member countries: Other EU countries']+ OA_passports_df_P['Europe: Other Europe: EU Member countries: Poland']+ OA_passports_df_P['Europe: Other Europe: EU Member countries: Portugal']+ OA_passports_df_P['Europe: Other Europe: EU Member countries: Romania']+ OA_passports_df_P['Europe: Other Europe: EU Member countries: Spain']
OA_passports_df_P['other_europe'] = OA_passports_df_P['Europe: Other Europe: Rest of Europe: Other Europe']+ OA_passports_df_P['Europe: Other Europe: Rest of Europe: Turkey']
OA_passports_df_P['ireland'] =OA_passports_df_P['Europe: Ireland']
OA_passports_df_P['united_kingdom'] =OA_passports_df_P['Europe: United Kingdom']
OA_passports_df_P['america_caribbean'] = OA_passports_df_P['The Americas and the Caribbean: Central and South America']
OA_passports_df_P['asia_middle_east'] = OA_passports_df_P['Middle East and Asia: Central Asia'] + OA_passports_df_P['Middle East and Asia: Middle East']+ OA_passports_df_P['Middle East and Asia: South-East Asia']+ OA_passports_df_P['Middle East and Asia: Southern Asia']
OA_passports_df_P['no_passport'] =OA_passports_df_P['No passport held']
#OA_passports_df_P['Does_not_apply'] =OA_passports_df_P['Does not apply']
OA_passports_df_P = OA_passports_df_P.reset_index()
OA_passports_df_P.drop(OA_passports_df_P.iloc[:, 1:28], inplace=True, axis=1)
OA_passports_df_P.head()

Passports held (27 categories),Output Areas Code,african,british_overseas_territories,antarctica_and_oceania_including_australasia,europe,other_europe,ireland,united_kingdom,america_caribbean,asia_middle_east,no_passport
0,E00000001,0,0,0,25,2,1,141,1,0,3
1,E00000003,0,0,4,12,0,1,226,0,1,4
2,E00000005,0,0,0,11,1,0,89,0,2,3
3,E00000007,0,0,14,31,3,7,78,0,2,2
4,E00000010,1,0,1,39,3,1,119,1,1,9

### 2.1.2 Household per OA

In [6]:
OA_hhold_df_P = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Households_per_OA.csv")
OA_hhold_df_P.drop(['Output Areas'], 1, inplace=True)
#renaming
OA_hhold_df_P.rename(columns = {'Observation':'total_households', 
                                }, inplace = True)

OA_hhold_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\1084625099.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_hhold_df_P.drop(['Output Areas'], 1, inplace=True)

  Output Areas Code  total_households
0         E00000001                94
1         E00000003               109
2         E00000005                63
3         E00000007                86
4         E00000010               126

### 2.1.3 Household Size per OA

In [7]:
OA_hhold_size_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Household_Size_per_OA.csv")
OA_hhold_size_df.head()

,Output Areas Code,Output Areas,Household size (9 categories) Code,Household size (9 categories),Observation
0,E00000001,E00000001,0,0 people in household,0
1,E00000001,E00000001,1,1 person in household,34
2,E00000001,E00000001,2,2 people in household,44
3,E00000001,E00000001,3,3 people in household,10
4,E00000001,E00000001,4,4 people in household,6

In [8]:
OA_hhold_size_df_P = pd.pivot_table(OA_hhold_size_df, values='Observation', index=['Output Areas Code'], columns=['Household size (9 categories)'], aggfunc=np.sum)
OA_hhold_size_df_P = OA_hhold_size_df_P.reset_index()
OA_hhold_size_df_P.head()

Household size (9 categories),Output Areas Code,0 people in household,1 person in household,2 people in household,3 people in household,4 people in household,5 people in household,6 people in household,7 people in household,8 or more people in household
0,E00000001,0,34,44,10,6,0,0,0,0
1,E00000003,0,27,42,19,17,4,0,0,0
2,E00000005,0,26,27,8,2,0,0,0,0
3,E00000007,0,38,44,2,2,1,0,0,0
4,E00000010,0,96,19,4,3,3,0,0,0

### 2.1.4 Household composition per OA

In [9]:
OA_hhold_comp_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Household_Composition_per_OA.csv")
OA_hhold_comp_df.head()

,Output Areas Code,Output Areas,Household composition (15 categories) Code,Household composition (15 categories),Observation
0,E00000001,E00000001,-8,Does not apply,0
1,E00000001,E00000001,1,One person household: Aged 66 years and over,16
2,E00000001,E00000001,2,One person household: Other,18
3,E00000001,E00000001,3,Single family household: All aged 66 years and...,16
4,E00000001,E00000001,4,Single family household: Married or civil part...,23

In [10]:
OA_hhold_comp_df_P = pd.pivot_table(OA_hhold_comp_df, values='Observation', index=['Output Areas Code'], columns=['Household composition (15 categories)'], aggfunc=np.sum)
OA_hhold_comp_df_P = OA_hhold_comp_df_P.reset_index()
OA_hhold_comp_df_P.drop(['Does not apply'], 1, inplace=True)

OA_hhold_comp_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\3770411479.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_hhold_comp_df_P.drop(['Does not apply'], 1, inplace=True)

Household composition (15 categories),Output Areas Code,One person household: Aged 66 years and over,One person household: Other,"Other household types: Other, including all full-time students and all aged 66 years and over",Other household types: With dependent children,Single family household: All aged 66 years and over,Single family household: Cohabiting couple family: All children non-dependent,Single family household: Cohabiting couple family: No children,Single family household: Cohabiting couple family: With dependent children,Single family household: Lone parent family: All children non-dependent,Single family household: Lone parent family: With dependent children,Single family household: Married or civil partnership couple: All children non-dependent,Single family household: Married or civil partnership couple: Dependent children,Single family household: Married or civil partnership couple: No children,Single family household: Other single family household: Other family composition
0,E00000001,16,18,3,0,16,0,2,3,2,3,1,7,23,0
1,E00000003,11,16,10,0,20,0,5,1,0,3,9,19,15,0
2,E00000005,9,17,2,0,7,0,5,4,3,1,2,2,11,0
3,E00000007,3,34,6,0,3,0,22,0,0,0,0,3,7,8
4,E00000010,17,79,6,0,0,3,10,3,0,0,0,2,5,3

### 2.1.6 Ethnicity per OA

In [11]:
OA_ethincity_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Ethnicity_per_OA.csv")
OA_ethincity_df .head()

,Output Areas Code,Output Areas,Ethnic group (20 categories) Code,Ethnic group (20 categories),Observation
0,E00000001,E00000001,-8,Does not apply,0
1,E00000001,E00000001,1,"Asian, Asian British or Asian Welsh: Bangladeshi",0
2,E00000001,E00000001,2,"Asian, Asian British or Asian Welsh: Chinese",4
3,E00000001,E00000001,3,"Asian, Asian British or Asian Welsh: Indian",0
4,E00000001,E00000001,4,"Asian, Asian British or Asian Welsh: Pakistani",1

In [12]:
OA_ethincity_df_P = pd.pivot_table(OA_ethincity_df, values='Observation', index=['Output Areas Code'], columns=['Ethnic group (20 categories)'], aggfunc=np.sum)
OA_ethincity_df_P = OA_ethincity_df_P.reset_index()
OA_ethincity_df_P.drop(['Does not apply'], 1, inplace=True)
OA_ethincity_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\188246616.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_ethincity_df_P.drop(['Does not apply'], 1, inplace=True)

Ethnic group (20 categories),Output Areas Code,"Asian, Asian British or Asian Welsh: Bangladeshi","Asian, Asian British or Asian Welsh: Chinese","Asian, Asian British or Asian Welsh: Indian","Asian, Asian British or Asian Welsh: Other Asian","Asian, Asian British or Asian Welsh: Pakistani","Black, Black British, Black Welsh, Caribbean or African: African","Black, Black British, Black Welsh, Caribbean or African: Caribbean","Black, Black British, Black Welsh, Caribbean or African: Other Black",Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups,Mixed or Multiple ethnic groups: White and Asian,Mixed or Multiple ethnic groups: White and Black African,Mixed or Multiple ethnic groups: White and Black Caribbean,Other ethnic group: Any other ethnic group,Other ethnic group: Arab,"White: English, Welsh, Scottish, Northern Irish or British",White: Gypsy or Irish Traveller,White: Irish,White: Other White,White: Roma
0,E00000001,0,4,0,0,1,0,3,0,1,5,0,0,7,0,112,0,0,39,4
1,E00000003,0,6,11,7,0,5,0,0,7,6,0,0,3,1,174,0,0,35,0
2,E00000005,0,4,4,5,0,0,0,0,2,2,2,0,7,1,65,0,0,20,0
3,E00000007,0,16,1,7,0,2,0,0,1,2,1,0,3,5,62,0,4,40,0
4,E00000010,1,3,3,3,0,5,5,2,11,7,3,1,10,1,83,0,0,37,0

In [13]:
#feature engineering
OA_ethincity_df_P['all_asian_ethnic_groups'] = OA_ethincity_df_P['Asian, Asian British or Asian Welsh: Bangladeshi'] + OA_ethincity_df_P['Asian, Asian British or Asian Welsh: Chinese'] + OA_ethincity_df_P['Asian, Asian British or Asian Welsh: Indian'] + OA_ethincity_df_P['Asian, Asian British or Asian Welsh: Pakistani'] + OA_ethincity_df_P['Asian, Asian British or Asian Welsh: Other Asian']
OA_ethincity_df_P['all_black_ethnic_groups'] = OA_ethincity_df_P['Black, Black British, Black Welsh, Caribbean or African: African'] + OA_ethincity_df_P['Black, Black British, Black Welsh, Caribbean or African: Caribbean'] + OA_ethincity_df_P['Black, Black British, Black Welsh, Caribbean or African: Other Black']
OA_ethincity_df_P['all_mixed_or_multiple_ethnic_groups'] = OA_ethincity_df_P['Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups'] + OA_ethincity_df_P['Mixed or Multiple ethnic groups: White and Asian'] + OA_ethincity_df_P['Mixed or Multiple ethnic groups: White and Black African'] + OA_ethincity_df_P['Mixed or Multiple ethnic groups: White and Black Caribbean']
OA_ethincity_df_P['other_ethnic_group'] = OA_ethincity_df_P['Other ethnic group: Any other ethnic group'] + OA_ethincity_df_P['Other ethnic group: Arab']
OA_ethincity_df_P['all_white_ethnic_groups'] = OA_ethincity_df_P['White: English, Welsh, Scottish, Northern Irish or British'] + OA_ethincity_df_P['White: Gypsy or Irish Traveller'] + OA_ethincity_df_P['White: Irish'] + OA_ethincity_df_P['White: Other White'] + OA_ethincity_df_P['White: Roma']
OA_ethincity_df_P.head()

Ethnic group (20 categories),Output Areas Code,"Asian, Asian British or Asian Welsh: Bangladeshi","Asian, Asian British or Asian Welsh: Chinese","Asian, Asian British or Asian Welsh: Indian","Asian, Asian British or Asian Welsh: Other Asian","Asian, Asian British or Asian Welsh: Pakistani","Black, Black British, Black Welsh, Caribbean or African: African","Black, Black British, Black Welsh, Caribbean or African: Caribbean","Black, Black British, Black Welsh, Caribbean or African: Other Black",Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups,Mixed or Multiple ethnic groups: White and Asian,Mixed or Multiple ethnic groups: White and Black African,Mixed or Multiple ethnic groups: White and Black Caribbean,Other ethnic group: Any other ethnic group,Other ethnic group: Arab,"White: English, Welsh, Scottish, Northern Irish or British",White: Gypsy or Irish Traveller,White: Irish,White: Other White,White: Roma,all_asian_ethnic_groups,all_black_ethnic_groups,all_mixed_or_multiple_ethnic_groups,other_ethnic_group,all_white_ethnic_groups
0,E00000001,0,4,0,0,1,0,3,0,1,5,0,0,7,0,112,0,0,39,4,5,3,6,7,155
1,E00000003,0,6,11,7,0,5,0,0,7,6,0,0,3,1,174,0,0,35,0,24,5,13,4,209
2,E00000005,0,4,4,5,0,0,0,0,2,2,2,0,7,1,65,0,0,20,0,13,0,6,8,85
3,E00000007,0,16,1,7,0,2,0,0,1,2,1,0,3,5,62,0,4,40,0,24,2,4,8,106
4,E00000010,1,3,3,3,0,5,5,2,11,7,3,1,10,1,83,0,0,37,0,10,12,22,11,120

### 2.1.7 Population by age per MSOA

In [14]:
census2021_age_by_single_year_msoa2021_df = pd.read_csv(r"N:\Geodatabase\Raw_Data\Census 2021\Population\census2021_age_by_single_year_msoa2021.csv")
census2021_age_by_single_year_msoa2021_df.head()

,Middle Layer Super Output Areas Code,Middle Layer Super Output Areas,Age (101 categories) Code,Age (101 categories),Observation
0,E02000001,City of London 001,0,Aged under 1 year,44
1,E02000001,City of London 001,1,Aged 1 year,57
2,E02000001,City of London 001,2,Aged 2 years,34
3,E02000001,City of London 001,3,Aged 3 years,39
4,E02000001,City of London 001,4,Aged 4 years,40

In [1]:
MSOA_pop_per_age_df_P = pd.pivot_table(MSOA_pop_per_age_df, values='Observation', index=None, columns=['Age (101 categories)'], aggfunc=np.sum)
MSOA_pop_per_age_df_P = MSOA_pop_per_age_df_P.reset_index()

#renaming
for i in range(1,100):
    MSOA_pop_per_age_df_P.rename(columns = {'Aged ' + str(i) + ' years':'Age_' + str(i)}, inplace = True)
    
MSOA_pop_per_age_df_P.head()

NameError: name 'pd' is not defined

In [16]:
#Create new features

MSOA_pop_per_age_df_P['legal children_0_to_15'] = MSOA_pop_per_age_df_P['Aged under 1 year'] + MSOA_pop_per_age_df_P['Aged 1 year'] + MSOA_pop_per_age_df_P['Age_2'] + MSOA_pop_per_age_df_P['Age_3'] \
                                     + MSOA_pop_per_age_df_P['Age_4'] + MSOA_pop_per_age_df_P['Age_5'] + MSOA_pop_per_age_df_P['Age_6'] + MSOA_pop_per_age_df_P['Age_7'] \
                                     + MSOA_pop_per_age_df_P['Age_8'] + MSOA_pop_per_age_df_P['Age_9'] + MSOA_pop_per_age_df_P['Age_10'] + MSOA_pop_per_age_df_P['Age_11'] \
                                     + MSOA_pop_per_age_df_P['Age_12'] + MSOA_pop_per_age_df_P['Age_13'] + MSOA_pop_per_age_df_P['Age_14'] \
                                     + MSOA_pop_per_age_df_P['Age_15']

MSOA_pop_per_age_df_P['working_age_adults_16_66'] =   MSOA_pop_per_age_df_P['Age_16'] + MSOA_pop_per_age_df_P['Age_17'] + MSOA_pop_per_age_df_P['Age_18'] + MSOA_pop_per_age_df_P['Age_19'] \
                                     + MSOA_pop_per_age_df_P['Age_20'] + MSOA_pop_per_age_df_P['Age_21'] + MSOA_pop_per_age_df_P['Age_22'] + MSOA_pop_per_age_df_P['Age_23'] \
                                     + MSOA_pop_per_age_df_P['Age_24'] + MSOA_pop_per_age_df_P['Age_25'] + MSOA_pop_per_age_df_P['Age_26'] + MSOA_pop_per_age_df_P['Age_27'] \
                                     + MSOA_pop_per_age_df_P['Age_28'] + MSOA_pop_per_age_df_P['Age_29'] + MSOA_pop_per_age_df_P['Age_30'] + MSOA_pop_per_age_df_P['Age_31'] \
                                     + MSOA_pop_per_age_df_P['Age_32'] + MSOA_pop_per_age_df_P['Age_33'] + MSOA_pop_per_age_df_P['Age_34'] + MSOA_pop_per_age_df_P['Age_35'] \
                                     + MSOA_pop_per_age_df_P['Age_36'] + MSOA_pop_per_age_df_P['Age_37'] + MSOA_pop_per_age_df_P['Age_38'] + MSOA_pop_per_age_df_P['Age_39'] \
                                     + MSOA_pop_per_age_df_P['Age_40'] + MSOA_pop_per_age_df_P['Age_41'] + MSOA_pop_per_age_df_P['Age_42'] + MSOA_pop_per_age_df_P['Age_43'] \
                                     + MSOA_pop_per_age_df_P['Age_44'] + MSOA_pop_per_age_df_P['Age_45'] + MSOA_pop_per_age_df_P['Age_46'] + MSOA_pop_per_age_df_P['Age_47'] \
                                     + MSOA_pop_per_age_df_P['Age_48'] + MSOA_pop_per_age_df_P['Age_49'] + MSOA_pop_per_age_df_P['Age_50'] + MSOA_pop_per_age_df_P['Age_51'] \
                                     + MSOA_pop_per_age_df_P['Age_52'] + MSOA_pop_per_age_df_P['Age_53'] + MSOA_pop_per_age_df_P['Age_54'] + MSOA_pop_per_age_df_P['Age_55'] \
                                     + MSOA_pop_per_age_df_P['Age_56'] + MSOA_pop_per_age_df_P['Age_57'] + MSOA_pop_per_age_df_P['Age_58'] + MSOA_pop_per_age_df_P['Age_59'] \
                                     + MSOA_pop_per_age_df_P['Age_60'] + MSOA_pop_per_age_df_P['Age_61'] + MSOA_pop_per_age_df_P['Age_62'] + MSOA_pop_per_age_df_P['Age_63'] \
                                     + MSOA_pop_per_age_df_P['Age_64'] + MSOA_pop_per_age_df_P['Age_65'] + MSOA_pop_per_age_df_P['Age_66']


MSOA_pop_per_age_df_P['non_working_age_adults_66_above'] = MSOA_pop_per_age_df_P['Age_67'] + MSOA_pop_per_age_df_P['Age_68'] + MSOA_pop_per_age_df_P['Age_69'] \
                                     + MSOA_pop_per_age_df_P['Age_70'] + MSOA_pop_per_age_df_P['Age_71'] + MSOA_pop_per_age_df_P['Age_72'] + MSOA_pop_per_age_df_P['Age_73'] \
                                     + MSOA_pop_per_age_df_P['Age_74'] + MSOA_pop_per_age_df_P['Age_75'] + MSOA_pop_per_age_df_P['Age_76'] + MSOA_pop_per_age_df_P['Age_77'] \
                                     + MSOA_pop_per_age_df_P['Age_78'] + MSOA_pop_per_age_df_P['Age_79'] + MSOA_pop_per_age_df_P['Age_80'] + MSOA_pop_per_age_df_P['Age_81'] \
                                     + MSOA_pop_per_age_df_P['Age_82'] + MSOA_pop_per_age_df_P['Age_83'] + MSOA_pop_per_age_df_P['Age_84'] + MSOA_pop_per_age_df_P['Age_85'] \
                                     + MSOA_pop_per_age_df_P['Age_86'] + MSOA_pop_per_age_df_P['Age_87'] + MSOA_pop_per_age_df_P['Age_88'] + MSOA_pop_per_age_df_P['Age_89'] \
                                     + MSOA_pop_per_age_df_P['Age_90'] + MSOA_pop_per_age_df_P['Age_91'] + MSOA_pop_per_age_df_P['Age_92'] + MSOA_pop_per_age_df_P['Age_93'] \
                                     + MSOA_pop_per_age_df_P['Age_94'] + MSOA_pop_per_age_df_P['Age_95'] + MSOA_pop_per_age_df_P['Age_96'] + MSOA_pop_per_age_df_P['Age_97'] \
                                     + MSOA_pop_per_age_df_P['Age_98'] + MSOA_pop_per_age_df_P['Age_99'] + MSOA_pop_per_age_df_P['Aged 100 years and over']

MSOA_pop_per_age_df_P['age_0_to_1'] =  MSOA_pop_per_age_df_P['Aged under 1 year'] 

MSOA_pop_per_age_df_P['age_1_to_9'] =  MSOA_pop_per_age_df_P['Aged under 1 year'] + MSOA_pop_per_age_df_P['Aged 1 year'] + MSOA_pop_per_age_df_P['Age_2'] + MSOA_pop_per_age_df_P['Age_3'] \
                                     + MSOA_pop_per_age_df_P['Age_4'] + MSOA_pop_per_age_df_P['Age_5'] + MSOA_pop_per_age_df_P['Age_6'] + MSOA_pop_per_age_df_P['Age_7'] \
                                     + MSOA_pop_per_age_df_P['Age_8'] + MSOA_pop_per_age_df_P['Age_9']

MSOA_pop_per_age_df_P['age_10_to_19'] =  MSOA_pop_per_age_df_P['Age_10'] + MSOA_pop_per_age_df_P['Age_11'] + MSOA_pop_per_age_df_P['Age_12'] + MSOA_pop_per_age_df_P['Age_13'] \
                                     + MSOA_pop_per_age_df_P['Age_14'] + MSOA_pop_per_age_df_P['Age_15'] + MSOA_pop_per_age_df_P['Age_16'] + MSOA_pop_per_age_df_P['Age_17'] \
                                     + MSOA_pop_per_age_df_P['Age_18'] + MSOA_pop_per_age_df_P['Age_19']

MSOA_pop_per_age_df_P['age_14_to_25'] =  MSOA_pop_per_age_df_P['Age_14'] + MSOA_pop_per_age_df_P['Age_15'] + MSOA_pop_per_age_df_P['Age_16'] + MSOA_pop_per_age_df_P['Age_17'] \
                                     + MSOA_pop_per_age_df_P['Age_18'] + MSOA_pop_per_age_df_P['Age_19'] + MSOA_pop_per_age_df_P['Age_20'] + MSOA_pop_per_age_df_P['Age_21'] + MSOA_pop_per_age_df_P['Age_22'] + MSOA_pop_per_age_df_P['Age_23'] \
                                     + MSOA_pop_per_age_df_P['Age_24'] + MSOA_pop_per_age_df_P['Age_25']

MSOA_pop_per_age_df_P['age_20_to_29'] =  MSOA_pop_per_age_df_P['Age_20'] + MSOA_pop_per_age_df_P['Age_21'] + MSOA_pop_per_age_df_P['Age_22'] + MSOA_pop_per_age_df_P['Age_23'] \
                                     + MSOA_pop_per_age_df_P['Age_24'] + MSOA_pop_per_age_df_P['Age_25'] + MSOA_pop_per_age_df_P['Age_26'] + MSOA_pop_per_age_df_P['Age_27'] \
                                     + MSOA_pop_per_age_df_P['Age_28'] + MSOA_pop_per_age_df_P['Age_29']

MSOA_pop_per_age_df_P['age_30_to_39'] =  MSOA_pop_per_age_df_P['Age_30'] + MSOA_pop_per_age_df_P['Age_31'] + MSOA_pop_per_age_df_P['Age_32'] + MSOA_pop_per_age_df_P['Age_33'] \
                                     + MSOA_pop_per_age_df_P['Age_34'] + MSOA_pop_per_age_df_P['Age_35'] + MSOA_pop_per_age_df_P['Age_36'] + MSOA_pop_per_age_df_P['Age_37'] \
                                     + MSOA_pop_per_age_df_P['Age_38'] + MSOA_pop_per_age_df_P['Age_39']

MSOA_pop_per_age_df_P['age_40_to_49'] =  MSOA_pop_per_age_df_P['Age_40'] + MSOA_pop_per_age_df_P['Age_41'] + MSOA_pop_per_age_df_P['Age_42'] + MSOA_pop_per_age_df_P['Age_43'] \
                                     + MSOA_pop_per_age_df_P['Age_44'] + MSOA_pop_per_age_df_P['Age_45'] + MSOA_pop_per_age_df_P['Age_46'] + MSOA_pop_per_age_df_P['Age_47'] \
                                     + MSOA_pop_per_age_df_P['Age_48'] + MSOA_pop_per_age_df_P['Age_49']

MSOA_pop_per_age_df_P['age_50_to_59'] =  MSOA_pop_per_age_df_P['Age_50'] + MSOA_pop_per_age_df_P['Age_51'] + MSOA_pop_per_age_df_P['Age_52'] + MSOA_pop_per_age_df_P['Age_53'] \
                                     + MSOA_pop_per_age_df_P['Age_54'] + MSOA_pop_per_age_df_P['Age_55'] + MSOA_pop_per_age_df_P['Age_56'] + MSOA_pop_per_age_df_P['Age_57'] \
                                     + MSOA_pop_per_age_df_P['Age_58'] + MSOA_pop_per_age_df_P['Age_59']

MSOA_pop_per_age_df_P['age_60_to_69'] =  MSOA_pop_per_age_df_P['Age_60'] + MSOA_pop_per_age_df_P['Age_61'] + MSOA_pop_per_age_df_P['Age_62'] + MSOA_pop_per_age_df_P['Age_63'] \
                                     + MSOA_pop_per_age_df_P['Age_64'] + MSOA_pop_per_age_df_P['Age_65'] + MSOA_pop_per_age_df_P['Age_66'] + MSOA_pop_per_age_df_P['Age_67'] \
                                     + MSOA_pop_per_age_df_P['Age_68'] + MSOA_pop_per_age_df_P['Age_69']

MSOA_pop_per_age_df_P['age_70_to_79'] =  MSOA_pop_per_age_df_P['Age_70'] + MSOA_pop_per_age_df_P['Age_71'] + MSOA_pop_per_age_df_P['Age_72'] + MSOA_pop_per_age_df_P['Age_73'] \
                                     + MSOA_pop_per_age_df_P['Age_74'] + MSOA_pop_per_age_df_P['Age_75'] + MSOA_pop_per_age_df_P['Age_76'] + MSOA_pop_per_age_df_P['Age_77'] \
                                     + MSOA_pop_per_age_df_P['Age_78'] + MSOA_pop_per_age_df_P['Age_79']

MSOA_pop_per_age_df_P['age_80_to_89'] =  MSOA_pop_per_age_df_P['Age_80'] + MSOA_pop_per_age_df_P['Age_81'] + MSOA_pop_per_age_df_P['Age_82'] + MSOA_pop_per_age_df_P['Age_83'] \
                                     + MSOA_pop_per_age_df_P['Age_84'] + MSOA_pop_per_age_df_P['Age_85'] + MSOA_pop_per_age_df_P['Age_86'] + MSOA_pop_per_age_df_P['Age_87'] \
                                     + MSOA_pop_per_age_df_P['Age_88'] + MSOA_pop_per_age_df_P['Age_89']

MSOA_pop_per_age_df_P['age_90_to_99'] =  MSOA_pop_per_age_df_P['Age_90'] + MSOA_pop_per_age_df_P['Age_91'] + MSOA_pop_per_age_df_P['Age_92'] + MSOA_pop_per_age_df_P['Age_93'] \
                                     + MSOA_pop_per_age_df_P['Age_94'] + MSOA_pop_per_age_df_P['Age_95'] + MSOA_pop_per_age_df_P['Age_96'] + MSOA_pop_per_age_df_P['Age_97'] \
                                     + MSOA_pop_per_age_df_P['Age_98'] + MSOA_pop_per_age_df_P['Age_99']

MSOA_pop_per_age_df_P['age_100_over'] =  MSOA_pop_per_age_df_P['Aged 100 years and over'] 

MSOA_pop_per_age_df_P.drop(MSOA_pop_per_age_df_P.iloc[:, 1:101],axis = 1,inplace = True)
MSOA_pop_per_age_df_P.drop(['Aged under 1 year'],axis = 1,inplace = True)
MSOA_pop_per_age_df_P.rename(columns = {'Middle Layer Super Output Areas Code':'msoa21cd'}, inplace = True)
MSOA_pop_per_age_df_P.head()

Age (101 categories),msoa21cd,legal children_0_to_15,working_age_adults_16_66,non_working_age_adults_66_above,age_0_to_1,age_1_to_9,age_10_to_19,age_14_to_25,age_20_to_29,age_30_to_39,age_40_to_49,age_50_to_59,age_60_to_69,age_70_to_79,age_80_to_89,age_90_to_99,age_100_over
0,E02000001,580,6962,1037,44,374,391,1453,2178,1724,1091,1158,850,528,245,37,3
1,E02000002,2299,5146,836,115,1407,1385,1270,930,1317,1128,873,552,386,238,62,3
2,E02000003,2692,7751,1105,201,1788,1483,1728,1607,1942,1533,1372,905,537,322,57,2
3,E02000004,1328,4429,884,65,838,795,987,914,994,849,857,656,414,246,76,2
4,E02000005,3096,7240,750,162,1952,1716,1752,1312,1874,1681,1287,643,380,208,33,0

# LAD Age

In [17]:
LAD_pop_per_age_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/LAD_Age.csv")
LAD_pop_per_age_df.head()

,Lower tier local authorities Code,Lower tier local authorities,Age (101 categories) Code,Age (101 categories),Observation
0,E06000001,Hartlepool,0,Aged under 1 year,918
1,E06000001,Hartlepool,1,Aged 1 year,954
2,E06000001,Hartlepool,2,Aged 2 years,1046
3,E06000001,Hartlepool,3,Aged 3 years,988
4,E06000001,Hartlepool,4,Aged 4 years,1077

In [18]:
LAD_pop_per_age_df_P = pd.pivot_table(LAD_pop_per_age_df, values='Observation', index=['Lower tier local authorities Code'], columns=['Age (101 categories)'], aggfunc=np.sum)
LAD_pop_per_age_df_P = LAD_pop_per_age_df_P.reset_index()

#renaming
for i in range(1,100):
    LAD_pop_per_age_df_P.rename(columns = {'Aged ' + str(i) + ' years':'Age_' + str(i)}, inplace = True)
    
LAD_pop_per_age_df_P.head()

Age (101 categories),Lower tier local authorities Code,Aged 1 year,Age_10,Aged 100 years and over,Age_11,Age_12,Age_13,Age_14,Age_15,Age_16,Age_17,Age_18,Age_19,Age_2,Age_20,Age_21,Age_22,Age_23,Age_24,Age_25,Age_26,Age_27,Age_28,Age_29,Age_3,Age_30,Age_31,Age_32,Age_33,Age_34,Age_35,Age_36,Age_37,Age_38,Age_39,Age_4,Age_40,Age_41,Age_42,Age_43,Age_44,Age_45,Age_46,Age_47,Age_48,Age_49,Age_5,Age_50,Age_51,Age_52,Age_53,Age_54,Age_55,Age_56,Age_57,Age_58,Age_59,Age_6,Age_60,Age_61,Age_62,Age_63,Age_64,Age_65,Age_66,Age_67,Age_68,Age_69,Age_7,Age_70,Age_71,Age_72,Age_73,Age_74,Age_75,Age_76,Age_77,Age_78,Age_79,Age_8,Age_80,Age_81,Age_82,Age_83,Age_84,Age_85,Age_86,Age_87,Age_88,Age_89,Age_9,Age_90,Age_91,Age_92,Age_93,Age_94,Age_95,Age_96,Age_97,Age_98,Age_99,Aged under 1 year
0,E06000001,954,1167,21,1238,1188,1190,1137,1168,1091,1085,927,909,1046,983,1014,1062,999,1052,1064,1077,1114,1105,1135,988,1195,1129,1177,1184,1199,1106,1139,1080,1057,1081,1077,1071,1110,999,948,937,1019,944,1058,1141,1255,1109,1309,1253,1308,1351,1357,1436,1450,1433,1411,1400,1032,1384,1264,1277,1186,1184,1121,1053,1010,1043,1020,1097,956,1030,1017,1067,1014,762,719,616,567,558,1172,503,515,495,509,441,378,340,288,268,216,1172,181,130,110,92,62,48,30,19,19,14,918
1,E06000002,1720,2033,22,1969,1824,1832,1807,1798,1763,1718,1654,1638,1766,1898,1977,2006,2208,2082,2072,2058,2070,2045,2077,1908,2017,2039,2105,2084,2075,2050,1958,1918,1748,1701,1913,1761,1737,1652,1445,1447,1566,1503,1590,1586,1685,1861,1713,1700,1688,1817,1818,1872,1910,1851,1886,1850,1920,1787,1716,1757,1786,1674,1529,1523,1435,1406,1315,1950,1306,1266,1256,1291,1343,962,938,822,816,762,2079,707,667,658,639,565,518,432,392,335,282,1985,248,217,153,112,82,61,47,38,18,15,1621
2,E06000003,1347,1601,24,1596,1562,1599,1635,1508,1553,1513,1290,1260,1353,1158,1281,1366,1319,1451,1459,1417,1451,1500,1634,1429,1634,1559,1545,1593,1578,1582,1579,1497,1460,1488,1509,1616,1548,1432,1346,1309,1451,1447,1563,1696,1792,1461,1927,1922,1981,1987,2195,2171,2067,2185,2108,2124,1503,1956,1926,1977,1913,1792,1762,1654,1751,1657,1673,1513,1598,1677,1745,1831,1824,1422,1465,1245,1143,1066,1657,1000,977,936,830,736,656,553,488,410,340,1740,323,256,187,150,129,85,64,48,26,18,1176
3,E06000004,2078,2688,28,2583,2677,2548,2525,2402,2321,2359,1899,1636,2150,1700,1813,1883,2000,2293,2139,2212,2477,2499,2591,2178,2639,2513,2608,2695,2680,2702,2679,2612,2595,2464,2411,2688,2518,2515,2168,2077,2273,2307,2441,2392,2762,2344,2784,2719,2773,2797,2859,2783,2754,2863,2853,2757,2314,2670,2571,2560,2438,2495,2319,2140,2193,2102,2039,2459,2028,1938,2054,2189,2043,1482,1589,1355,1216,1230,2722,1103,1037,1050,928,836,753,610,535,509,459,2590,408,262,224,144,120,88,55,54,34,29,1916
4,E06000005,1048,1345,22,1340,1350,1306,1285,1243,1303,1238,1150,854,1109,817,1037,1123,1196,1253,1228,1203,1309,1284,1355,1167,1482,1363,1367,1382,1374,1362,1293,1330,1290,1287,1130,1358,1400,1409,1251,1224,1256,1312,1397,1416,1537,1220,1578,1527,1514,1522,1629,1595,1621,1547,1588,1504,1229,1530,1356,1439,1415,1264,1285,1127,1224,1169,1154,1257,1121,1145,1205,1285,1224,942,995,825,716,672,1305,679,656,678,587,519,460,425,362,313,281,1319,241,178,137,105,104,73,53,20,38,25,1040

In [19]:
#Create new features

LAD_pop_per_age_df_P['legal children_0_to_15'] = LAD_pop_per_age_df_P['Aged under 1 year'] + LAD_pop_per_age_df_P['Aged 1 year'] + LAD_pop_per_age_df_P['Age_2'] + LAD_pop_per_age_df_P['Age_3'] \
                                     + LAD_pop_per_age_df_P['Age_4'] + LAD_pop_per_age_df_P['Age_5'] + LAD_pop_per_age_df_P['Age_6'] + LAD_pop_per_age_df_P['Age_7'] \
                                     + LAD_pop_per_age_df_P['Age_8'] + LAD_pop_per_age_df_P['Age_9'] + LAD_pop_per_age_df_P['Age_10'] + LAD_pop_per_age_df_P['Age_11'] \
                                     + LAD_pop_per_age_df_P['Age_12'] + LAD_pop_per_age_df_P['Age_13'] + LAD_pop_per_age_df_P['Age_14'] \
                                     + LAD_pop_per_age_df_P['Age_15']

LAD_pop_per_age_df_P['working_age_adults_16_66'] =   LAD_pop_per_age_df_P['Age_16'] + LAD_pop_per_age_df_P['Age_17'] + LAD_pop_per_age_df_P['Age_18'] + LAD_pop_per_age_df_P['Age_19'] \
                                     + LAD_pop_per_age_df_P['Age_20'] + LAD_pop_per_age_df_P['Age_21'] + LAD_pop_per_age_df_P['Age_22'] + LAD_pop_per_age_df_P['Age_23'] \
                                     + LAD_pop_per_age_df_P['Age_24'] + LAD_pop_per_age_df_P['Age_25'] + LAD_pop_per_age_df_P['Age_26'] + LAD_pop_per_age_df_P['Age_27'] \
                                     + LAD_pop_per_age_df_P['Age_28'] + LAD_pop_per_age_df_P['Age_29'] + LAD_pop_per_age_df_P['Age_30'] + LAD_pop_per_age_df_P['Age_31'] \
                                     + LAD_pop_per_age_df_P['Age_32'] + LAD_pop_per_age_df_P['Age_33'] + LAD_pop_per_age_df_P['Age_34'] + LAD_pop_per_age_df_P['Age_35'] \
                                     + LAD_pop_per_age_df_P['Age_36'] + LAD_pop_per_age_df_P['Age_37'] + LAD_pop_per_age_df_P['Age_38'] + LAD_pop_per_age_df_P['Age_39'] \
                                     + LAD_pop_per_age_df_P['Age_40'] + LAD_pop_per_age_df_P['Age_41'] + LAD_pop_per_age_df_P['Age_42'] + LAD_pop_per_age_df_P['Age_43'] \
                                     + LAD_pop_per_age_df_P['Age_44'] + LAD_pop_per_age_df_P['Age_45'] + LAD_pop_per_age_df_P['Age_46'] + LAD_pop_per_age_df_P['Age_47'] \
                                     + LAD_pop_per_age_df_P['Age_48'] + LAD_pop_per_age_df_P['Age_49'] + LAD_pop_per_age_df_P['Age_50'] + LAD_pop_per_age_df_P['Age_51'] \
                                     + LAD_pop_per_age_df_P['Age_52'] + LAD_pop_per_age_df_P['Age_53'] + LAD_pop_per_age_df_P['Age_54'] + LAD_pop_per_age_df_P['Age_55'] \
                                     + LAD_pop_per_age_df_P['Age_56'] + LAD_pop_per_age_df_P['Age_57'] + LAD_pop_per_age_df_P['Age_58'] + LAD_pop_per_age_df_P['Age_59'] \
                                     + LAD_pop_per_age_df_P['Age_60'] + LAD_pop_per_age_df_P['Age_61'] + LAD_pop_per_age_df_P['Age_62'] + LAD_pop_per_age_df_P['Age_63'] \
                                     + LAD_pop_per_age_df_P['Age_64'] + LAD_pop_per_age_df_P['Age_65'] + LAD_pop_per_age_df_P['Age_66']


LAD_pop_per_age_df_P['non_working_age_adults_66_above'] = LAD_pop_per_age_df_P['Age_67'] + LAD_pop_per_age_df_P['Age_68'] + LAD_pop_per_age_df_P['Age_69'] \
                                     + LAD_pop_per_age_df_P['Age_70'] + LAD_pop_per_age_df_P['Age_71'] + LAD_pop_per_age_df_P['Age_72'] + LAD_pop_per_age_df_P['Age_73'] \
                                     + LAD_pop_per_age_df_P['Age_74'] + LAD_pop_per_age_df_P['Age_75'] + LAD_pop_per_age_df_P['Age_76'] + LAD_pop_per_age_df_P['Age_77'] \
                                     + LAD_pop_per_age_df_P['Age_78'] + LAD_pop_per_age_df_P['Age_79'] + LAD_pop_per_age_df_P['Age_80'] + LAD_pop_per_age_df_P['Age_81'] \
                                     + LAD_pop_per_age_df_P['Age_82'] + LAD_pop_per_age_df_P['Age_83'] + LAD_pop_per_age_df_P['Age_84'] + LAD_pop_per_age_df_P['Age_85'] \
                                     + LAD_pop_per_age_df_P['Age_86'] + LAD_pop_per_age_df_P['Age_87'] + LAD_pop_per_age_df_P['Age_88'] + LAD_pop_per_age_df_P['Age_89'] \
                                     + LAD_pop_per_age_df_P['Age_90'] + LAD_pop_per_age_df_P['Age_91'] + LAD_pop_per_age_df_P['Age_92'] + LAD_pop_per_age_df_P['Age_93'] \
                                     + LAD_pop_per_age_df_P['Age_94'] + LAD_pop_per_age_df_P['Age_95'] + LAD_pop_per_age_df_P['Age_96'] + LAD_pop_per_age_df_P['Age_97'] \
                                     + LAD_pop_per_age_df_P['Age_98'] + LAD_pop_per_age_df_P['Age_99'] + LAD_pop_per_age_df_P['Aged 100 years and over']

LAD_pop_per_age_df_P['age_0_to_1'] =  LAD_pop_per_age_df_P['Aged under 1 year'] 

LAD_pop_per_age_df_P['age_1_to_9'] =  LAD_pop_per_age_df_P['Aged under 1 year'] + LAD_pop_per_age_df_P['Aged 1 year'] + LAD_pop_per_age_df_P['Age_2'] + LAD_pop_per_age_df_P['Age_3'] \
                                     + LAD_pop_per_age_df_P['Age_4'] + LAD_pop_per_age_df_P['Age_5'] + LAD_pop_per_age_df_P['Age_6'] + LAD_pop_per_age_df_P['Age_7'] \
                                     + LAD_pop_per_age_df_P['Age_8'] + LAD_pop_per_age_df_P['Age_9']

LAD_pop_per_age_df_P['age_10_to_19'] =  LAD_pop_per_age_df_P['Age_10'] + LAD_pop_per_age_df_P['Age_11'] + LAD_pop_per_age_df_P['Age_12'] + LAD_pop_per_age_df_P['Age_13'] \
                                     + LAD_pop_per_age_df_P['Age_14'] + LAD_pop_per_age_df_P['Age_15'] + LAD_pop_per_age_df_P['Age_16'] + LAD_pop_per_age_df_P['Age_17'] \
                                     + LAD_pop_per_age_df_P['Age_18'] + LAD_pop_per_age_df_P['Age_19']

LAD_pop_per_age_df_P['age_14_to_25'] =  LAD_pop_per_age_df_P['Age_14'] + LAD_pop_per_age_df_P['Age_15'] + LAD_pop_per_age_df_P['Age_16'] + LAD_pop_per_age_df_P['Age_17'] \
                                     + LAD_pop_per_age_df_P['Age_18'] + LAD_pop_per_age_df_P['Age_19'] + LAD_pop_per_age_df_P['Age_20'] + LAD_pop_per_age_df_P['Age_21'] + LAD_pop_per_age_df_P['Age_22'] + LAD_pop_per_age_df_P['Age_23'] \
                                     + LAD_pop_per_age_df_P['Age_24'] + LAD_pop_per_age_df_P['Age_25']

LAD_pop_per_age_df_P['age_20_to_29'] =  LAD_pop_per_age_df_P['Age_20'] + LAD_pop_per_age_df_P['Age_21'] + LAD_pop_per_age_df_P['Age_22'] + LAD_pop_per_age_df_P['Age_23'] \
                                     + LAD_pop_per_age_df_P['Age_24'] + LAD_pop_per_age_df_P['Age_25'] + LAD_pop_per_age_df_P['Age_26'] + LAD_pop_per_age_df_P['Age_27'] \
                                     + LAD_pop_per_age_df_P['Age_28'] + LAD_pop_per_age_df_P['Age_29']

LAD_pop_per_age_df_P['age_30_to_39'] =  LAD_pop_per_age_df_P['Age_30'] + LAD_pop_per_age_df_P['Age_31'] + LAD_pop_per_age_df_P['Age_32'] + LAD_pop_per_age_df_P['Age_33'] \
                                     + LAD_pop_per_age_df_P['Age_34'] + LAD_pop_per_age_df_P['Age_35'] + LAD_pop_per_age_df_P['Age_36'] + LAD_pop_per_age_df_P['Age_37'] \
                                     + LAD_pop_per_age_df_P['Age_38'] + LAD_pop_per_age_df_P['Age_39']

LAD_pop_per_age_df_P['age_40_to_49'] =  LAD_pop_per_age_df_P['Age_40'] + LAD_pop_per_age_df_P['Age_41'] + LAD_pop_per_age_df_P['Age_42'] + LAD_pop_per_age_df_P['Age_43'] \
                                     + LAD_pop_per_age_df_P['Age_44'] + LAD_pop_per_age_df_P['Age_45'] + LAD_pop_per_age_df_P['Age_46'] + LAD_pop_per_age_df_P['Age_47'] \
                                     + LAD_pop_per_age_df_P['Age_48'] + LAD_pop_per_age_df_P['Age_49']

LAD_pop_per_age_df_P['age_50_to_59'] =  LAD_pop_per_age_df_P['Age_50'] + LAD_pop_per_age_df_P['Age_51'] + LAD_pop_per_age_df_P['Age_52'] + LAD_pop_per_age_df_P['Age_53'] \
                                     + LAD_pop_per_age_df_P['Age_54'] + LAD_pop_per_age_df_P['Age_55'] + LAD_pop_per_age_df_P['Age_56'] + LAD_pop_per_age_df_P['Age_57'] \
                                     + LAD_pop_per_age_df_P['Age_58'] + LAD_pop_per_age_df_P['Age_59']

LAD_pop_per_age_df_P['age_60_to_69'] =  LAD_pop_per_age_df_P['Age_60'] + LAD_pop_per_age_df_P['Age_61'] + LAD_pop_per_age_df_P['Age_62'] + LAD_pop_per_age_df_P['Age_63'] \
                                     + LAD_pop_per_age_df_P['Age_64'] + LAD_pop_per_age_df_P['Age_65'] + LAD_pop_per_age_df_P['Age_66'] + LAD_pop_per_age_df_P['Age_67'] \
                                     + LAD_pop_per_age_df_P['Age_68'] + LAD_pop_per_age_df_P['Age_69']

LAD_pop_per_age_df_P['age_70_to_79'] =  LAD_pop_per_age_df_P['Age_70'] + LAD_pop_per_age_df_P['Age_71'] + LAD_pop_per_age_df_P['Age_72'] + LAD_pop_per_age_df_P['Age_73'] \
                                     + LAD_pop_per_age_df_P['Age_74'] + LAD_pop_per_age_df_P['Age_75'] + LAD_pop_per_age_df_P['Age_76'] + LAD_pop_per_age_df_P['Age_77'] \
                                     + LAD_pop_per_age_df_P['Age_78'] + LAD_pop_per_age_df_P['Age_79']

LAD_pop_per_age_df_P['age_80_to_89'] =  LAD_pop_per_age_df_P['Age_80'] + LAD_pop_per_age_df_P['Age_81'] + LAD_pop_per_age_df_P['Age_82'] + LAD_pop_per_age_df_P['Age_83'] \
                                     + LAD_pop_per_age_df_P['Age_84'] + LAD_pop_per_age_df_P['Age_85'] + LAD_pop_per_age_df_P['Age_86'] + LAD_pop_per_age_df_P['Age_87'] \
                                     + LAD_pop_per_age_df_P['Age_88'] + LAD_pop_per_age_df_P['Age_89']

LAD_pop_per_age_df_P['age_90_to_99'] =  LAD_pop_per_age_df_P['Age_90'] + LAD_pop_per_age_df_P['Age_91'] + LAD_pop_per_age_df_P['Age_92'] + LAD_pop_per_age_df_P['Age_93'] \
                                     + LAD_pop_per_age_df_P['Age_94'] + LAD_pop_per_age_df_P['Age_95'] + LAD_pop_per_age_df_P['Age_96'] + LAD_pop_per_age_df_P['Age_97'] \
                                     + LAD_pop_per_age_df_P['Age_98'] + LAD_pop_per_age_df_P['Age_99']

LAD_pop_per_age_df_P['age_100_over'] =  LAD_pop_per_age_df_P['Aged 100 years and over'] 

LAD_pop_per_age_df_P.drop(LAD_pop_per_age_df_P.iloc[:, 1:101],axis = 1,inplace = True)
LAD_pop_per_age_df_P.drop(['Aged under 1 year'],axis = 1,inplace = True)
LAD_pop_per_age_df_P.rename(columns = {'Lower tier local authorities Code':'lad22cd'}, inplace = True)
LAD_pop_per_age_df_P.head()

Age (101 categories),lad22cd,legal children_0_to_15,working_age_adults_16_66,non_working_age_adults_66_above,age_0_to_1,age_1_to_9,age_10_to_19,age_14_to_25,age_20_to_29,age_30_to_39,age_40_to_49,age_50_to_59,age_60_to_69,age_70_to_79,age_80_to_89,age_90_to_99,age_100_over
0,E06000001,17653,58623,16058,918,10565,11100,12491,10605,11347,10482,13708,11542,8306,3953,705,21
1,E06000002,29986,92810,21126,1621,18723,18036,22621,20493,19695,15972,18105,15928,10762,5195,991,22
2,E06000003,24189,84014,28333,1176,14688,15117,16793,14036,15515,15200,20667,18061,15016,6926,1286,24
3,E06000004,38585,125285,32724,1916,23162,23638,24970,21607,26187,24141,27942,23527,17124,7820,1418,28
4,E06000005,19693,68481,19633,1040,11824,12414,13727,11805,13530,13560,15625,12963,10130,4960,974,22

### 2.1.7 Health Metric by MSOA

In [20]:
MSOA_health_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/MSOA_Health_Data_csv.csv")
MSOA_health_df.rename(columns = {'Area Code':'msoa21cd'},inplace = True)
MSOA_health_df.drop(['Area Name'],1,inplace=True)
MSOA_health_df.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\4284785816.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  MSOA_health_df.drop(['Area Name'],1,inplace=True)

,msoa21cd,life_expectancy_male_at_birth_2016_2020,life_expectancy_female_at_birth_2016_2020,life_expectancy_average_at_birth_2016_2020,rate_mortality_all_causes_all_ages_per_100_2016_2020,rate_mortality_all_causes_under_75_per_100_2016_2020,rate_mortality_cancer_per_100_2016_2020,rate_mortality_cancer_under_75_per_100_2016_2020,rate_mortality_circulatory_disease_per_100_2016_2020,rate_mortality_circulatory_disease_under_75_per_100_2016_2020,rate_mortality_coronary_heart_disease_per_100_2016_2020,rate_mortality_stroke_per_100_2016_2020,rate_mortality_respiratory_diseases_per_100_2016_2020,rate_mortality_respiratory_diseases_under_75_per_100_2016_2020,percentage_old_age_pop_living_alone_65_plus_2011,old_age_pop_living_alone_65_plus_2011,percentage_households_in_poverty_2013_2014,percentage_household_with_overcrowding_2011,household_with_overcrowding_2011,percentage_unemployment_working_age_claiming_out_of_work_benefit_2021,unemployed_working_age_claiming_out_of_work_benefit_2021,rate_long_term_unemployment_per_1000_working_age_population_2021,long_term_unemployment_2021,percentage_reception_overweight_including_obesity,reception_overweight_including_obesity,percentage_reception_obesity_including_severe_obesity,reception_obesity_including_severe_obesity,percentage_year6_overweight_including_obesity,year6_overweight_including_obesity,percentage_year6_obese_including_severe_obesity,year6_obese_including_severe_obesity
0,E02000001,90.368903,90.737293,90.553098,50.247355,61.290593,65.183666,67.478951,55.775547,64.748007,73.347225,35.621603,36.508637,71.472594,50.821256,526,15.5,34.595211,1517,3.675168,276.666667,1.328374,10.00,26.66667,20,0.00000,0,35.71429,25,14.28571,10
1,E02000002,78.774088,81.704768,80.239428,99.344041,132.848007,112.130843,135.386944,92.922057,142.866305,83.598469,73.317476,102.475182,120.340653,37.148047,409,28.1,14.743826,400,8.493659,392.916667,4.053178,18.75,28.16901,100,12.67606,45,48.14815,195,33.33333,135
2,E02000003,78.441644,84.285725,81.363685,94.424566,109.105081,89.812507,90.736002,104.476530,143.473019,96.669062,87.573001,115.420217,98.458641,36.406250,466,21.6,14.058425,539,7.542906,547.916667,1.720815,12.50,20.61856,100,10.30928,50,42.85714,195,29.67033,135
3,E02000004,77.937114,81.709185,79.823150,113.410620,114.107227,112.164249,116.986639,95.596398,87.915240,107.077043,93.337770,129.338925,136.803642,31.916996,323,22.2,8.110440,188,7.960905,336.666667,3.251360,13.75,21.56863,55,9.80392,25,44.00000,110,32.00000,80
4,E02000005,78.987501,83.884420,81.435961,98.243799,109.845725,108.499515,110.294040,101.255854,162.164843,110.991609,68.158421,129.804013,130.078418,39.217759,371,23.1,15.142947,482,7.722539,514.166667,2.816161,18.75,24.27184,125,12.62136,65,46.60194,240,31.06796,160

### 2.1.8 Relegion per OA

In [21]:
OA_relegion_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Relegion_per_OA.csv")
OA_relegion_df .head()

,Output Areas Code,Output Areas,Religion (10 categories) Code,Religion (10 categories),Observation
0,E00000001,E00000001,-8,Does not apply,0
1,E00000001,E00000001,1,No religion,91
2,E00000001,E00000001,2,Christian,74
3,E00000001,E00000001,3,Buddhist,0
4,E00000001,E00000001,4,Hindu,0

In [22]:
OA_relegion_df_P = pd.pivot_table(OA_relegion_df, values='Observation', index=['Output Areas Code'], columns=['Religion (10 categories)'], aggfunc=np.sum)
OA_relegion_df_P = OA_relegion_df_P.reset_index()
OA_relegion_df_P.drop(['Does not apply'], 1, inplace=True)
OA_relegion_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\2963102915.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_relegion_df_P.drop(['Does not apply'], 1, inplace=True)

Religion (10 categories),Output Areas Code,Buddhist,Christian,Hindu,Jewish,Muslim,No religion,Not answered,Other religion,Sikh
0,E00000001,0,74,0,0,3,91,7,0,0
1,E00000003,1,79,10,3,6,122,32,3,0
2,E00000005,0,40,2,3,1,50,14,2,0
3,E00000007,4,61,0,1,4,65,10,0,0
4,E00000010,0,62,0,3,4,84,25,0,0

### 2.1.9 Economic activity

In [23]:
OA_economic_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Economic activity status_per_OA.csv")
OA_economic_df_P = pd.pivot_table(OA_economic_df, values='Observation', index=['Output Areas Code'], columns=['Economic activity status (20 categories)'], aggfunc=np.sum)
OA_economic_df_P = OA_economic_df_P.reset_index()
OA_economic_df_P.drop(['Does not apply'], 1, inplace=True)
OA_economic_df_P .head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\285760652.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_economic_df_P.drop(['Does not apply'], 1, inplace=True)

Economic activity status (20 categories),Output Areas Code,Economically Inactive: Looking after home or family,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time,Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically active and a full-time student: In employment: Employee: Full-time,Economically active and a full-time student: In employment: Employee: Part-time,Economically active and a full-time student: In employment: Self-employed with employees: Full-time,Economically active and a full-time student: In employment: Self-employed with employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Student
0,E00000001,2,44,17,7,1,9,10,10,0,0,0,0,0,0,0,1,3,52,5
1,E00000003,6,73,17,9,1,16,18,5,0,1,0,0,0,0,0,0,1,57,19
2,E00000005,3,38,7,6,0,10,4,3,0,1,0,0,0,0,0,1,6,23,3
3,E00000007,1,87,7,1,0,6,8,1,0,0,0,0,0,0,0,1,2,17,11
4,E00000010,0,66,11,3,0,15,15,18,0,0,0,0,1,0,0,9,9,15,8

In [24]:
#Create features
OA_economic_df_P['Economically_Active'] = (OA_economic_df_P['Economically active (excluding full-time students): In employment: Employee: Part-time'] + 
                                          OA_economic_df_P['Economically active (excluding full-time students): In employment: Employee: Full-time'] + 
                                          OA_economic_df_P['Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time'] + 
                                          OA_economic_df_P['Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time'] + 
                                          OA_economic_df_P['Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time'] + 
                                          OA_economic_df_P['Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time'] +
                                          OA_economic_df_P['Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks'])
                                         
OA_economic_df_P['Economically_Active_Employeed'] = (OA_economic_df_P['Economically active (excluding full-time students): In employment: Employee: Part-time'] + 
                                OA_economic_df_P['Economically active (excluding full-time students): In employment: Employee: Full-time'] +
                               OA_economic_df_P['Economically active and a full-time student: In employment: Employee: Part-time'] + 
                                OA_economic_df_P['Economically active and a full-time student: In employment: Employee: Full-time'])

OA_economic_df_P['Economically_Active_Self_Employed'] = (OA_economic_df_P['Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time'] +
                                     OA_economic_df_P['Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time'] + 
                                     OA_economic_df_P['Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time'] + 
                                     OA_economic_df_P['Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time'])

OA_economic_df_P['Economically_Active_Student'] = (OA_economic_df_P['Economically active and a full-time student: In employment: Employee: Part-time'] + 
                                                  OA_economic_df_P['Economically active and a full-time student: In employment: Employee: Full-time'] + 
                                                  OA_economic_df_P['Economically active and a full-time student: In employment: Self-employed with employees: Part-time'] +
                                                  OA_economic_df_P['Economically active and a full-time student: In employment: Self-employed with employees: Full-time'] + 
                                                  OA_economic_df_P['Economically active and a full-time student: In employment: Self-employed without employees: Part-time'] + 
                                                  OA_economic_df_P['Economically active and a full-time student: In employment: Self-employed without employees: Full-time'])

OA_economic_df_P['Economically_Inactive'] = (OA_economic_df_P['Economically inactive: Retired'] + 
                                            OA_economic_df_P['Economically inactive: Student'] + 
                                            OA_economic_df_P['Economically Inactive: Looking after home or family'] + 
                                            OA_economic_df_P['Economically inactive: Long-term sick or disabled'] + 
                                            OA_economic_df_P['Economically inactive: Other'])

#OA_economic_df_P.drop(OA_economic_df_P.iloc[:, 1:20],axis = 1,inplace = True)

OA_economic_df_P.head()

Economic activity status (20 categories),Output Areas Code,Economically Inactive: Looking after home or family,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time,Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically active and a full-time student: In employment: Employee: Full-time,Economically active and a full-time student: In employment: Employee: Part-time,Economically active and a full-time student: In employment: Self-employed with employees: Full-time,Economically active and a full-time student: In employment: Self-employed with employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Student,Economically_Active,Economically_Active_Employeed,Economically_Active_Self_Employed,Economically_Active_Student,Economically_Inactive
0,E00000001,2,44,17,7,1,9,10,10,0,0,0,0,0,0,0,1,3,52,5,98,61,27,0,63
1,E00000003,6,73,17,9,1,16,18,5,0,1,0,0,0,0,0,0,1,57,19,139,91,44,1,83
2,E00000005,3,38,7,6,0,10,4,3,0,1,0,0,0,0,0,1,6,23,3,68,46,20,1,36
3,E00000007,1,87,7,1,0,6,8,1,0,0,0,0,0,0,0,1,2,17,11,110,94,15,0,32
4,E00000010,0,66,11,3,0,15,15,18,0,0,0,0,1,0,0,9,9,15,8,128,77,33,1,41

### 2.1.10 Full time Students per OA

In [25]:
OA_students_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/full_time_students_per_OA.csv")
OA_students_df .head()

,Output Areas Code,Output Areas,Schoolchild or full-time student indicator (3 categories) Code,Schoolchild or full-time student indicator (3 categories),Observation
0,E00000001,E00000001,-8,Does not apply,1
1,E00000001,E00000001,1,Student,18
2,E00000001,E00000001,2,Not a student,158
3,E00000003,E00000003,-8,Does not apply,10
4,E00000003,E00000003,1,Student,44

In [26]:
OA_students_df_P = pd.pivot_table(OA_students_df, values='Observation', index=['Output Areas Code'], columns=['Schoolchild or full-time student indicator (3 categories)'], aggfunc=np.sum)
OA_students_df_P = OA_students_df_P.reset_index()
OA_students_df_P.drop(['Does not apply'], 1, inplace=True)
OA_students_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\2798779365.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_students_df_P.drop(['Does not apply'], 1, inplace=True)

Schoolchild or full-time student indicator (3 categories),Output Areas Code,Not a student,Student
0,E00000001,158,18
1,E00000003,201,44
2,E00000005,102,5
3,E00000007,131,16
4,E00000010,165,11

### 2.1.10 Current Occupation per OA

In [27]:
OA_nssec_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/NS-SeC_per_OA.csv")
OA_nssec_df .head()

,Output Areas Code,Output Areas,National Statistics Socio-economic Classification (NS-SeC) (10 categories) Code,National Statistics Socio-economic Classification (NS-SeC) (10 categories),Observation
0,E00000001,E00000001,-8,Does not apply,15
1,E00000001,E00000001,1,"L1, L2 and L3: Higher managerial, administrati...",80
2,E00000001,E00000001,2,"L4, L5 and L6: Lower managerial, administrativ...",38
3,E00000001,E00000001,3,L7: Intermediate occupations,13
4,E00000001,E00000001,4,L8 and L9: Small employers and own account wor...,9

In [28]:
OA_nssec_df_P = pd.pivot_table(OA_nssec_df, values='Observation', index=['Output Areas Code'], columns=['National Statistics Socio-economic Classification (NS-SeC) (10 categories)'], aggfunc=np.sum)
OA_nssec_df_P = OA_nssec_df_P.reset_index()
OA_nssec_df_P.drop(['Does not apply'], 1, inplace=True)
OA_nssec_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\803233061.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_nssec_df_P.drop(['Does not apply'], 1, inplace=True)

National Statistics Socio-economic Classification (NS-SeC) (10 categories),Output Areas Code,"L1, L2 and L3: Higher managerial, administrative and professional occupations",L10 and L11: Lower supervisory and technical occupations,L12: Semi-routine occupations,L13: Routine occupations,L14.1 and L14.2: Never worked and long-term unemployed,L15: Full-time students,"L4, L5 and L6: Lower managerial, administrative and professional occupations",L7: Intermediate occupations,L8 and L9: Small employers and own account workers
0,E00000001,80,3,5,5,4,2,38,13,9
1,E00000003,96,2,5,2,5,20,58,8,26
2,E00000005,37,0,3,1,1,4,28,8,21
3,E00000007,62,3,3,1,6,10,39,5,11
4,E00000010,34,7,10,14,11,5,45,17,27

### 2.1.11 Travel to Work Method

In [29]:
OA_TTW_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Method of Travel to work_per_OA.csv")
OA_TTW_df.head()

,Output Areas Code,Output Areas,Method used to travel to workplace (12 categories) Code,Method used to travel to workplace (12 categories),Observation
0,E00000001,E00000001,1,Work mainly at or from home,59
1,E00000001,E00000001,2,"Underground, metro, light rail, tram",6
2,E00000001,E00000001,3,Train,1
3,E00000001,E00000001,4,"Bus, minibus or coach",1
4,E00000001,E00000001,5,Taxi,0

In [30]:
OA_TTW_df_P = pd.pivot_table(OA_TTW_df, values='Observation', index=['Output Areas Code'], columns=['Method used to travel to workplace (12 categories)'], aggfunc=np.sum)
OA_TTW_df_P = OA_TTW_df_P.reset_index()
OA_TTW_df_P.drop(['Not in employment or aged 15 years and under'], 1, inplace=True)
OA_TTW_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\2726415558.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_TTW_df_P.drop(['Not in employment or aged 15 years and under'], 1, inplace=True)

Method used to travel to workplace (12 categories),Output Areas Code,Bicycle,"Bus, minibus or coach",Driving a car or van,"Motorcycle, scooter or moped",On foot,Other method of travel to work,Passenger in a car or van,Taxi,Train,"Underground, metro, light rail, tram",Work mainly at or from home
0,E00000001,6,1,1,0,14,0,0,0,1,6,59
1,E00000003,2,0,7,0,7,1,0,0,1,10,105
2,E00000005,2,2,3,1,13,0,0,1,3,4,37
3,E00000007,1,4,5,0,15,0,0,1,2,0,78
4,E00000010,10,5,4,0,20,3,0,0,5,13,55

### 2.1.12 Distance to Work per OA

In [31]:
OA_Dist_TTW_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Distance of Travel to Work_per_OA.csv")
OA_Dist_TTW_df.head()

,Output Areas Code,Output Areas,Distance travelled to work (11 categories) Code,Distance travelled to work (11 categories),Observation
0,E00000001,E00000001,-8,Does not apply,88
1,E00000001,E00000001,1,Less than 2km,8
2,E00000001,E00000001,2,2km to less than 5km,7
3,E00000001,E00000001,3,5km to less than 10km,5
4,E00000001,E00000001,4,10km to less than 20km,2

In [32]:
OA_Dist_TTW_df_P = pd.pivot_table(OA_Dist_TTW_df, values='Observation', index=['Output Areas Code'], columns=['Distance travelled to work (11 categories)'], aggfunc=np.sum)
OA_Dist_TTW_df_P = OA_Dist_TTW_df_P.reset_index()
OA_Dist_TTW_df_P.drop(['Does not apply'], 1, inplace=True)
OA_Dist_TTW_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\1873543511.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_Dist_TTW_df_P.drop(['Does not apply'], 1, inplace=True)

Distance travelled to work (11 categories),Output Areas Code,10km to less than 20km,20km to less than 30km,2km to less than 5km,30km to less than 40km,40km to less than 60km,5km to less than 10km,60km and over,Less than 2km,"Works mainly at an offshore installation, in no fixed place, or outside the UK",Works mainly from home
0,E00000001,2,0,7,0,1,5,1,8,5,59
1,E00000003,2,1,7,0,0,11,0,5,3,105
2,E00000005,1,0,8,0,0,3,0,11,6,37
3,E00000007,2,0,5,0,0,4,2,13,2,78
4,E00000010,4,0,9,0,0,4,1,29,11,55

### 2.1.13 Household deprivation per OA

In [33]:
OA_Deprivation_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Household_deprivation_per_OA.csv")
OA_Deprivation_df.head()

,Output Areas Code,Output Areas,Household deprivation (6 categories) Code,Household deprivation (6 categories),Observation
0,E00000001,E00000001,-8,Does not apply,0
1,E00000001,E00000001,1,Household is not deprived in any dimension,66
2,E00000001,E00000001,2,Household is deprived in one dimension,22
3,E00000001,E00000001,3,Household is deprived in two dimensions,3
4,E00000001,E00000001,4,Household is deprived in three dimensions,0

In [34]:
OA_Deprivation_df_P = pd.pivot_table(OA_Deprivation_df, values='Observation', index=['Output Areas Code'], columns=['Household deprivation (6 categories)'], aggfunc=np.sum)
OA_Deprivation_df_P = OA_Deprivation_df_P.reset_index()
OA_Deprivation_df_P.drop(['Does not apply'], 1, inplace=True)
OA_Deprivation_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\1729226482.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_Deprivation_df_P.drop(['Does not apply'], 1, inplace=True)

Household deprivation (6 categories),Output Areas Code,Household is deprived in four dimensions,Household is deprived in one dimension,Household is deprived in three dimensions,Household is deprived in two dimensions,Household is not deprived in any dimension
0,E00000001,0,22,0,3,66
1,E00000003,0,30,0,5,74
2,E00000005,0,15,0,2,48
3,E00000007,0,15,1,1,69
4,E00000010,1,56,7,22,40

### 2.1.15 LA IMD

In [35]:
LA_IMD_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/File_10_-_IoD2019_Local_Authority_District_Summaries__lower-tier__csv.csv")

#renaming
LA_IMD_df.rename(columns = {'Local Authority District code (2019)':'lad22cd'}, inplace = True)
LA_IMD_df.head()

,lad22cd,Local Authority District name (2019),IMD - Average rank,IMD - Rank of average rank,IMD - Average score,IMD - Rank of average score,IMD - Proportion of LSOAs in most deprived 10% nationally,IMD - Rank of proportion of LSOAs in most deprived 10% nationally,IMD 2019 - Extent,IMD 2019 - Rank of extent,IMD 2019 - Local concentration,IMD 2019 - Rank of local concentration,Income - Average rank,Income - Rank of average rank,Income - Average score,Income - Rank of average score,Income - Proportion of LSOAs in most deprived 10% nationally,Income - Rank of proportion of LSOAs in most deprived 10% nationally,Income scale,Rank of Income Scale,Employment - Average rank,Employment - Rank of average rank,Employment - Average score,Employment - Rank of average score,Employment - Proportion of LSOAs in most deprived 10% nationally,Employment - Rank of proportion of LSOAs in most deprived 10% nationally,Employment scale,Rank of Employment Scale,"Education, Skills and Training - Average rank","Education, Skills and Training - Rank of average rank","Education, Skills and Training - Average score","Education, Skills and Training - Rank of average score","Education, Skills and Training - Proportion of LSOAs in most deprived 10% nationally","Education, Skills and Training - Rank of proportion of LSOAs in most deprived 10% nationally",Health Deprivation and Disability - Average rank,Health Deprivation and Disability - Rank of average rank,Health Deprivation and Disability - Average score,Health Deprivation and Disability - Rank of average score,Health Deprivation and Disability - Proportion of LSOAs in most deprived 10% nationally,Health Deprivation and Disability - Rank of proportion of LSOAs in most deprived 10% nationally,Crime - Average rank,Crime - Rank of average rank,Crime - Average score,Crime - Rank of average score,Crime - Proportion of LSOAs in most deprived 10% nationally,Crime - Rank of proportion of LSOAs in most deprived 10% nationally,Barriers to Housing and Services - Average rank,Barriers to Housing and Services - Rank of average rank,Barriers to Housing and Services - Average score,Barriers to Housing and Services - Rank of average score,Barriers to Housing and Services - Proportion of LSOAs in most deprived 10% nationally,Barriers to Housing and Services - Rank of proportion of LSOAs in most deprived 10% nationally,Living Environment - Average rank,Living Environment - Rank of average rank,Living Environment - Average score,Living Environment - Rank of average score,Living Environment - Proportion of LSOAs in most deprived 10% nationally,Living Environment - Rank of proportion of LSOAs in most deprived 10% nationally,IDACI - Average rank,IDACI - Rank of average rank,IDACI - Average score,IDACI - Rank of average score,IDACI - Proportion of LSOAs in most deprived 10% nationally,IDACI - Rank of proportion of LSOAs in most deprived 10% nationally,IDAOPI - Average rank,IDAOPI - Rank of average rank,IDAOPI - Average score,IDAOPI - Rank of average score,IDAOPI - Proportion of LSOAs in most deprived 10% nationally,IDAOPI - Rank of proportion of LSOAs in most deprived 10% nationally
0,E06000001,Hartlepool,22581.98,25,35.037,10,0.3621,10,0.4973,14,32560.44,10,23509.14,16,0.228,5,0.3793,7,21084,110,24902.51,5,0.185,4,0.4310,5,9715.25,111,"19,980.79",77,30.255,51,0.2069,38,25806.04,21,0.869,16,0.3621,16,"22,855.72",27,0.566,25,0.3276,14,9407.74,284,14.242,283,0.0000,250,5359.48,307,6.943,307,0.0000,251,23480.37,22,0.283,8,0.4310,3,21237.10,29,0.228,26,0.2931,15
1,E06000002,Middlesbrough,23729.10,16,40.460,5,0.4884,1,0.5710,6,32726.13,3,23950.79,9,0.251,1,0.5000,1,34959,59,25231.38,4,0.191,3,0.4884,2,15542.50,62,"22,111.75",36,38.850,8,0.3953,3,27603.83,9,1.194,6,0.5698,4,"23,671.36",20,0.701,15,0.4535,3,9341.76,286,14.183,284,0.0000,250,10453.74,262,12.929,259,0.0000,251,25026.00,7,0.327,1,0.4767,1,20061.41,39,0.233,22,0.3837,11
2,E06000003,Redcar and Cleveland,20348.40,62,29.792,40,0.2386,29,0.3630,43,32545.62,11,20604.49,50,0.186,28,0.2614,24,25142,96,23809.65,17,0.165,8,0.3295,12,12291.00,86,"18,997.48",102,27.768,73,0.1932,46,25339.55,26,0.790,27,0.3523,18,"18,035.47",98,0.138,99,0.1364,58,9611.85,283,14.139,286,0.0000,250,5891.43,306,7.793,306,0.0114,235,21868.78,45,0.256,19,0.2955,13,16716.82,88,0.168,74,0.1477,52
3,E06000004,Stockton-on-Tees,17541.72,113,25.790,73,0.2083,39,0.3024,59,32301.09,24,18291.93,99,0.164,51,0.2167,33,31750,74,20104.05,67,0.135,45,0.2083,39,15089.25,64,"16,899.44",139,24.786,111,0.1667,61,23468.75,48,0.684,36,0.2833,28,"14,933.36",156,-0.111,154,0.1000,84,11053.82,264,15.870,264,0.0167,219,4538.17,312,6.007,311,0.0000,251,19164.60,93,0.209,60,0.1917,37,15589.56,112,0.160,84,0.1417,55
4,E06000005,Darlington,18284.63,103,25.657,77,0.1846,47,0.2891,66,32173.97,32,18361.47,94,0.153,69,0.1846,41,16208,133,20134.54,65,0.128,52,0.1846,52,7637.50,132,"18,401.65",114,27.402,76,0.2000,42,22510.99,61,0.532,57,0.2462,35,"22,802.29",30,0.558,26,0.2923,20,7041.46,306,11.942,306,0.0308,199,7148.04,300,8.800,301,0.0000,251,19072.53,96,0.203,69,0.2154,30,15702.96,110,0.152,92,0.0769,79

In [36]:
LA_Health_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/LAD Health.csv")
LA_Health_df.head()

,Lower tier local authorities Code,Lower tier local authorities,General health (6 categories) Code,General health (6 categories),Observation
0,E06000001,Hartlepool,-8,Does not apply,0.0
1,E06000001,Hartlepool,1,Very good health,42.8
2,E06000001,Hartlepool,2,Good health,33.7
3,E06000001,Hartlepool,3,Fair health,15.6
4,E06000001,Hartlepool,4,Bad health,6.0

In [37]:
LA_Health_df_P = pd.pivot_table(LA_Health_df, values='Observation', index=['Lower tier local authorities Code'], columns=['General health (6 categories)'], aggfunc=np.sum)
LA_Health_df_P = LA_Health_df_P.reset_index()
LA_Health_df_P.drop(['Does not apply'], 1, inplace=True)

LA_Health_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\3455528903.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  LA_Health_df_P.drop(['Does not apply'], 1, inplace=True)

General health (6 categories),Lower tier local authorities Code,Bad health,Fair health,Good health,Very bad health,Very good health
0,E06000001,6.0,15.6,33.7,1.9,42.8
1,E06000002,6.1,14.9,33.3,1.9,43.8
2,E06000003,5.4,14.9,34.0,1.7,44.1
3,E06000004,4.9,14.2,33.7,1.5,45.7
4,E06000005,4.5,14.0,34.8,1.2,45.5

### 2.1.16 Median House Price

In [38]:
Median_House_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Median House Price per ward.csv", encoding  = 'latin')
#Median_House_df.columns = Median_House_df.columns.str[-8:]
Median_House_df.rename(columns = {'Ward code':'WD21CD'}, inplace = True)
Median_House_df.drop(['Ward name', 'Local authority code', 'Local authority name'],1,inplace = True)
Median_House_df.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\912111187.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  Median_House_df.drop(['Ward name', 'Local authority code', 'Local authority name'],1,inplace = True)

,WD21CD,Overall 2013,Overall 2014,Overall 2015,Overall 2016,Overall 2017,Overall 2018,Overall 2019,Overall 2020,Overall 2021,Overall 2022,Overall 2023,Overall 10 year change,Overall 5 year change,Detached 2013,Detached 2014,Detached 2015,Detached 2016,Detached 2017,Detached 2018,Detached 2019,Detached 2020,Detached 2021,Detached 2022,Detached 2023,Detached 10 year change,Detached 5 year change,Semi Detached 2013,Semi Detached 2014,Semi Detached 2015,Semi Detached 2016,Semi Detached 2017,Semi Detached 2018,Semi Detached 2019,Semi Detached 2020,Semi Detached 2021,Semi Detached 2022,Semi Detached 2023,Semi Detached 10 year change,Semi Detached 5 year change,Terraced 2013,Terraced 2014,Terraced 2015,Terraced 2016,Terraced 2017,Terraced 2018,Terraced 2019,Terraced 2020,Terraced 2021,Terraced 2022,Terraced 2023,Terraced 10 year change,Terraced 5 year change,Flats 2013,Flats 2014,Flats 2015,Flats 2016,Flats 2017,Flats 2018,Flats 2019,Flats 2020,Flats 2021,Flats 2022,Flats 2023,Flats 10 year change,Flats 5 year change
0,E05008945,107500,92250,115000,110000,89000,110000,99000,110000,110000,110000,99000,-8,-10,170000,157975,174995,174475,155500,165000,0,180000,174250,205000,170000,0,3,110000,105500,121500,114998,115000,120000,119000,126000,119975,133250,124250,13,4,72500,58500,57000,73500,62000,61125,68750,74500,68000,74500,82000,13,34,0,47000,0,68000,0,67500,0,0,0,63950,78000,101,16
1,E05008946,154500,155500,158000,142498,149995,157000,150000,149000,163000,165000,190000,23,21,195999,194500,194975,195000,202500,196950,203725,184500,210000,229500,245000,25,24,136400,130000,133000,129950,132500,126000,130000,132000,137000,147000,151000,11,20,88000,89000,110000,112995,110000,115500,95000,112500,115000,105000,125250,42,8,74000,88000,84898,55700,108495,115000,92500,113750,80000,80750,85000,15,-26
2,E05008947,84000,89000,115000,69995,93000,86500,84000,90250,90000,105000,106500,27,23,0,0,0,114500,0,0,0,134000,235000,249000,0,101,101,0,0,147750,0,123950,88000,0,83500,88000,105000,107000,101,22,82285,91000,122000,87500,87500,87000,71000,90500,81250,100000,110000,34,26,78000,57000,61600,57773,87000,80000,89250,88000,86000,90000,95500,22,19
3,E05008943,85000,75000,82250,80000,115000,126500,131475,129950,139950,113000,118000,39,-7,0,0,0,179975,194950,182475,179950,195000,187475,210500,217500,101,19,91238,88500,110000,89000,124950,123000,127725,123975,120000,129000,128500,41,4,62900,62000,74500,68500,65000,62000,77500,71000,100000,83250,100000,59,61,0,0,0,0,0,0,0,0,0,0,0,101,101
4,E05008944,108000,120000,121500,120000,116250,128000,125250,132000,136375,146000,157250,46,23,155000,161000,192000,168000,184000,190000,165000,185000,180000,219950,209500,35,10,113000,121500,125000,124000,123500,130000,130000,132000,145000,149500,160875,42,24,77000,77750,80000,89500,81000,81500,85975,85000,91000,95000,121000,57,48,0,0,0,0,0,0,0,0,0,0,0,101,101

### 2.1.16A Number of houses sold

In [39]:
Num_House_df = pd.read_csv("N:/2092_Development_of_a_GIS_Based_Portrait/WORKING/GIS/01_Data/12_For Tableau/Final Set/HPSSA Dataset 36 - Number of residential property sales by ward.csv", encoding  = 'latin')
Num_House_df.rename(columns = {'Ward code':'WD21CD'}, inplace = True)
Num_House_df.drop(['Ward name', 'Local authority code', 'Local authority name'],1,inplace = True)
Num_House_df.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\1550405138.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  Num_House_df.drop(['Ward name', 'Local authority code', 'Local authority name'],1,inplace = True)

,WD21CD,Houses sold last year,Houses sold in the last 5 years,Houses sold in the last 10 years,Det_Houses sold last year,Det_Houses sold in the last 5 years,Det_Houses sold in the last 10 years,SDet_Houses sold last year,SDet_Houses sold in the last 5 years,SDet_Houses sold in the last 10 years,Ter_Houses sold last year,Ter_Houses sold in the last 5 years,Ter_Houses sold in the last 10 years,Flt_Houses sold last year,Flt_Houses sold in the last 5 years,Flt_Houses sold in the last 10 years,New_Houses sold last year,New_Houses sold in the last 5 years,New_Houses sold in the last 10 years,NDet_Houses sold last year,NDet_Houses sold in the last 5 years,NDet_Houses sold in the last 10 years,NSDet_Houses sold last year,NSDet_Houses sold in the last 5 years,NSDet_Houses sold in the last 10 years,NTer_Houses sold last year,NTer_Houses sold in the last 5 years,NTer_Houses sold in the last 10 years,NFlt_Houses sold last year,NFlt_Houses sold in the last 5 years,NFlt_Houses sold in the last 10 years,Ex_Houses sold last year,Ex_Houses sold in the last 5 years,Ex_Houses sold in the last 10 years,ExDet_Houses sold last year,ExDet_Houses sold in the last 5 years,ExDet_Houses sold in the last 10 years,ExSDet_Houses sold last year,ExSDet_Houses sold in the last 5 years,ExSDet_Houses sold in the last 10 years,ExTer_Houses sold last year,ExTer_Houses sold in the last 5 years,ExTer_Houses sold in the last 10 years,ExFlt_Houses sold last year,ExFlt_Houses sold in the last 5 years,ExFlt_Houses sold in the last 10 years
0,E05008945,528,2346,4483,48,200,565,211,1200,2196,231,837,1529,38,109,193,0,8,283,0,0,173,0,8,77,0,0,33,0,0,0,528,2338,4200,48,200,392,211,1192,2119,231,837,1496,38,109,193
1,E05008946,583,3438,7254,272,1777,3723,222,1164,2456,59,310,710,30,187,365,6,197,1729,0,75,852,0,39,617,0,0,109,6,83,151,577,3241,5525,272,1702,2871,222,1125,1839,59,310,601,24,104,214
2,E05008947,357,1667,2911,22,127,180,42,185,297,184,876,1523,109,479,911,24,101,378,11,36,36,5,12,44,0,0,60,8,53,238,333,1566,2533,11,91,144,37,173,253,184,876,1463,101,426,673
3,E05008943,351,1961,3223,72,609,817,135,766,1381,135,564,970,9,22,55,33,698,921,25,434,550,1,186,288,7,78,83,0,0,0,318,1263,2302,47,175,267,134,580,1093,128,486,887,9,22,55
4,E05008944,473,2602,4513,79,442,732,296,1617,2771,93,519,962,5,24,48,0,80,84,0,4,8,0,64,64,0,12,12,0,0,0,473,2522,4429,79,438,724,296,1553,2707,93,507,950,5,24,48

### 2.1.17 Housing Tenure

In [40]:
OA_housing_tenure_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Housing_Tenure_per_OA.csv")
OA_housing_tenure_df.head()

,Output Areas Code,Output Areas,Tenure of household (9 categories) Code,Tenure of household (9 categories),Observation
0,E00000001,E00000001,-8,Does not apply,0
1,E00000001,E00000001,0,Owned: Owns outright,59
2,E00000001,E00000001,1,Owned: Owns with a mortgage or loan,13
3,E00000001,E00000001,2,Shared ownership: Shared ownership,0
4,E00000001,E00000001,3,Social rented: Rents from council or Local Aut...,6

In [41]:
OA_housing_tenure_df_P = pd.pivot_table(OA_housing_tenure_df, values='Observation', index=['Output Areas Code'], columns=['Tenure of household (9 categories)'], aggfunc=np.sum)
OA_housing_tenure_df_P = OA_housing_tenure_df_P.reset_index()
OA_housing_tenure_df_P.drop(['Does not apply'], 1, inplace=True)
OA_housing_tenure_df_P['Owned_combined'] = OA_housing_tenure_df_P['Owned: Owns outright']+OA_housing_tenure_df_P['Owned: Owns with a mortgage or loan']
OA_housing_tenure_df_P['Private_Rented_combined'] = OA_housing_tenure_df_P['Private rented: Other private rented']+OA_housing_tenure_df_P['Private rented: Private landlord or letting agency']
OA_housing_tenure_df_P['Social_Rented_combined'] = OA_housing_tenure_df_P['Social rented: Other social rented']+OA_housing_tenure_df_P['Social rented: Rents from council or Local Authority']
OA_housing_tenure_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\2026331051.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_housing_tenure_df_P.drop(['Does not apply'], 1, inplace=True)

Tenure of household (9 categories),Output Areas Code,Lives rent free,Owned: Owns outright,Owned: Owns with a mortgage or loan,Private rented: Other private rented,Private rented: Private landlord or letting agency,Shared ownership: Shared ownership,Social rented: Other social rented,Social rented: Rents from council or Local Authority,Owned_combined,Private_Rented_combined,Social_Rented_combined
0,E00000001,0,59,13,2,13,0,1,6,72,15,7
1,E00000003,1,60,31,7,10,0,0,2,91,17,2
2,E00000005,0,29,11,4,17,0,1,1,40,21,2
3,E00000007,0,20,8,11,46,1,0,1,28,57,1
4,E00000010,0,13,12,3,28,0,7,63,25,31,70

### 2.1.17 Car Ownership

In [42]:
OA_car_ownership_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Car_ownership_per_OA.csv")
OA_car_ownership_df.head()

,Output Areas Code,Output Areas,Car or van availability (5 categories) Code,Car or van availability (5 categories),Observation
0,E00000001,E00000001,-8,Does not apply,0
1,E00000001,E00000001,0,No cars or vans in household,46
2,E00000001,E00000001,1,1 car or van in household,41
3,E00000001,E00000001,2,2 cars or vans in household,5
4,E00000001,E00000001,3,3 or more cars or vans in household,3

In [43]:
OA_car_ownership_df_P = pd.pivot_table(OA_car_ownership_df, values='Observation', index=['Output Areas Code'], columns=['Car or van availability (5 categories)'], aggfunc=np.sum)
OA_car_ownership_df_P = OA_car_ownership_df_P.reset_index()
OA_car_ownership_df_P.drop(['Does not apply'], 1, inplace=True)
OA_car_ownership_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\2032069190.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_car_ownership_df_P.drop(['Does not apply'], 1, inplace=True)

Car or van availability (5 categories),Output Areas Code,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household,No cars or vans in household
0,E00000001,41,5,3,46
1,E00000003,47,7,4,51
2,E00000005,18,2,4,37
3,E00000007,16,4,0,66
4,E00000010,17,0,0,109

### 2.1.17 Average Income

In [44]:
MSOA_avg_income_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Income_Estimate_per_MSOA.csv", encoding  = 'latin')
MSOA_avg_income_df.rename(columns = {'MSOA code':'msoa21cd'}, inplace = True)
MSOA_avg_income_df.drop(['Local authority code','Local authority name','Region code','Region name'],1,inplace = True)
MSOA_avg_income_df.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\1716494766.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  MSOA_avg_income_df.drop(['Local authority code','Local authority name','Region code','Region name'],1,inplace = True)

,msoa21cd,MSOA name,Total annual income (£),Net annual income (£),Net annual income before housing costs (£),Net annual income after housing costs (£)
0,E02004297,County Durham 001,41400,30500,28800,27700
1,E02004290,County Durham 002,41100,31200,30100,28600
2,E02004298,County Durham 003,44300,33800,31300,31400
3,E02004299,County Durham 004,35400,29500,27600,25000
4,E02004291,County Durham 005,34500,27200,26500,23800

### 2.1.18 Occupation

In [45]:
OA_occupation_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/OA Ocupation.csv")
OA_occupation_df['Occupation (current) (10 categories)'] = OA_occupation_df['Occupation (current) (10 categories)'].str.split('.').str[1]
OA_occupation_df.head()

,Output Areas Code,Output Areas,Occupation (current) (10 categories) Code,Occupation (current) (10 categories),Observation
0,E00000001,E00000001,-8,NaN,88
1,E00000001,E00000001,1,"Managers, directors and senior officials",24
2,E00000001,E00000001,2,Professional occupations,37
3,E00000001,E00000001,3,Associate professional and technical occupations,13
4,E00000001,E00000001,4,Administrative and secretarial occupations,6

In [46]:
OA_occupation_df_P = pd.pivot_table(OA_occupation_df, values='Observation', index=['Output Areas Code'], columns=['Occupation (current) (10 categories)'], aggfunc=np.sum)
OA_occupation_df_P = OA_occupation_df_P.reset_index()
OA_occupation_df_P.head()

Occupation (current) (10 categories),Output Areas Code,Administrative and secretarial occupations,Associate professional and technical occupations,"Caring, leisure and other service occupations",Elementary occupations,"Managers, directors and senior officials","Process, plant and machine operatives",Professional occupations,Sales and customer service occupations,Skilled trades occupations
0,E00000001,6,13,4,0,24,1,37,1,1
1,E00000003,6,32,4,0,36,3,54,2,0
2,E00000005,6,15,1,0,16,0,25,2,1
3,E00000007,1,29,4,1,29,2,36,1,3
4,E00000010,8,28,9,11,23,0,28,0,7

### 2.1.19 MSOA Industry

In [47]:
MSOA_industry_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/OA Industry.csv")
MSOA_industry_df['Industry (current) (88 categories)'] = MSOA_industry_df['Industry (current) (88 categories)'].str[3:]
MSOA_industry_df = MSOA_industry_df.drop(MSOA_industry_df[MSOA_industry_df['Industry (current) (88 categories)'] == 's not apply'].index)
MSOA_industry_df.head()

,Middle layer Super Output Areas Code,Middle layer Super Output Areas,Industry (current) (88 categories) Code,Industry (current) (88 categories),Observation
1,E02000001,City of London 001,1,"Crop and animal production, hunting and relate...",0
2,E02000001,City of London 001,2,Forestry and logging,0
3,E02000001,City of London 001,3,Fishing and aquaculture,0
4,E02000001,City of London 001,4,Mining of coal and lignite,0
5,E02000001,City of London 001,5,Extraction of crude petroleum and natural gas,1

In [48]:
# Step 1: Create a new column called 'Industry_Type'
MSOA_industry_df['Industry_Type'] = ''

# Step 2: Import an Excel tab called 'Industry'
excel_file = "C:/Users/abhimanya.achara/Downloads/SW Herts - Categories to Group_KI Update.xlsx"  # Replace with your Excel file path
excel_tab_name = 'Industry'

# Load the Excel tab into a DataFrame
industry_df = pd.read_excel(excel_file, sheet_name=excel_tab_name)

# Step 3: Update 'Industry_Type' based on matching values
for index, row in MSOA_industry_df.iterrows():
    industry = row['Industry (current) (88 categories)']
    matching_row = industry_df[industry_df['Column Names'] == industry]
    
    if not matching_row.empty:
        industry_type = matching_row.iloc[0]['Broad Industries']
        MSOA_industry_df.at[index, 'Industry_Type'] = industry_type
        
MSOA_industry_df.head()

,Middle layer Super Output Areas Code,Middle layer Super Output Areas,Industry (current) (88 categories) Code,Industry (current) (88 categories),Observation,Industry_Type
1,E02000001,City of London 001,1,"Crop and animal production, hunting and relate...",0,"Agriculture, Forestry and Fishing"
2,E02000001,City of London 001,2,Forestry and logging,0,"Agriculture, Forestry and Fishing"
3,E02000001,City of London 001,3,Fishing and aquaculture,0,"Agriculture, Forestry and Fishing"
4,E02000001,City of London 001,4,Mining of coal and lignite,0,Mining and Quarrying
5,E02000001,City of London 001,5,Extraction of crude petroleum and natural gas,1,Mining and Quarrying

In [99]:
MSOA_industry_df_P = pd.pivot_table(MSOA_industry_df, values='Observation', index=['Middle layer Super Output Areas Code'], columns=['Industry_Type'], aggfunc=np.sum)
MSOA_industry_df_P = MSOA_industry_df_P.reset_index()
MSOA_industry_df_P['Industry_pop'] = MSOA_industry_df_P.sum(axis=1,numeric_only=True)
#MSOA_industry_df_P.drop(['s not apply'], 1, inplace=True)
MSOA_industry_df_P.rename(columns = {'Middle layer Super Output Areas Code':'msoa21cd'}, inplace = True)
MSOA_industry_df_P.head()

Industry_Type,msoa21cd,,Advertising,"Agriculture, Forestry and Fishing",Architecture and Engineering,"Arts, Entertainment and Recreation",Broadcasting,Education,"Electricity, gas, steam and air conditioning supply",Employment Agencies,Film and TV,Finance and Insurance,Health and Social Care Services,Hospitality and Food Services,Information Technologies,International Organisations,Leasing,Legal and Accounting,Maintenance Services,Management and Management Consulting,Manufacturing,Mining and Quarrying,Office Administration Services,Other,Personal Service Provision,Printing,"Professional, Scientific and Technical Services",Public Administration,Publishing,Real Estate,Repair of Electronics and Goods,Scientific Research and Development,Security Services,Telecommunications,Transportation and Storage,Travel Services,Veterinary Services,"Water Supply, Sewerage and Waste Management",Web Search and Data Processing,Wholesale and Retail Trade,Industry_pop
0,E02000001,118,135,0,219,303,32,375,2,37,68,1063,340,178,381,10,3,545,67,192,93,1,38,88,31,14,108,220,44,88,1,65,23,27,68,26,1,2,37,309,5352
1,E02000002,503,19,1,19,39,5,289,8,26,13,98,586,193,68,0,8,86,107,16,86,1,20,11,25,3,9,164,3,51,2,3,50,15,213,5,4,19,2,467,3237
2,E02000003,740,35,2,40,83,6,468,9,43,10,200,749,269,170,2,9,156,184,26,127,1,31,42,91,10,23,293,9,102,1,4,99,33,402,12,5,35,3,717,5241
3,E02000004,444,27,0,16,44,5,289,7,24,3,122,517,121,75,1,13,83,99,19,107,0,25,22,32,12,14,190,3,50,2,7,27,32,239,6,3,32,4,397,3113
4,E02000005,633,28,0,42,77,1,415,16,42,5,171,817,263,162,0,23,98,166,26,143,1,34,25,54,14,20,249,3,77,7,11,77,38,359,7,0,29,4,730,4867

# LAD Industry

In [50]:
LAD_industry_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/LAD_Industry.csv")
LAD_industry_df['Industry (current) (88 categories)'] = LAD_industry_df['Industry (current) (88 categories)'].str[3:]
LAD_industry_df = LAD_industry_df.drop(LAD_industry_df[LAD_industry_df['Industry (current) (88 categories)'] == 's not apply'].index)
LAD_industry_df.head()

,Lower tier local authorities Code,Lower tier local authorities,Industry (current) (88 categories) Code,Industry (current) (88 categories),Observation
1,E06000001,Hartlepool,1,"Crop and animal production, hunting and relate...",117
2,E06000001,Hartlepool,2,Forestry and logging,0
3,E06000001,Hartlepool,3,Fishing and aquaculture,32
4,E06000001,Hartlepool,4,Mining of coal and lignite,5
5,E06000001,Hartlepool,5,Extraction of crude petroleum and natural gas,401

In [51]:
# Step 1: Create a new column called 'Industry_Type'
LAD_industry_df['Industry_Type'] = ''

# Step 2: Import an Excel tab called 'Industry'
excel_file = "C:/Users/abhimanya.achara/Downloads/SW Herts - Categories to Group_KI Update.xlsx"  # Replace with your Excel file path
excel_tab_name = 'Industry'

# Load the Excel tab into a DataFrame
industry_df = pd.read_excel(excel_file, sheet_name=excel_tab_name)

# Step 3: Update 'Industry_Type' based on matching values
for index, row in LAD_industry_df.iterrows():
    industry = row['Industry (current) (88 categories)']
    matching_row = industry_df[industry_df['Column Names'] == industry]
    
    if not matching_row.empty:
        industry_type = matching_row.iloc[0]['Broad Industries']
        LAD_industry_df.at[index, 'Industry_Type'] = industry_type
        
LAD_industry_df.head()

,Lower tier local authorities Code,Lower tier local authorities,Industry (current) (88 categories) Code,Industry (current) (88 categories),Observation,Industry_Type
1,E06000001,Hartlepool,1,"Crop and animal production, hunting and relate...",117,"Agriculture, Forestry and Fishing"
2,E06000001,Hartlepool,2,Forestry and logging,0,"Agriculture, Forestry and Fishing"
3,E06000001,Hartlepool,3,Fishing and aquaculture,32,"Agriculture, Forestry and Fishing"
4,E06000001,Hartlepool,4,Mining of coal and lignite,5,Mining and Quarrying
5,E06000001,Hartlepool,5,Extraction of crude petroleum and natural gas,401,Mining and Quarrying

In [52]:
LAD_industry_df_P = pd.pivot_table(LAD_industry_df, values='Observation', index=['Lower tier local authorities Code'], columns=['Industry_Type'], aggfunc=np.sum)
LAD_industry_df_P = LAD_industry_df_P.reset_index()
LAD_industry_df_P['Industry_pop'] = LAD_industry_df_P.sum(axis=1,numeric_only=True)
#LAD_industry_df_P.drop(['s not apply'], 1, inplace=True)
LAD_industry_df_P.rename(columns = {'Lower tier local authorities Code':'lad22cd'}, inplace = True)
LAD_industry_df_P.head()

Industry_Type,lad22cd,,Advertising,"Agriculture, Forestry and Fishing",Architecture and Engineering,"Arts, Entertainment and Recreation",Broadcasting,Education,"Electricity, gas, steam and air conditioning supply",Employment Agencies,Film and TV,Finance and Insurance,Health and Social Care Services,Hospitality and Food Services,Information Technologies,International Organisations,Leasing,Legal and Accounting,Maintenance Services,Management and Management Consulting,Manufacturing,Mining and Quarrying,Office Administration Services,Other,Personal Service Provision,Printing,"Professional, Scientific and Technical Services",Public Administration,Publishing,Real Estate,Repair of Electronics and Goods,Scientific Research and Development,Security Services,Telecommunications,Transportation and Storage,Travel Services,Veterinary Services,"Water Supply, Sewerage and Waste Management",Web Search and Data Processing,Wholesale and Retail Trade,Industry_pop
0,E06000001,3809,106,149,694,590,23,3763,584,157,46,628,6354,1845,468,1,123,481,779,182,3810,428,268,153,575,64,114,2632,29,544,22,65,260,247,1452,58,47,444,21,5734,37749
1,E06000002,4797,157,82,831,786,26,5282,439,240,74,1203,11756,3034,781,1,194,558,1257,168,3902,604,495,247,897,87,142,3610,32,762,48,152,451,581,3102,98,75,397,35,9048,56431
2,E06000003,5387,185,283,1075,996,14,5188,537,177,54,854,10322,2815,614,2,175,646,1364,181,4532,1052,312,188,1045,78,161,3698,36,919,51,181,400,358,2676,119,128,467,33,8317,55620
3,E06000004,7319,327,259,1969,1446,50,8847,850,364,102,2231,14889,3879,1443,2,366,1131,1709,374,6771,938,531,308,1429,143,315,6455,50,1223,44,346,638,958,4233,206,167,586,46,13503,86447
4,E06000005,3760,147,311,688,803,27,4293,184,240,50,1455,7872,2295,680,2,307,648,1066,300,4154,135,402,202,773,85,144,4199,56,522,56,130,256,1199,2869,80,101,295,41,8468,49295

### 2.1.20 OA Heating

In [53]:
OA_heating_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/OA heating.csv")
OA_heating_df.head()

,Output Areas Code,Output Areas,Type of central heating in household (13 categories) Code,Type of central heating in household (13 categories),Observation
0,E00000001,E00000001,-9,Does not apply,0
1,E00000001,E00000001,1,No central heating,3
2,E00000001,E00000001,2,Mains gas only,5
3,E00000001,E00000001,3,Tank or bottled gas only,1
4,E00000001,E00000001,4,Electric only,43

In [54]:
OA_heating_df_P = pd.pivot_table(OA_heating_df, values='Observation', index=['Output Areas Code'], columns=['Type of central heating in household (13 categories)'], aggfunc=np.sum)
OA_heating_df_P = OA_heating_df_P.reset_index()
OA_heating_df_P.drop(['Does not apply'], 1, inplace=True)
OA_heating_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\4164328289.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_heating_df_P.drop(['Does not apply'], 1, inplace=True)

Type of central heating in household (13 categories),Output Areas Code,District or communal heat networks only,Electric only,Mains gas only,No central heating,Oil only,Other central heating only,Renewable energy only,Solid fuel only,Tank or bottled gas only,Two or more types of central heating (including renewable energy),Two or more types of central heating (not including renewable energy),Wood only
0,E00000001,29,43,5,3,0,3,0,0,1,0,11,0
1,E00000003,39,42,10,3,0,4,0,0,0,0,11,0
2,E00000005,22,15,17,1,0,0,1,0,0,0,6,0
3,E00000007,5,31,37,1,0,1,0,0,2,1,6,0
4,E00000010,7,19,68,16,0,2,0,0,2,0,13,0

### 2.1.20 OA Occupancy

In [55]:
OA_occupancy_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/OA Occupancy rating.csv")
OA_occupancy_df.head()

,Output Areas Code,Output Areas,Occupancy rating for rooms (6 categories) Code,Occupancy rating for rooms (6 categories),Observation
0,E00000001,E00000001,-8,Does not apply,0
1,E00000001,E00000001,1,Occupancy rating of rooms: +2 or more,78
2,E00000001,E00000001,2,Occupancy rating of rooms: +1,13
3,E00000001,E00000001,3,Occupancy rating of rooms: 0,2
4,E00000001,E00000001,4,Occupancy rating of rooms: -1,1

In [56]:
OA_occupancy_df_P = pd.pivot_table(OA_occupancy_df, values='Observation', index=['Output Areas Code'], columns=['Occupancy rating for rooms (6 categories)'], aggfunc=np.sum)
OA_occupancy_df_P = OA_occupancy_df_P.reset_index()
OA_occupancy_df_P.drop(['Does not apply'], 1, inplace=True)

OA_occupancy_df_P.rename(columns = {'Occupancy rating of rooms: +1':'Underoccupied','Occupancy rating of rooms: +2 or more':'Significantly Underoccupied','Occupancy rating of rooms: -1':'Overoccupied','Occupancy rating of rooms: -2 or less':'Significantly Overoccupied','Occupancy rating of rooms: 0':'Ideal Occupation'}, inplace = True)
OA_occupancy_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\275525937.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_occupancy_df_P.drop(['Does not apply'], 1, inplace=True)

Occupancy rating for rooms (6 categories),Output Areas Code,Underoccupied,Significantly Underoccupied,Overoccupied,Significantly Overoccupied,Ideal Occupation
0,E00000001,13,78,1,0,2
1,E00000003,11,89,2,0,7
2,E00000005,33,13,2,0,13
3,E00000007,34,7,4,0,41
4,E00000010,4,2,24,3,91

### 2.1.21 House Type

In [57]:
OA_housing_type_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/OA House type.csv")
OA_housing_type_df.head()

,Output Areas Code,Output Areas,Accommodation type (8 categories) Code,Accommodation type (8 categories),Observation
0,E00000001,E00000001,1,Detached,0
1,E00000001,E00000001,2,Semi-detached,0
2,E00000001,E00000001,3,Terraced,1
3,E00000001,E00000001,4,In a purpose-built block of flats or tenement,93
4,E00000001,E00000001,5,"Part of a converted or shared house, including...",0

In [58]:
OA_housing_type_df_P = pd.pivot_table(OA_housing_type_df, values='Observation', index=['Output Areas Code'], columns=['Accommodation type (8 categories)'], aggfunc=np.sum)
OA_housing_type_df_P = OA_housing_type_df_P.reset_index()
OA_housing_type_df_P.head()

Accommodation type (8 categories),Output Areas Code,A caravan or other mobile or temporary structure,Detached,"In a commercial building, for example, in an office building, hotel or over a shop",In a purpose-built block of flats or tenement,"Part of a converted or shared house, including bedsits","Part of another converted building, for example, former school, church or warehouse",Semi-detached,Terraced
0,E00000001,0,0,0,93,0,0,0,1
1,E00000003,0,0,0,97,0,0,1,11
2,E00000005,0,0,0,62,0,0,0,1
3,E00000007,0,0,3,76,0,5,2,0
4,E00000010,0,0,4,121,0,0,0,0

### 2.1.21 Education Level

In [59]:
OA_education_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Education_per_OA.csv")
OA_education_df.head()

,Output Areas Code,Output Areas,Highest level of qualification (8 categories) Code,Highest level of qualification (8 categories),Observation
0,E00000001,E00000001,-8,Does not apply,15
1,E00000001,E00000001,0,No qualifications,4
2,E00000001,E00000001,1,Level 1 and entry level qualifications: 1 to 4...,7
3,E00000001,E00000001,2,Level 2 qualifications: 5 or more GCSEs (A* to...,10
4,E00000001,E00000001,3,Apprenticeship,1

In [60]:
OA_education_df_P = pd.pivot_table(OA_education_df, values='Observation', index=['Output Areas Code'], columns=['Highest level of qualification (8 categories)'], aggfunc=np.sum)
OA_education_df_P = OA_education_df_P.reset_index()
OA_education_df_P.drop(['Does not apply'], 1, inplace=True)
OA_education_df_P.rename(columns = {'Level 1 and entry level qualifications: 1 to 4 GCSEs grade A* to C, Any GCSEs at other grades, O levels or CSEs (any grades), 1 AS level, NVQ level 1, Foundation GNVQ, Basic or Essential Skills':'NVQ_level_1','Level 2 qualifications: 5 or more GCSEs (A* to C or 9 to 4), O levels (passes), CSEs (grade 1), School Certification, 1 A level, 2 to 3 AS levels, VCEs, Intermediate or Higher Diploma, Welsh Baccalaureate Intermediate Diploma, NVQ level 2, Intermediate GNVQ, City and Guilds Craft, BTEC First or General Diploma, RSA Diploma':'NVQ_level_2','Level 3 qualifications: 2 or more A levels or VCEs, 4 or more AS levels, Higher School Certificate, Progression or Advanced Diploma, Welsh Baccalaureate Advance Diploma, NVQ level 3; Advanced GNVQ, City and Guilds Advanced Craft, ONC, OND, BTEC National, RSA Advanced Diploma':'NVQ_level_3','Level 4 qualifications or above: degree (BA, BSc), higher degree (MA, PhD, PGCE), NVQ level 4 to 5, HNC, HND, RSA Higher Diploma, BTEC Higher level, professional qualifications (for example, teaching, nursing, accountancy)':'NVQ_level_4_to_5','Other: vocational or work-related qualifications, other qualifications achieved in England or Wales, qualifications achieved outside England or Wales (equivalent not stated or unknown)':'Vocational_and_Other_Education'}, inplace = True)
OA_education_df_P.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\2114458859.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  OA_education_df_P.drop(['Does not apply'], 1, inplace=True)

Highest level of qualification (8 categories),Output Areas Code,Apprenticeship,NVQ_level_1,NVQ_level_2,NVQ_level_3,NVQ_level_4_to_5,No qualifications,Vocational_and_Other_Education
0,E00000001,1,7,10,11,122,4,5
1,E00000003,1,3,8,20,184,5,0
2,E00000005,3,2,3,7,88,3,0
3,E00000007,1,2,5,7,117,5,2
4,E00000010,0,15,18,23,93,15,8

## 2.2 Join OA Census Data

In [72]:
merge2 = pd.merge(OA_sex_df_P, OA_hhold_df_P, how = 'left', on = 'Output Areas Code' )
merge3 = pd.merge(merge2, OA_hhold_size_df_P, how = 'left', on = 'Output Areas Code' )
merge4 = pd.merge(merge3, OA_hhold_comp_df_P, how = 'left', on = 'Output Areas Code' )
merge5 = pd.merge(merge4, OA_passports_df_P, how = 'left', on = 'Output Areas Code' )
merge6 = pd.merge(merge5, OA_ethincity_df_P, how = 'left', on = 'Output Areas Code' )
merge7 = pd.merge(merge6, OA_relegion_df_P, how = 'left', on = 'Output Areas Code' )
merge8 = pd.merge(merge7, OA_students_df_P, how = 'left', on = 'Output Areas Code' )
merge9 = pd.merge(merge8, OA_education_df_P, how = 'left', on = 'Output Areas Code' )
merge10 = pd.merge(merge9, OA_economic_df_P, how = 'left', on = 'Output Areas Code' )
merge11 = pd.merge(merge10, OA_occupation_df_P, how = 'left', on = 'Output Areas Code' )
merge12 = pd.merge(merge11, OA_nssec_df_P, how = 'left', on = 'Output Areas Code' )
merge13 = pd.merge(merge12, OA_housing_type_df_P, how = 'left', on = 'Output Areas Code' )
merge14 = pd.merge(merge13, OA_housing_tenure_df_P, how = 'left', on = 'Output Areas Code' )
merge15 = pd.merge(merge14, OA_occupancy_df_P, how = 'left', on = 'Output Areas Code' )
merge16 = pd.merge(merge15, OA_heating_df_P, how = 'left', on = 'Output Areas Code' )
merge17 = pd.merge(merge16, OA_car_ownership_df_P, how = 'left', on = 'Output Areas Code' )
merge18 = pd.merge(merge17, OA_TTW_df_P, how = 'left', on = 'Output Areas Code' )
OA_Census2021_df = pd.merge(merge18, OA_Dist_TTW_df_P, how = 'left', on = 'Output Areas Code' )

#renaming
OA_Census2021_df.rename(columns = {'Output Areas Code':'oa21cd', 
                              }, inplace = True)

OA_Census2021_df.head()

,oa21cd,female_population,male_population,total_population,total_households,0 people in household,1 person in household,2 people in household,3 people in household,4 people in household,5 people in household,6 people in household,7 people in household,8 or more people in household,One person household: Aged 66 years and over,One person household: Other,"Other household types: Other, including all full-time students and all aged 66 years and over",Other household types: With dependent children,Single family household: All aged 66 years and over,Single family household: Cohabiting couple family: All children non-dependent,Single family household: Cohabiting couple family: No children,Single family household: Cohabiting couple family: With dependent children,Single family household: Lone parent family: All children non-dependent,Single family household: Lone parent family: With dependent children,Single family household: Married or civil partnership couple: All children non-dependent,Single family household: Married or civil partnership couple: Dependent children,Single family household: Married or civil partnership couple: No children,Single family household: Other single family household: Other family composition,african,british_overseas_territories,antarctica_and_oceania_including_australasia,europe,other_europe,ireland,united_kingdom,america_caribbean,asia_middle_east,no_passport,"Asian, Asian British or Asian Welsh: Bangladeshi","Asian, Asian British or Asian Welsh: Chinese","Asian, Asian British or Asian Welsh: Indian","Asian, Asian British or Asian Welsh: Other Asian","Asian, Asian British or Asian Welsh: Pakistani","Black, Black British, Black Welsh, Caribbean or African: African","Black, Black British, Black Welsh, Caribbean or African: Caribbean","Black, Black British, Black Welsh, Caribbean or African: Other Black",Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups,Mixed or Multiple ethnic groups: White and Asian,Mixed or Multiple ethnic groups: White and Black African,Mixed or Multiple ethnic groups: White and Black Caribbean,Other ethnic group: Any other ethnic group,Other ethnic group: Arab,"White: English, Welsh, Scottish, Northern Irish or British",White: Gypsy or Irish Traveller,White: Irish,White: Other White,White: Roma,all_asian_ethnic_groups,all_black_ethnic_groups,all_mixed_or_multiple_ethnic_groups,other_ethnic_group,all_white_ethnic_groups,Buddhist,Christian,Hindu,Jewish,Muslim,No religion,Not answered,Other religion,Sikh,Not a student,Student,Apprenticeship,NVQ_level_1,NVQ_level_2,NVQ_level_3,NVQ_level_4_to_5,No qualifications,Vocational_and_Other_Education,Economically Inactive: Looking after home or family,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time,Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically active and a full-time student: In employment: Employee: Full-time,Economically active and a full-time student: In employment: Employee: Part-time,Economically active and a full-time student: In employment: Self-employed with employees: Full-time,Economically active and a full-time student: In employment: Self-employed with employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Student,Economically_Active,Economically_Active_Employeed,Economically_Active_Self_Employed,Economically_Active_Student,Economically_Inactive,Administrative and secretarial occupations,Associate professional and technical occupations,"Caring, leisure and other service occupations",Elementary occupations,"Managers, directors and senior officials","Process, plant and machine operatives",Professional occupations,Sales and customer service occupations,Skilled trades occupations,"L1, L2 and L3: Higher managerial, administrative and professional occupations",L10 and L11: Lower supervisory and technical occupations,L12: Semi-routine occupations,L13: Routine occupations,L14.1 and L14.2: Never worked and long-term unemployed,L15: Full-time students,"L4, L5 and L6: Lower managerial, administrative and professional occupations",L7: Intermediate occupations,L8 and L9: Small employers and own account workers,A caravan or other mobile or temporary structure,Detached,"In a commercial building, for example, in an office building, hotel or over a shop",In a purpose-built block of flats or tenement,"Part of a converted or shared house, including bedsits","Part of another converted building, for example, former school, church or warehouse",Semi-detached,Terraced,Lives rent free,Owned: Owns outright,Owned: Owns with a mortgage or loan,Private rented: Other private rented,Private rented: Private landlord or letting agency,Shared ownership: Shared ownership,Social rented: Other social rented,Social rented: Rents from council or Local Authority,Owned_combined,Private_Rented_combined,Social_Rented_combined,Underoccupied,Significantly Underoccupied,Overoccupied,Significantly Overoccupied,Ideal Occupation,District or communal heat networks only,Electric only,Mains gas only,No central heating,Oil only,Other central heating only,Renewable energy only,Solid fuel only,Tank or bottled gas only,Two or more types of central heating (including renewable energy),Two or more types of central heating (not including renewable energy),Wood only,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household,No cars or vans in household,Bicycle,"Bus, minibus or coach",Driving a car or van,"Motorcycle, scooter or moped",On foot,Other method of travel to work,Passenger in a car or van,Taxi,Train,"Underground, metro, light rail, tram",Work mainly at or from home,10km to less than 20km,20km to less than 30km,2km to less than 5km,30km to less than 40km,40km to less than 60km,5km to less than 10km,60km and over,Less than 2km,"Works mainly at an offshore installation, in no fixed place, or outside the UK",Works mainly from home
0,E00000001,75,101,176,94,0,34,44,10,6,0,0,0,0,16,18,3,0,16,0,2,3,2,3,1,7,23,0,0,0,0,25,2,1,141,1,0,3,0,4,0,0,1,0,3,0,1,5,0,0,7,0,112,0,0,39,4,5,3,6,7,155,0,74,0,0,3,91,7,0,0,158,18,1,7,10,11,122,4,5,2,44,17,7,1,9,10,10,0,0,0,0,0,0,0,1,3,52,5,98,61,27,0,63,6,13,4,0,24,1,37,1,1,80,3,5,5,4,2,38,13,9,0,0,0,93,0,0,0,1,0,59,13,2,13,0,1,6,72,15,7,13,78,1,0,2,29,43,5,3,0,3,0,0,1,0,11,0,41,5,3,46,6,1,1,0,14,0,0,0,1,6,59,2,0,7,0,1,5,1,8,5,59
1,E00000003,123,135,258,109,0,27,42,19,17,4,0,0,0,11,16,10,0,20,0,5,1,0,3,9,19,15,0,0,0,4,12,0,1,226,0,1,4,0,6,11,7,0,5,0,0,7,6,0,0,3,1,174,0,0,35,0,24,5,13,4,209,1,79,10,3,6,122,32,3,0,201,44,1,3,8,20,184,5,0,6,73,17,9,1,16,18,5,0,1,0,0,0,0,0,0,1,57,19,139,91,44,1,83,6,32,4,0,36,3,54,2,0,96,2,5,2,5,20,58,8,26,0,0,0,97,0,0,1,11,1,60,31,7,10,0,0,2,91,17,2,11,89,2,0,7,39,42,10,3,0,4,0,0,0,0,11,0,47,7,4,51,2,0,7,0,7,1,0,0,1,10,105,2,1,7,0,0,11,0,5,3,105
2,E00000005,52,60,112,63,0,26,27,8,2,0,0,0,0,9,17,2,0,7,0,5,4,3,1,2,2,11,0,0,0,0,11,1,0,89,0,2,3,0,4,4,5,0,0,0,0,2,2,2,0,7,1,65,0,0,20,0,13,0,6,8,85,0,40,2,3,1,50,14,2,0,102,5,3,2,3,7,88,3,0,3,38,7,6,0,10,4,3,0,1,0,0,0,0,0,1,6,23,3,68,46,20,1,36,6,15,1,0,16,0,25,2,1,37,0,3,1,1,4,28,8,21,0,0,0,62,0,0,0,1,0,29,11,4,17,0,1,1,40,21,2,33,13,2,0,13,22,15,17,1,0,0,1,0,0,0,6,0,18,2,4,37,2,2,3,1,13,0,0,1,3,4,37,1,0,8,0,0,3,0,11,6,37
3,E00000007,67,77,144,86,0,38,44,2,2,1,0,0,0,3,34,6,0,3,0,22,0,0,0,0,3,7,8,0,0,14,31,3,7,78,0,2,2,0,16,1,7,0,2,0,0,1,2,1,0,3,5,62,0,4,40,0,24,2,4,8,106,4,61,0,1,4,65,10,0,0,131,16,1,2,5,7,117,5,2,1,87,7,1,0,6,8,1,0,0,0,0,0,0,0,1,2,17,11,110,94,15,0,32,1,29,4,1,29,2,36,1,3,62,3,3,1,6,10,39,5,11,0,0,3,76,0,5,2,0,0,20,8,11,46,1,0,1,28,57,1,34,7,4,0,41,5,31,37,1,0,1,0,0,2,1,6,0,16,4,0,66,1,4,5,0,15,0,0,1,2,0,78,2,0,5,0,0,4,2,13,2,78
4,E00000010,71,107,178,126,0,96,19,4,3,3,0,0,0,17,79,6,0,0,3,10,3,0,0,0,2,5,3,1,0,1,39,3,1,119,1,1,9,1,3,3,3,0,5,5,2,11,7,3,1,10,1,83,0,0,37,0,10,12,22,11,120,0,62,0,3,4,84,25,0,0,165,11,0,15,18,23,93,15,8,0,66,11,3,0,15,15,18,0,0,0,0,1,0,0,9,9,15,8,128,77,33,1,41,8,28,9,11,23,0,28,0,7,34,7,10,14,11,5,45,17,27,0,0,4,121,0,0,0,0,0,13,12,3,28,0,7,63,25,31,70,4,2,24,3,91,7,19,68,16,0,2,0,0,2,0,13,0,17,0,0,109,10,5,4,0,20,3,0,0,5,13,55,4,0,9,0,0,4,1,29,11,55

## 2.3 Lookup - OA to LSOA, MSOA, LA

In [73]:
OALookupdf = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/OA21_LSOA21_MSOA21_LAD22_EW_LU.csv")
OALookupdf.head()

,oa21cd,lsoa21cd,lsoa21nm,msoa21cd,msoa21nm,lad22cd,lad22nm
0,E00000001,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London
1,E00000003,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London
2,E00000005,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London
3,E00000007,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London
4,E00000010,E01000003,City of London 001C,E02000001,City of London 001,E09000001,City of London

## 2.4 Lookup - OA to Ward

In [74]:
WardLookupdf = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/OA11_WD21_LAD21_EW_LU.csv", encoding = 'latin')
WardLookupdf.rename(columns = {'OA11CD':'oa21cd'}, inplace = True)
WardLookupdf.drop(['LAD21CD','LAD21NM'],1,inplace = True)
WardLookupdf.head()

C:\Users\abhimanya.achara\AppData\Local\Temp\ipykernel_32968\4026394549.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  WardLookupdf.drop(['LAD21CD','LAD21NM'],1,inplace = True)

      oa21cd     WD21CD       WD21NM
0  E00060526  E05013038  Burn Valley
1  E00060525  E05013038  Burn Valley
2  E00060529  E05013038  Burn Valley
3  E00060337  E05013038  Burn Valley
4  E00060338  E05013038  Burn Valley

## 2.5 Lookup - OA to Region

In [75]:
RegionLookupdf = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/OA21_RGN22_LU.csv")
RegionLookupdf.head()

      oa21cd    rgn22cd rgn22nm
0  E00000001  E12000007  London
1  E00000003  E12000007  London
2  E00000005  E12000007  London
3  E00000007  E12000007  London
4  E00000010  E12000007  London

# 3. Merge & Group data

In [76]:
OA_Census2021_df = pd.merge(OA_Census2021_df, OALookupdf, how = 'left', on = 'oa21cd' )
OA_Census2021_df = pd.merge(OA_Census2021_df, WardLookupdf, how = 'left', on = 'oa21cd' )
OA_Census2021_df = pd.merge(OA_Census2021_df, RegionLookupdf, how = 'left', on = 'oa21cd' )
OA_Census2021_df.head()

,oa21cd,female_population,male_population,total_population,total_households,0 people in household,1 person in household,2 people in household,3 people in household,4 people in household,5 people in household,6 people in household,7 people in household,8 or more people in household,One person household: Aged 66 years and over,One person household: Other,"Other household types: Other, including all full-time students and all aged 66 years and over",Other household types: With dependent children,Single family household: All aged 66 years and over,Single family household: Cohabiting couple family: All children non-dependent,Single family household: Cohabiting couple family: No children,Single family household: Cohabiting couple family: With dependent children,Single family household: Lone parent family: All children non-dependent,Single family household: Lone parent family: With dependent children,Single family household: Married or civil partnership couple: All children non-dependent,Single family household: Married or civil partnership couple: Dependent children,Single family household: Married or civil partnership couple: No children,Single family household: Other single family household: Other family composition,african,british_overseas_territories,antarctica_and_oceania_including_australasia,europe,other_europe,ireland,united_kingdom,america_caribbean,asia_middle_east,no_passport,"Asian, Asian British or Asian Welsh: Bangladeshi","Asian, Asian British or Asian Welsh: Chinese","Asian, Asian British or Asian Welsh: Indian","Asian, Asian British or Asian Welsh: Other Asian","Asian, Asian British or Asian Welsh: Pakistani","Black, Black British, Black Welsh, Caribbean or African: African","Black, Black British, Black Welsh, Caribbean or African: Caribbean","Black, Black British, Black Welsh, Caribbean or African: Other Black",Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups,Mixed or Multiple ethnic groups: White and Asian,Mixed or Multiple ethnic groups: White and Black African,Mixed or Multiple ethnic groups: White and Black Caribbean,Other ethnic group: Any other ethnic group,Other ethnic group: Arab,"White: English, Welsh, Scottish, Northern Irish or British",White: Gypsy or Irish Traveller,White: Irish,White: Other White,White: Roma,all_asian_ethnic_groups,all_black_ethnic_groups,all_mixed_or_multiple_ethnic_groups,other_ethnic_group,all_white_ethnic_groups,Buddhist,Christian,Hindu,Jewish,Muslim,No religion,Not answered,Other religion,Sikh,Not a student,Student,Apprenticeship,NVQ_level_1,NVQ_level_2,NVQ_level_3,NVQ_level_4_to_5,No qualifications,Vocational_and_Other_Education,Economically Inactive: Looking after home or family,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time,Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically active and a full-time student: In employment: Employee: Full-time,Economically active and a full-time student: In employment: Employee: Part-time,Economically active and a full-time student: In employment: Self-employed with employees: Full-time,Economically active and a full-time student: In employment: Self-employed with employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Student,Economically_Active,Economically_Active_Employeed,Economically_Active_Self_Employed,Economically_Active_Student,Economically_Inactive,Administrative and secretarial occupations,Associate professional and technical occupations,"Caring, leisure and other service occupations",Elementary occupations,"Managers, directors and senior officials","Process, plant and machine operatives",Professional occupations,Sales and customer service occupations,Skilled trades occupations,"L1, L2 and L3: Higher managerial, administrative and professional occupations",L10 and L11: Lower supervisory and technical occupations,L12: Semi-routine occupations,L13: Routine occupations,L14.1 and L14.2: Never worked and long-term unemployed,L15: Full-time students,"L4, L5 and L6: Lower managerial, administrative and professional occupations",L7: Intermediate occupations,L8 and L9: Small employers and own account workers,A caravan or other mobile or temporary structure,Detached,"In a commercial building, for example, in an office building, hotel or over a shop",In a purpose-built block of flats or tenement,"Part of a converted or shared house, including bedsits","Part of another converted building, for example, former school, church or warehouse",Semi-detached,Terraced,Lives rent free,Owned: Owns outright,Owned: Owns with a mortgage or loan,Private rented: Other private rented,Private rented: Private landlord or letting agency,Shared ownership: Shared ownership,Social rented: Other social rented,Social rented: Rents from council or Local Authority,Owned_combined,Private_Rented_combined,Social_Rented_combined,Underoccupied,Significantly Underoccupied,Overoccupied,Significantly Overoccupied,Ideal Occupation,District or communal heat networks only,Electric only,Mains gas only,No central heating,Oil only,Other central heating only,Renewable energy only,Solid fuel only,Tank or bottled gas only,Two or more types of central heating (including renewable energy),Two or more types of central heating (not including renewable energy),Wood only,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household,No cars or vans in household,Bicycle,"Bus, minibus or coach",Driving a car or van,"Motorcycle, scooter or moped",On foot,Other method of travel to work,Passenger in a car or van,Taxi,Train,"Underground, metro, light rail, tram",Work mainly at or from home,10km to less than 20km,20km to less than 30km,2km to less than 5km,30km to less than 40km,40km to less than 60km,5km to less than 10km,60km and over,Less than 2km,"Works mainly at an offshore installation, in no fixed place, or outside the UK",Works mainly from home,lsoa21cd,lsoa21nm,msoa21cd,msoa21nm,lad22cd,lad22nm,WD21CD,WD21NM,rgn22cd,rgn22nm
0,E00000001,75,101,176,94,0,34,44,10,6,0,0,0,0,16,18,3,0,16,0,2,3,2,3,1,7,23,0,0,0,0,25,2,1,141,1,0,3,0,4,0,0,1,0,3,0,1,5,0,0,7,0,112,0,0,39,4,5,3,6,7,155,0,74,0,0,3,91,7,0,0,158,18,1,7,10,11,122,4,5,2,44,17,7,1,9,10,10,0,0,0,0,0,0,0,1,3,52,5,98,61,27,0,63,6,13,4,0,24,1,37,1,1,80,3,5,5,4,2,38,13,9,0,0,0,93,0,0,0,1,0,59,13,2,13,0,1,6,72,15,7,13,78,1,0,2,29,43,5,3,0,3,0,0,1,0,11,0,41,5,3,46,6,1,1,0,14,0,0,0,1,6,59,2,0,7,0,1,5,1,8,5,59,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London,E05009288,Aldersgate,E12000007,London
1,E00000003,123,135,258,109,0,27,42,19,17,4,0,0,0,11,16,10,0,20,0,5,1,0,3,9,19,15,0,0,0,4,12,0,1,226,0,1,4,0,6,11,7,0,5,0,0,7,6,0,0,3,1,174,0,0,35,0,24,5,13,4,209,1,79,10,3,6,122,32,3,0,201,44,1,3,8,20,184,5,0,6,73,17,9,1,16,18,5,0,1,0,0,0,0,0,0,1,57,19,139,91,44,1,83,6,32,4,0,36,3,54,2,0,96,2,5,2,5,20,58,8,26,0,0,0,97,0,0,1,11,1,60,31,7,10,0,0,2,91,17,2,11,89,2,0,7,39,42,10,3,0,4,0,0,0,0,11,0,47,7,4,51,2,0,7,0,7,1,0,0,1,10,105,2,1,7,0,0,11,0,5,3,105,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London,E05009288,Aldersgate,E12000007,London
2,E00000005,52,60,112,63,0,26,27,8,2,0,0,0,0,9,17,2,0,7,0,5,4,3,1,2,2,11,0,0,0,0,11,1,0,89,0,2,3,0,4,4,5,0,0,0,0,2,2,2,0,7,1,65,0,0,20,0,13,0,6,8,85,0,40,2,3,1,50,14,2,0,102,5,3,2,3,7,88,3,0,3,38,7,6,0,10,4,3,0,1,0,0,0,0,0,1,6,23,3,68,46,20,1,36,6,15,1,0,16,0,25,2,1,37,0,3,1,1,4,28,8,21,0,0,0,62,0,0,0,1,0,29,11,4,17,0,1,1,40,21,2,33,13,2,0,13,22,15,17,1,0,0,1,0,0,0,6,0,18,2,4,37,2,2,3,1,13,0,0,1,3,4,37,1,0,8,0,0,3,0,11,6,37,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London,E05009288,Aldersgate,E12000007,London
3,E00000007,67,77,144,86,0,38,44,2,2,1,0,0,0,3,34,6,0,3,0,22,0,0,0,0,3,7,8,0,0,14,31,3,7,78,0,2,2,0,16,1,7,0,2,0,0,1,2,1,0,3,5,62,0,4,40,0,24,2,4,8,106,4,61,0,1,4,65,10,0,0,131,16,1,2,5,7,117,5,2,1,87,7,1,0,6,8,1,0,0,0,0,0,0,0,1,2,17,11,110,94,15,0,32,1,29,4,1,29,2,36,1,3,62,3,3,1,6,10,39,5,11,0,0,3,76,0,5,2,0,0,20,8,11,46,1,0,1,28,57,1,34,7,4,0,41,5,31,37,1,0,1,0,0,2,1,6,0,16,4,0,66,1,4,5,0,15,0,0,1,2,0,78,2,0,5,0,0,4,2,13,2,78,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London,E05009288,Aldersgate,E12000007,London
4,E00000010,71,107,178,126,0,96,19,4,3,3,0,0,0,17,79,6,0,0,3,10,3,0,0,0,2,5,3,1,0,1,39,3,1,119,1,1,9,1,3,3,3,0,5,5,2,11,7,3,1,10,1,83,0,0,37,0,10,12,22,11,120,0,62,0,3,4,84,25,0,0,165,11,0,15,18,23,93,15,8,0,66,11,3,0,15,15,18,0,0,0,0,1,0,0,9,9,15,8,128,77,33,1,41,8,28,9,11,23,0,28,0,7,34,7,10,14,11,5,45,17,27,0,0,4,121,0,0,0,0,0,13,12,3,28,0,7,63,25,31,70,4,2,24,3,91,7,19,68,16,0,2,0,0,2,0,13,0,17,0,0,109,10,5,4,0,20,3,0,0,5,13,55,4,0,9,0,0,4,1,29,11,55,E01000003,City of London 001C,E02000001,City of London 001,E09000001,City of London,E05009302,Cripplegate,E12000007,London

# OA

In [ ]:
OA_Census2021_df.to_excel('N:/Geodatabase/241122_Cleaned Data/OA_Census2021.xlsx', index=False)

# LSOA

In [86]:
LSOA_Census2021_df = OA_Census2021_df.groupby(by=['lsoa21cd', 'lsoa21nm','msoa21cd', 'msoa21nm', 'lad22cd','lad22nm','rgn22cd','rgn22nm'], dropna=False, as_index=False).sum()
LSOA_Census2021_df.head()

,lsoa21cd,lsoa21nm,msoa21cd,msoa21nm,lad22cd,lad22nm,rgn22cd,rgn22nm,female_population,male_population,total_population,total_households,0 people in household,1 person in household,2 people in household,3 people in household,4 people in household,5 people in household,6 people in household,7 people in household,8 or more people in household,One person household: Aged 66 years and over,One person household: Other,"Other household types: Other, including all full-time students and all aged 66 years and over",Other household types: With dependent children,Single family household: All aged 66 years and over,Single family household: Cohabiting couple family: All children non-dependent,Single family household: Cohabiting couple family: No children,Single family household: Cohabiting couple family: With dependent children,Single family household: Lone parent family: All children non-dependent,Single family household: Lone parent family: With dependent children,Single family household: Married or civil partnership couple: All children non-dependent,Single family household: Married or civil partnership couple: Dependent children,Single family household: Married or civil partnership couple: No children,Single family household: Other single family household: Other family composition,african,british_overseas_territories,antarctica_and_oceania_including_australasia,europe,other_europe,ireland,united_kingdom,america_caribbean,asia_middle_east,no_passport,"Asian, Asian British or Asian Welsh: Bangladeshi","Asian, Asian British or Asian Welsh: Chinese","Asian, Asian British or Asian Welsh: Indian","Asian, Asian British or Asian Welsh: Other Asian","Asian, Asian British or Asian Welsh: Pakistani","Black, Black British, Black Welsh, Caribbean or African: African","Black, Black British, Black Welsh, Caribbean or African: Caribbean","Black, Black British, Black Welsh, Caribbean or African: Other Black",Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups,Mixed or Multiple ethnic groups: White and Asian,Mixed or Multiple ethnic groups: White and Black African,Mixed or Multiple ethnic groups: White and Black Caribbean,Other ethnic group: Any other ethnic group,Other ethnic group: Arab,"White: English, Welsh, Scottish, Northern Irish or British",White: Gypsy or Irish Traveller,White: Irish,White: Other White,White: Roma,all_asian_ethnic_groups,all_black_ethnic_groups,all_mixed_or_multiple_ethnic_groups,other_ethnic_group,all_white_ethnic_groups,Buddhist,Christian,Hindu,Jewish,Muslim,No religion,Not answered,Other religion,Sikh,Not a student,Student,Apprenticeship,NVQ_level_1,NVQ_level_2,NVQ_level_3,NVQ_level_4_to_5,No qualifications,Vocational_and_Other_Education,Economically Inactive: Looking after home or family,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time,Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically active and a full-time student: In employment: Employee: Full-time,Economically active and a full-time student: In employment: Employee: Part-time,Economically active and a full-time student: In employment: Self-employed with employees: Full-time,Economically active and a full-time student: In employment: Self-employed with employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Student,Economically_Active,Economically_Active_Employeed,Economically_Active_Self_Employed,Economically_Active_Student,Economically_Inactive,Administrative and secretarial occupations,Associate professional and technical occupations,"Caring, leisure and other service occupations",Elementary occupations,"Managers, directors and senior officials","Process, plant and machine operatives",Professional occupations,Sales and customer service occupations,Skilled trades occupations,"L1, L2 and L3: Higher managerial, administrative and professional occupations",L10 and L11: Lower supervisory and technical occupations,L12: Semi-routine occupations,L13: Routine occupations,L14.1 and L14.2: Never worked and long-term unemployed,L15: Full-time students,"L4, L5 and L6: Lower managerial, administrative and professional occupations",L7: Intermediate occupations,L8 and L9: Small employers and own account workers,A caravan or other mobile or temporary structure,Detached,"In a commercial building, for example, in an office building, hotel or over a shop",In a purpose-built block of flats or tenement,"Part of a converted or shared house, including bedsits","Part of another converted building, for example, former school, church or warehouse",Semi-detached,Terraced,Lives rent free,Owned: Owns outright,Owned: Owns with a mortgage or loan,Private rented: Other private rented,Private rented: Private landlord or letting agency,Shared ownership: Shared ownership,Social rented: Other social rented,Social rented: Rents from council or Local Authority,Owned_combined,Private_Rented_combined,Social_Rented_combined,Underoccupied,Significantly Underoccupied,Overoccupied,Significantly Overoccupied,Ideal Occupation,District or communal heat networks only,Electric only,Mains gas only,No central heating,Oil only,Other central heating only,Renewable energy only,Solid fuel only,Tank or bottled gas only,Two or more types of central heating (including renewable energy),Two or more types of central heating (not including renewable energy),Wood only,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household,No cars or vans in household,Bicycle,"Bus, minibus or coach",Driving a car or van,"Motorcycle, scooter or moped",On foot,Other method of travel to work,Passenger in a car or van,Taxi,Train,"Underground, metro, light rail, tram",Work mainly at or from home,10km to less than 20km,20km to less than 30km,2km to less than 5km,30km to less than 40km,40km to less than 60km,5km to less than 10km,60km and over,Less than 2km,"Works mainly at an offshore installation, in no fixed place, or outside the UK",Works mainly from home
0,E01000001,City of London 001A,E02000001,City of London 001,E09000001,City of London,E12000007,London,688,789,1477,838,0,371,351,70,41,6,0,0,0,126,245,50,1,84,0,99,13,7,10,13,68,112,11,5,0,28,191,29,26,1063,7,38,25,4,66,49,37,2,8,3,0,18,27,7,2,46,22,822,0,31,318,11,158,11,54,68,1182,10,512,39,29,32,711,136,5,0,1272,155,13,26,54,86,1126,32,16,34,573,78,42,2,80,81,35,2,3,0,0,2,3,6,9,24,306,76,891,656,205,10,449,39,184,19,4,194,6,406,11,5,620,11,31,16,37,84,367,72,118,0,0,8,803,0,10,3,14,1,338,144,53,283,3,4,17,482,336,21,265,227,106,3,236,258,342,108,22,2,24,1,0,5,1,72,0,244,28,12,551,24,12,18,3,109,3,0,3,17,35,639,11,1,53,2,3,34,3,84,33,639
1,E01000002,City of London 001B,E02000001,City of London 001,E09000001,City of London,E12000007,London,607,777,1384,824,0,411,315,62,33,5,1,0,0,101,309,45,2,59,3,96,10,15,13,10,44,105,19,10,0,16,179,25,28,964,8,29,23,6,103,37,33,2,7,2,0,29,25,4,2,36,13,735,0,42,302,6,181,9,60,49,1085,10,469,21,35,27,680,139,5,0,1210,141,4,28,52,89,1086,23,18,28,593,61,36,4,111,63,32,1,4,0,0,3,0,3,0,42,233,87,900,659,214,8,390,35,187,5,7,218,3,414,3,3,631,6,17,10,42,88,358,55,95,0,1,8,768,2,14,2,29,0,283,149,38,324,2,6,23,432,362,29,252,166,116,6,287,252,358,76,18,1,34,2,0,2,2,81,1,204,27,13,579,25,15,19,1,93,5,3,2,12,30,678,6,2,40,4,3,21,2,78,48,678
2,E01000003,City of London 001C,E02000001,City of London 001,E09000001,City of London,E12000007,London,755,854,1609,1019,0,582,321,74,32,6,1,0,0,161,422,55,1,31,5,104,16,21,22,15,44,108,18,13,0,15,228,26,29,1143,20,26,51,11,51,37,50,2,32,15,8,43,35,15,7,91,19,813,0,32,343,4,151,55,100,110,1192,14,549,18,44,50,776,156,6,3,1436,138,12,61,90,121,1055,132,34,40,677,115,18,7,90,83,68,1,3,0,0,2,2,2,40,47,243,66,1058,796,198,8,436,72,217,27,42,191,11,388,26,28,503,33,70,70,72,67,426,131,128,0,1,6,996,2,13,0,0,2,232,145,42,293,0,52,249,377,335,301,191,42,218,11,551,198,232,443,37,2,24,1,0,6,2,73,0,168,15,5,825,62,26,27,4,146,16,7,4,21,72,622,22,3,80,0,0,60,7,145,67,622
3,E01000005,City of London 001E,E02000001,City of London 001,E09000001,City of London,E12000007,London,545,555,1100,476,0,218,120,48,44,25,7,8,4,47,172,36,20,7,4,28,12,25,29,16,46,26,11,18,0,11,163,3,4,769,12,48,41,258,35,23,31,1,75,27,15,31,16,12,20,101,26,259,0,20,148,6,348,117,79,127,433,7,405,16,12,341,244,69,6,0,798,253,32,61,122,130,387,197,29,40,328,95,3,5,25,19,59,7,12,0,0,3,1,15,52,73,95,132,534,442,52,23,392,43,61,52,86,52,16,129,34,21,143,42,102,103,152,163,141,61,56,0,0,10,456,5,5,0,2,0,19,22,15,91,1,186,148,41,106,334,121,24,108,20,206,107,85,211,7,3,27,0,0,3,0,36,0,92,9,3,375,20,45,32,2,90,8,1,2,25,69,204,27,4,78,0,2,45,2,95,47,204
4,E01000006,Barking and Dagenham 016A,E02000017,Barking and Dagenham 016,E09000002,Barking and Dagenham,E12000007,London,902,943,1845,553,0,93,124,105,99,62,40,14,16,26,62,65,76,22,2,13,23,22,55,40,106,27,10,27,0,2,450,10,11,1107,4,137,94,215,11,161,89,409,129,42,30,26,16,15,15,82,5,239,0,15,338,13,885,201,72,87,605,12,686,105,1,724,131,120,2,66,1276,417,38,155,170,206,499,295,66,133,413,198,24,10,111,83,58,8,27,1,0,2,4,8,74,50,117,106,897,646,228,42,480,68,97,82,161,76,101,126,68,107,118,68,164,164,183,156,210,125,237,1,34,0,121,24,3,88,283,0,109,159,30,229,3,13,12,268,259,25,106,183,90,41,136,0,95,386,14,0,11,0,0,5,3,35,0,251,97,27,183,6,60,226,6,61,17,10,1,104,206,191,160,42,89,10,5,108,12,61,205,191

In [88]:
LSOA_Census2021_df.to_excel('N:/Geodatabase/241122_Cleaned Data/LSOA_Census2021.xlsx', index=False)
#LSOA_Census2021_df.to_excel('N:/Geodatabase/241122_Cleaned Data/LSOA_Census2021.xlsx', index=False, engine='xlsxwriter')

# MSOA

In [90]:
MSOA_Census2021_df = OA_Census2021_df.groupby(by=['msoa21cd', 'msoa21nm','lad22cd', 'lad22nm','rgn22cd','rgn22nm'], dropna=False, as_index=False).sum()
MSOA_Census2021_df = pd.merge(MSOA_Census2021_df,MSOA_pop_per_age_df_P, how = 'left', on='msoa21cd')
MSOA_Census2021_df = pd.merge(MSOA_Census2021_df,MSOA_avg_income_df, how = 'left', on='msoa21cd')
MSOA_Census2021_df = pd.merge(MSOA_Census2021_df,MSOA_industry_df_P, how = 'left', on='msoa21cd')
MSOA_Census2021_df = pd.merge(MSOA_Census2021_df,MSOA_health_df, how = 'left', on='msoa21cd')
MSOA_Census2021_df.head()

,msoa21cd,msoa21nm,lad22cd,lad22nm,rgn22cd,rgn22nm,female_population,male_population,total_population,total_households,0 people in household,1 person in household,2 people in household,3 people in household,4 people in household,5 people in household,6 people in household,7 people in household,8 or more people in household,One person household: Aged 66 years and over,One person household: Other,"Other household types: Other, including all full-time students and all aged 66 years and over",Other household types: With dependent children,Single family household: All aged 66 years and over,Single family household: Cohabiting couple family: All children non-dependent,Single family household: Cohabiting couple family: No children,Single family household: Cohabiting couple family: With dependent children,Single family household: Lone parent family: All children non-dependent,Single family household: Lone parent family: With dependent children,Single family household: Married or civil partnership couple: All children non-dependent,Single family household: Married or civil partnership couple: Dependent children,Single family household: Married or civil partnership couple: No children,Single family household: Other single family household: Other family composition,african,british_overseas_territories,antarctica_and_oceania_including_australasia,europe,other_europe,ireland,united_kingdom,america_caribbean,asia_middle_east,no_passport,"Asian, Asian British or Asian Welsh: Bangladeshi","Asian, Asian British or Asian Welsh: Chinese","Asian, Asian British or Asian Welsh: Indian","Asian, Asian British or Asian Welsh: Other Asian","Asian, Asian British or Asian Welsh: Pakistani","Black, Black British, Black Welsh, Caribbean or African: African","Black, Black British, Black Welsh, Caribbean or African: Caribbean","Black, Black British, Black Welsh, Caribbean or African: Other Black",Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups,Mixed or Multiple ethnic groups: White and Asian,Mixed or Multiple ethnic groups: White and Black African,Mixed or Multiple ethnic groups: White and Black Caribbean,Other ethnic group: Any other ethnic group,Other ethnic group: Arab,"White: English, Welsh, Scottish, Northern Irish or British",White: Gypsy or Irish Traveller,White: Irish,White: Other White,White: Roma,all_asian_ethnic_groups,all_black_ethnic_groups,all_mixed_or_multiple_ethnic_groups,other_ethnic_group,all_white_ethnic_groups,Buddhist,Christian,Hindu,Jewish,Muslim,No religion,Not answered,Other religion,Sikh,Not a student,Student,Apprenticeship,NVQ_level_1,NVQ_level_2,NVQ_level_3,NVQ_level_4_to_5,No qualifications,Vocational_and_Other_Education,Economically Inactive: Looking after home or family,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time,Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically active and a full-time student: In employment: Employee: Full-time,Economically active and a full-time student: In employment: Employee: Part-time,Economically active and a full-time student: In employment: Self-employed with employees: Full-time,Economically active and a full-time student: In employment: Self-employed with employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Student,Economically_Active,Economically_Active_Employeed,Economically_Active_Self_Employed,Economically_Active_Student,Economically_Inactive,Administrative and secretarial occupations,Associate professional and technical occupations,"Caring, leisure and other service occupations",Elementary occupations,"Managers, directors and senior officials","Process, plant and machine operatives",Professional occupations,Sales and customer service occupations,Skilled trades occupations,"L1, L2 and L3: Higher managerial, administrative and professional occupations",L10 and L11: Lower supervisory and technical occupations,L12: Semi-routine occupations,L13: Routine occupations,L14.1 and L14.2: Never worked and long-term unemployed,L15: Full-time students,"L4, L5 and L6: Lower managerial, administrative and professional occupations",L7: Intermediate occupations,L8 and L9: Small employers and own account workers,A caravan or other mobile or temporary structure,Detached,"In a commercial building, for example, in an office building, hotel or over a shop",In a purpose-built block of flats or tenement,"Part of a converted or shared house, including bedsits","Part of another converted building, for example, former school, church or warehouse",Semi-detached,Terraced,Lives rent free,Owned: Owns outright,Owned: Owns with a mortgage or loan,Private rented: Other private rented,Private rented: Private landlord or letting agency,Shared ownership: Shared ownership,Social rented: Other social rented,Social rented: Rents from council or Local Authority,Owned_combined,Private_Rented_combined,Social_Rented_combined,Underoccupied,Significantly Underoccupied,Overoccupied,Significantly Overoccupied,Ideal Occupation,District or communal heat networks only,Electric only,Mains gas only,No central heating,Oil only,Other central heating only,Renewable energy only,Solid fuel only,Tank or bottled gas only,Two or more types of central heating (including renewable energy),Two or more types of central heating (not including renewable energy),Wood only,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household,No cars or vans in household,Bicycle,"Bus, minibus or coach",Driving a car or van,"Motorcycle, scooter or moped",On foot,Other method of travel to work,Passenger in a car or van,Taxi,Train,"Underground, metro, light rail, tram",Work mainly at or from home,10km to less than 20km,20km to less than 30km,2km to less than 5km,30km to less than 40km,40km to less than 60km,5km to less than 10km,60km and over,Less than 2km,"Works mainly at an offshore installation, in no fixed place, or outside the UK",Works mainly from home,legal children_0_to_15,working_age_adults_16_66,non_working_age_adults_66_above,age_0_to_1,age_1_to_9,age_10_to_19,age_14_to_25,age_20_to_29,age_30_to_39,age_40_to_49,age_50_to_59,age_60_to_69,age_70_to_79,age_80_to_89,age_90_to_99,age_100_over,MSOA name,Total annual income (£),Net annual income (£),Net annual income before housing costs (£),Net annual income after housing costs (£),,Advertising,"Agriculture, Forestry and Fishing",Architecture and Engineering,"Arts, Entertainment and Recreation",Broadcasting,Education,"Electricity, gas, steam and air conditioning supply",Employment Agencies,Film and TV,Finance and Insurance,Health and Social Care Services,Hospitality and Food Services,Information Technologies,International Organisations,Leasing,Legal and Accounting,Maintenance Services,Management and Management Consulting,Manufacturing,Mining and Quarrying,Office Administration Services,Other,Personal Service Provision,Printing,"Professional, Scientific and Technical Services",Public Administration,Publishing,Real Estate,Repair of Electronics and Goods,Scientific Research and Development,Security Services,Telecommunications,Transportation and Storage,Travel Services,Veterinary Services,"Water Supply, Sewerage and Waste Management",Web Search and Data Processing,Wholesale and Retail Trade,Industry_pop,life_expectancy_male_at_birth_2016_2020,life_expectancy_female_at_birth_2016_2020,life_expectancy_average_at_birth_2016_2020,rate_mortality_all_causes_all_ages_per_100_2016_2020,rate_mortality_all_causes_under_75_per_100_2016_2020,rate_mortality_cancer_per_100_2016_2020,rate_mortality_cancer_under_75_per_100_2016_2020,rate_mortality_circulatory_disease_per_100_2016_2020,rate_mortality_circulatory_disease_under_75_per_100_2016_2020,rate_mortality_coronary_heart_disease_per_100_2016_2020,rate_mortality_stroke_per_100_2016_2020,rate_mortality_respiratory_diseases_per_100_2016_2020,rate_mortality_respiratory_diseases_under_75_per_100_2016_2020,percentage_old_age_pop_living_alone_65_plus_2011,old_age_pop_living_alone_65_plus_2011,percentage_households_in_poverty_2013_2014,percentage_household_with_overcrowding_2011,household_with_overcrowding_2011,percentage_unemployment_working_age_claiming_out_of_work_benefit_2021,unemployed_working_age_claiming_out_of_work_benefit_2021,rate_long_term_unemployment_per_1000_working_age_population_2021,long_term_unemployment_2021,percentage_reception_overweight_including_obesity,reception_overweight_including_obesity,percentage_reception_obesity_including_severe_obesity,reception_obesity_including_severe_obesity,percentage_year6_overweight_including_obesity,year6_overweight_including_obesity,percentage_year6_obese_including_severe_obesity,year6_obese_including_severe_obesity
0,E02000001,City of London 001,E09000001,City of London,E12000007,London,3862,4717,8579,4913,0,2507,1766,372,192,51,11,8,10,495,2013,398,32,203,12,600,56,86,88,69,251,529,101,74,0,136,1454,185,130,5468,85,301,199,283,544,322,259,32,150,54,26,188,173,50,56,369,113,3652,0,186,2065,62,1440,230,467,482,5965,94,2981,203,180,538,3762,766,54,8,7210,1162,81,222,395,710,5936,531,134,195,3761,441,149,28,520,365,283,19,38,0,0,10,16,47,123,303,993,723,5547,4259,1062,83,2337,270,1027,155,178,1108,52,2345,122,98,3173,133,289,257,441,794,1914,431,571,0,7,202,4274,65,272,17,78,3,1114,678,316,2068,11,286,447,1792,2384,733,1231,621,779,49,2226,914,1940,1321,188,13,145,9,0,30,8,350,1,946,125,44,3789,191,134,123,12,760,52,12,20,97,346,3611,86,15,384,7,9,237,30,674,309,3611,580,6962,1037,44,374,391,1453,2178,1724,1091,1158,850,528,245,37,3,City of London 001,101800.0,62700.0,65000.0,59300.0,118,135,0,219,303,32,375,2,37,68,1063,340,178,381,10,3,545,67,192,93,1,38,88,31,14,108,220,44,88,1,65,23,27,68,26,1,2,37,309,5352,90.368903,90.737293,90.553098,50.247355,61.290593,65.183666,67.478951,55.775547,64.748007,73.347225,35.621603,36.508637,71.472594,50.821256,526.0,15.5,34.595211,1517.0,3.675168,276.666667,1.328374,10.00,26.66667,20.0,0.00000,0.0,35.71429,25.0,14.28571,10.0
1,E02000002,Barking and Dagenham 001,E09000002,Barking and Dagenham,E12000007,London,4368,3921,8289,2874,0,732,631,528,536,277,122,33,22,335,393,103,209,133,29,52,143,186,433,132,563,124,30,203,0,7,881,71,65,5837,4,257,907,622,29,445,205,541,1197,322,219,101,47,112,145,197,53,3015,6,85,902,36,1842,1738,405,250,4044,27,3897,270,31,1607,1817,426,32,172,5313,2315,251,639,789,823,1855,1431,202,480,1683,734,73,22,354,237,278,28,76,0,2,4,17,72,340,252,822,496,3381,2521,686,127,2390,297,310,379,480,278,299,534,255,415,408,312,741,727,824,670,916,612,773,1,132,8,1096,32,3,781,809,9,508,729,35,383,11,276,921,1237,418,1197,704,542,488,125,1014,41,314,2114,62,1,47,3,0,16,13,259,0,1279,549,139,919,31,378,1265,16,127,45,111,20,197,373,677,471,194,475,66,22,392,27,163,752,677,2299,5146,836,115,1407,1385,1270,930,1317,1128,873,552,386,238,62,3,Barking and Dagenham 001,43600.0,32500.0,28600.0,22500.0,503,19,1,19,39,5,289,8,26,13,98,586,193,68,0,8,86,107,16,86,1,20,11,25,3,9,164,3,51,2,3,50,15,213,5,4,19,2,467,3237,78.774088,81.704768,80.239428,99.344041,132.848007,112.130843,135.386944,92.922057,142.866305,83.598469,73.317476,102.475182,120.340653,37.148047,409.0,28.1,14.743826,400.0,8.493659,392.916667,4.053178,18.75,28.16901,100.0,12.67606,45.0,48.14815,195.0,33.33333,135.0
2,E02000003,Barking and Dagenham 002,E09000002,Barking and Dagenham,E12000007,London,5832,5707,11539,3930,0,980,950,687,677,346,144,82,79,443,527,207,397,154,21,98,120,212,416,264,729,271,72,181,0,3,1970,79,134,7616,17,636,886,1196,49,1148,340,1306,1092,456,246,145,87,110,142,490,42,2958,9,111,1556,67,4039,1794,484,532,4701,35,4961,574,18,3075,1581,589,57,661,7950,2640,359,915,1104,1252,3015,1883,332,714,2657,1130,160,64,600,353,384,75,141,3,4,29,20,49,255,397,1182,628,5348,4003,1177,272,3176,569,540,521,746,509,431,909,426,581,786,360,1008,976,1034,893,1490,1030,1256,3,178,84,995,176,19,1071,1406,1,939,1249,86,1109,23,112,409,2188,1195,521,957,1340,429,175,1049,22,418,2984,91,4,77,6,0,13,11,307,1,1839,721,218,1154,29,510,1676,20,232,83,122,31,552,638,1337,859,307,605,62,16,541,42,310,1153,1337,2692,7751,1105,201,1788,1483,1728,1607,1942,1533,1372,905,537,322,57,2,Barking and Dagenham 002,50900.0,39200.0,33000.0,27700.0,740,35,2,40,83,6,468,9,43,10,200,749,269,170,2,9,156,184,26,127,1,31,42,91,10,23,293,9,102,1,4,99,33,402,12,5,35,3,717,5241,78.441644,84.285725,81.363685,94.424566,109.105081,89.812507,90.736002,104.476530,143.473019,96.669062,87.573001,115.420217,98.458641,36.406250,466.0,21.6,14.058425,539.0,7.542906,547.916667,1.720815,12.50,20.61856,100.0,10.30928,50.0,42.85714,195.0,29.67033,135.0
3,E02000004,Barking and Dagenham 003,E09000002,Barking and Dagenham,E12000007,London,3394,3242,6636,2305,0,538,615,461,377,192,77,28,24,282,262,118,162,148,34,59,99,143,177,210,398,188,24,104,0,0,733,43,49,4838,6,130,709,313,28,220,225,265,597,222,127,50,45,51,95,190,29,3399,23,67,675,14,1051,946,241,219,4178,35,3459,159,13,829,1670,351,18,104,4899,1347,269,562,662,777,1631,1252,157,296,1846,598,63,22,322,170,224,38,48,1,1,0,6,35,194,217,936,309,3245,2530,577,94,1952,343,349,298,357,262,277,617,215,391,462,325,604,614,566,417,1005,689,635,5,100,11,270,34,6,898,985,1,653,895,36,334,15,111,261,1548,370,372,624,976,180,42,482,6,78,1956,23,2,31,0,0,21,3,179,0,983,572,207,545,39,261,1224,33,147,26,90,27,202,283,780,438,199,354,38,11,271,34,318,664,780,1328,4429,884,65,838,795,987,914,994,849,857,656,414,246,76,2,Barking and Dagenham 003,52000.0,38900.0,34300.0,29300.0,444,27,0,16,44,5,289,7,24,3,122,517,121,75,1,13,83,99,19,107,0,25,22,32,12,14,190,3,50,2,7,27,32,239,6,3,32,4,397,3113,77.937114,81.709185,79.823150,113.410620,114.107227,112.164249,116.986639,95.596398,87.915240,107.077043,93.337770,129.338925,136.803642,31.916996,323.0,22.2,8.110440,188.0,7.960905,336.666667,3.251360,13.75,21.56863,55.0,9.80392,25.0,44.00000,110.0,32.00000,80.0
4,E02000005,Barking and Dagenham 004,E09000002,Barking and Dagenham,E12000007,London,5681,5404,11085,3625,0,709,818,680,803,373,140,60,32,267,440,142,327,108,34,97,169,260,451,210,861,207,54,273,0,2,1590,77,52,7447,22,553,1018,872,68,1166,240,985,1436,296,219,89,81,90,215,341,53,3583,7,69,1226,37,3331,1951,475,394,4922,47,4595,739,22,2387,2207,606,79,404,7245,2862,313,787,1010,1085,2695,1782,309,656,2673,1109,118,54,467,307,323,38,83,4,1,8,7,63,335,387,796,576,5051,3903,946,141,2750,467,503,564,667,440,445,784,444,552,598,421,1027,1040,974,749,1290,892,988,1,216,45,368,95,5,812,2090,8,584,1302,62,718,48,218,692,1886,780,910,1028,943,434,152,1070,23,226,2888,65,0,60,2,0,18,25,315,0,1728,717,171,1016,46,607,1728,38,236,88,123,27,363,535,1075,790,250,685,56,20,533,54,364,1048,1075,3096,7240,750,162,1952,1716,1752,1312,1874,1681,1287,643,380,208,33,0,Barking and Dagenham 004,48100.0,35200.0,30000.0,25800.0,633,28,0,42,77,1,415,16,42,5,171,817,263,162,0,23,98,166,26,143,1,34,25,54,14,20,249,3,77,7,11,77,38,359,7,0,29,4,730,4867,78.987501,83.884420,81.435961,98.243799,109.845725,108.499515,110.294040,101.255854,162.164843,110.991609,68.158421,129.804013,130.078418,39.217759,371.0,23.1,15.142947,482.0,7.722539,514.166667,2.816161,18.75,24.27184,125.0,12.62136,65.0,46.60194,240.0,31.06796,160.0

In [91]:
MSOA_Census2021_df.to_excel('N:/Geodatabase/241122_Cleaned Data/MSOA_Census2021.xlsx', index=False, engine='xlsxwriter')

# Ward

In [94]:
Ward_Census2021_df = OA_Census2021_df.groupby(by=['WD21CD', 'WD21NM','lad22cd', 'lad22nm','rgn22cd','rgn22nm'], dropna=False, as_index=False).sum()
Ward_Census2021_df = pd.merge(Ward_Census2021_df,Median_House_df, how = 'left', on='WD21CD')
Ward_Census2021_df = pd.merge(Ward_Census2021_df,Num_House_df, how = 'left', on='WD21CD')
#Ward_Census2021_df.drop(['WD21NM_y'],1,inplace = True)
#Ward_Census2021_df.rename(columns = {'WD21NM_x':'WD21NM'}, inplace = True)
Ward_Census2021_df.head()

,WD21CD,WD21NM,lad22cd,lad22nm,rgn22cd,rgn22nm,female_population,male_population,total_population,total_households,0 people in household,1 person in household,2 people in household,3 people in household,4 people in household,5 people in household,6 people in household,7 people in household,8 or more people in household,One person household: Aged 66 years and over,One person household: Other,"Other household types: Other, including all full-time students and all aged 66 years and over",Other household types: With dependent children,Single family household: All aged 66 years and over,Single family household: Cohabiting couple family: All children non-dependent,Single family household: Cohabiting couple family: No children,Single family household: Cohabiting couple family: With dependent children,Single family household: Lone parent family: All children non-dependent,Single family household: Lone parent family: With dependent children,Single family household: Married or civil partnership couple: All children non-dependent,Single family household: Married or civil partnership couple: Dependent children,Single family household: Married or civil partnership couple: No children,Single family household: Other single family household: Other family composition,african,british_overseas_territories,antarctica_and_oceania_including_australasia,europe,other_europe,ireland,united_kingdom,america_caribbean,asia_middle_east,no_passport,"Asian, Asian British or Asian Welsh: Bangladeshi","Asian, Asian British or Asian Welsh: Chinese","Asian, Asian British or Asian Welsh: Indian","Asian, Asian British or Asian Welsh: Other Asian","Asian, Asian British or Asian Welsh: Pakistani","Black, Black British, Black Welsh, Caribbean or African: African","Black, Black British, Black Welsh, Caribbean or African: Caribbean","Black, Black British, Black Welsh, Caribbean or African: Other Black",Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups,Mixed or Multiple ethnic groups: White and Asian,Mixed or Multiple ethnic groups: White and Black African,Mixed or Multiple ethnic groups: White and Black Caribbean,Other ethnic group: Any other ethnic group,Other ethnic group: Arab,"White: English, Welsh, Scottish, Northern Irish or British",White: Gypsy or Irish Traveller,White: Irish,White: Other White,White: Roma,all_asian_ethnic_groups,all_black_ethnic_groups,all_mixed_or_multiple_ethnic_groups,other_ethnic_group,all_white_ethnic_groups,Buddhist,Christian,Hindu,Jewish,Muslim,No religion,Not answered,Other religion,Sikh,Not a student,Student,Apprenticeship,NVQ_level_1,NVQ_level_2,NVQ_level_3,NVQ_level_4_to_5,No qualifications,Vocational_and_Other_Education,Economically Inactive: Looking after home or family,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time,Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically active and a full-time student: In employment: Employee: Full-time,Economically active and a full-time student: In employment: Employee: Part-time,Economically active and a full-time student: In employment: Self-employed with employees: Full-time,Economically active and a full-time student: In employment: Self-employed with employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Student,Economically_Active,Economically_Active_Employeed,Economically_Active_Self_Employed,Economically_Active_Student,Economically_Inactive,Administrative and secretarial occupations,Associate professional and technical occupations,"Caring, leisure and other service occupations",Elementary occupations,"Managers, directors and senior officials","Process, plant and machine operatives",Professional occupations,Sales and customer service occupations,Skilled trades occupations,"L1, L2 and L3: Higher managerial, administrative and professional occupations",L10 and L11: Lower supervisory and technical occupations,L12: Semi-routine occupations,L13: Routine occupations,L14.1 and L14.2: Never worked and long-term unemployed,L15: Full-time students,"L4, L5 and L6: Lower managerial, administrative and professional occupations",L7: Intermediate occupations,L8 and L9: Small employers and own account workers,A caravan or other mobile or temporary structure,Detached,"In a commercial building, for example, in an office building, hotel or over a shop",In a purpose-built block of flats or tenement,"Part of a converted or shared house, including bedsits","Part of another converted building, for example, former school, church or warehouse",Semi-detached,Terraced,Lives rent free,Owned: Owns outright,Owned: Owns with a mortgage or loan,Private rented: Other private rented,Private rented: Private landlord or letting agency,Shared ownership: Shared ownership,Social rented: Other social rented,Social rented: Rents from council or Local Authority,Owned_combined,Private_Rented_combined,Social_Rented_combined,Underoccupied,Significantly Underoccupied,Overoccupied,Significantly Overoccupied,Ideal Occupation,District or communal heat networks only,Electric only,Mains gas only,No central heating,Oil only,Other central heating only,Renewable energy only,Solid fuel only,Tank or bottled gas only,Two or more types of central heating (including renewable energy),Two or more types of central heating (not including renewable energy),Wood only,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household,No cars or vans in household,Bicycle,"Bus, minibus or coach",Driving a car or van,"Motorcycle, scooter or moped",On foot,Other method of travel to work,Passenger in a car or van,Taxi,Train,"Underground, metro, light rail, tram",Work mainly at or from home,10km to less than 20km,20km to less than 30km,2km to less than 5km,30km to less than 40km,40km to less than 60km,5km to less than 10km,60km and over,Less than 2km,"Works mainly at an offshore installation, in no fixed place, or outside the UK",Works mainly from home,Overall 2013,Overall 2014,Overall 2015,Overall 2016,Overall 2017,Overall 2018,Overall 2019,Overall 2020,Overall 2021,Overall 2022,Overall 2023,Overall 10 year change,Overall 5 year change,Detached 2013,Detached 2014,Detached 2015,Detached 2016,Detached 2017,Detached 2018,Detached 2019,Detached 2020,Detached 2021,Detached 2022,Detached 2023,Detached 10 year change,Detached 5 year change,Semi Detached 2013,Semi Detached 2014,Semi Detached 2015,Semi Detached 2016,Semi Detached 2017,Semi Detached 2018,Semi Detached 2019,Semi Detached 2020,Semi Detached 2021,Semi Detached 2022,Semi Detached 2023,Semi Detached 10 year change,Semi Detached 5 year change,Terraced 2013,Terraced 2014,Terraced 2015,Terraced 2016,Terraced 2017,Terraced 2018,Terraced 2019,Terraced 2020,Terraced 2021,Terraced 2022,Terraced 2023,Terraced 10 year change,Terraced 5 year change,Flats 2013,Flats 2014,Flats 2015,Flats 2016,Flats 2017,Flats 2018,Flats 2019,Flats 2020,Flats 2021,Flats 2022,Flats 2023,Flats 10 year change,Flats 5 year change,Houses sold last year,Houses sold in the last 5 years,Houses sold in the last 10 years,Det_Houses sold last year,Det_Houses sold in the last 5 years,Det_Houses sold in the last 10 years,SDet_Houses sold last year,SDet_Houses sold in the last 5 years,SDet_Houses sold in the last 10 years,Ter_Houses sold last year,Ter_Houses sold in the last 5 years,Ter_Houses sold in the last 10 years,Flt_Houses sold last year,Flt_Houses sold in the last 5 years,Flt_Houses sold in the last 10 years,New_Houses sold last year,New_Houses sold in the last 5 years,New_Houses sold in the last 10 years,NDet_Houses sold last year,NDet_Houses sold in the last 5 years,NDet_Houses sold in the last 10 years,NSDet_Houses sold last year,NSDet_Houses sold in the last 5 years,NSDet_Houses sold in the last 10 years,NTer_Houses sold last year,NTer_Houses sold in the last 5 years,NTer_Houses sold in the last 10 years,NFlt_Houses sold last year,NFlt_Houses sold in the last 5 years,NFlt_Houses sold in the last 10 years,Ex_Houses sold last year,Ex_Houses sold in the last 5 years,Ex_Houses sold in the last 10 years,ExDet_Houses sold last year,ExDet_Houses sold in the last 5 years,ExDet_Houses sold in the last 10 years,ExSDet_Houses sold last year,ExSDet_Houses sold in the last 5 years,ExSDet_Houses sold in the last 10 years,ExTer_Houses sold last year,ExTer_Houses sold in the last 5 years,ExTer_Houses sold in the last 10 years,ExFlt_Houses sold last year,ExFlt_Houses sold in the last 5 years,ExFlt_Houses sold in the last 10 years
0,E05000026,Abbey,E09000002,Barking and Dagenham,E12000007,London,6132,6294,12426,4118,0,1027,852,797,650,391,200,94,97,169,851,264,419,63,11,117,164,184,443,192,880,244,111,347,0,7,2670,122,41,6951,13,1396,802,1424,125,1345,401,1933,1978,282,247,153,90,114,164,500,72,1580,6,45,1890,81,5228,2507,521,572,3602,47,4495,972,7,4546,1206,716,51,388,8084,3239,294,940,980,1152,3408,1987,401,1005,2573,1197,135,60,576,409,535,79,168,5,1,12,16,94,449,481,606,753,5485,4017,1180,281,3294,417,504,532,1020,352,498,871,444,597,751,388,1010,1174,1507,1084,1164,773,1294,4,138,47,2381,153,16,344,1022,10,488,673,114,1688,45,336,761,1161,1802,1097,681,634,874,291,1638,95,948,2370,140,13,119,11,0,32,18,368,0,1483,375,92,2170,62,563,1099,24,289,85,94,25,620,1259,1130,1049,201,484,51,32,716,55,357,1176,1130,165000.0,165000.0,175000.0,196000.0,230000.0,235000.0,227500.0,250000.0,325000.0,228000.0,207500.0,26.0,-12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,101.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,101.0,230000.0,231000.0,257500.0,321000.0,384625.0,389000.0,400000.0,375000.0,405000.0,415000.0,460000.0,100.0,18.0,126500.0,140000.0,165000.0,180000.0,216000.0,230000.0,215000.0,210000.0,315000.0,201000.0,198000.0,57.0,-14.0,360.0,2125.0,4835.0,0.0,0.0,4.0,8.0,17.0,29.0,69.0,453.0,1288.0,283.0,1655.0,3514.0,145.0,790.0,869.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,145.0,790.0,869.0,215.0,1335.0,3966.0,0.0,0.0,4.0,8.0,17.0,29.0,69.0,453.0,1288.0,138.0,865.0,2645.0
1,E05000027,Alibon,E09000002,Barking and Dagenham,E12000007,London,5938,5452,11390,3957,0,889,950,810,723,363,149,53,21,297,595,203,330,113,45,99,200,311,535,232,688,239,63,337,0,2,2065,88,74,7104,8,269,1414,824,61,268,322,380,1709,210,263,114,67,88,148,254,69,4729,13,80,1741,54,1855,2182,417,323,6617,30,5802,161,11,1760,2847,693,46,46,7681,2907,378,946,1114,1114,2572,2065,321,651,2681,1095,119,40,619,315,412,72,135,3,1,8,16,80,417,390,902,559,5281,3983,1093,235,2919,486,449,640,874,386,462,728,392,694,469,468,1128,1227,1059,832,1282,909,1145,1,237,21,392,106,4,894,2309,6,594,1126,84,772,51,231,1099,1720,856,1330,1132,698,625,181,1306,28,218,3152,74,0,93,1,4,34,3,349,0,1846,652,168,1299,67,496,1728,33,269,74,144,21,435,948,901,908,330,715,56,28,467,57,409,1219,901,168000.0,183000.0,220000.0,250000.0,295000.0,295000.0,307000.0,310000.0,310000.0,340000.0,375000.0,123.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,101.0,165500.0,188998.0,225000.0,320000.0,325000.0,327500.0,325000.0,335000.0,0.0,345000.0,383500.0,132.0,17.0,170000.0,183000.0,225000.0,262000.0,300000.0,300000.0,308000.0,311000.0,315000.0,342000.0,377500.0,122.0,26.0,0.0,120998.0,140000.0,169500.0,180000.0,202500.0,210000.0,0.0,200000.0,208000.0,190000.0,101.0,-6.0,240.0,1634.0,3695.0,0.0,0.0,0.0,24.0,146.0,320.0,181.0,1313.0,2908.0,35.0,175.0,467.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,240.0,1634.0,3691.0,0.0,0.0,0.0,24.0,146.0,320.0,181.0,1313.0,2904.0,35.0,175.0,467.0
2,E05000028,Becontree,E09000002,Barking and Dagenham,E12000007,London,6254,6176,12430,4015,0,894,811,766,768,432,164,94,67,350,546,200,350,115,46,88,150,302,438,264,915,189,55,297,0,2,1990,80,63,8239,19,538,1152,1154,67,768,358,1202,1637,347,223,150,82,109,125,387,244,3922,6,70,1520,46,3549,2207,466,631,5564,49,5274,341,14,3356,2225,717,60,399,8196,3338,362,989,1142,1266,2754,2269,350,815,2626,1213,128,41,553,403,475,44,146,2,4,8,20,51,489,456,954,699,5439,4029,1125,224,3413,527,512,587,892,356,542,722,449,614,527,463,1136,1282,1331,944,1290,928,1237,3,230,113,334,106,7,1263,1965,6,565,1135,100,922,56,242,981,1700,1022,1223,1060,868,538,234,1309,11,232,3217,79,2,96,3,0,13,9,350,0,1830,726,228,1238,78,616,1881,40,224,70,151,35,431,651,1020,776,226,895,46,27,603,53,340,1213,1020,172998.0,181995.0,215000.0,256000.0,300000.0,299000.0,312500.0,307250.0,325000.0,340000.0,382500.0,121.0,28.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,101.0,185000.0,199000.0,235500.0,273500.0,310000.0,326000.0,342000.0,335000.0,370000.0,365000.0,405000.0,119.0,24.0,177000.0,187125.0,230000.0,266000.0,312500.0,300000.0,323500.0,310000.0,327000.0,340000.0,381250.0,115.0,27.0,169495.0,179995.0,179995.0,226000.0,259000.0,220000.0,245000.0,230000.0,225000.0,248500.0,222750.0,31.0,1.0,269.0,1789.0,5433.0,0.0,0.0,4.0,62.0,302.0,634.0,174.0,1153.0,2919.0,33.0,334.0,1876.0,0.0,0.0,1027.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,204.0,0.0,0.0,823.0,269.0,1789.0,4406.0,0.0,0.0,4.0,62.0,302.0,634.0,174.0,1153.0,2715.0,33.0,334.0,1053.0
3,E05000029,Chadwell Heath,E09000002,Barking and Dagenham,E12000007,London,6320,5816,12136,4193,0,1063,938,753,756,417,181,63,34,493,565,181,323,197,38,81,182,266,534,229,824,211,54,248,0,7,1410,88,95,8549,13,484,1183,1168,52,833,345,962,1435,490,286,156,83,157,202,359,67,4044,12,116,1297,70,3360,2211,598,426,5539,45,5354,465,35,2745,2369,658,56,407,8029,3151,373,940,1156,1261,2850,2081,312,730,2570,1107,126,37,513,349,427,40,114,1,4,9,28,92,440,391,1289,684,5129,3831,1025,196,3534,486,498,552,680,454,421,818,407,597,683,437,1102,1023,1184,935,1452,982,1160,2,185,36,1379,77,16,1267,1212,9,863,1165,65,735,13,306,1036,2028,800,1342,1024,1009,643,172,1351,56,433,3122,81,4,72,5,0,20,17,377,0,1856,820,228,1301,40,538,1834,23,190,77,143,32,369,553,1119,742,286,665,83,30,572,47,260,1103,1119,218750.0,210000.0,241000.0,285000.0,300000.0,296000.0,327000.0,350000.0,363750.0,385500.0,415000.0,90.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,101.0,237500.0,250000.0,280000.0,330000.0,335000.0,394000.0,435000.0,382500.0,415000.0,425000.0,430000.0,81.0,9.0,220000.0,210000.0,250000.0,295000.0,323750.0,325000.0,366000.0,347500.0,350000.0,385000.0,415000.0,89.0,28.0,128998.0,123000.0,149500.0,197500.0,190000.0,222000.0,285000.0,210000.0,195000.0,220000.0,245000.0,90.0,10.0,375.0,2407.0,4364.0,11.0,54.0,98.0,114.0,686.0,1210.0,170.0,964.0,1816.0,80.0,703.0,1240.0,0.0,446.0,484.0,0.0,0.0,0.0,0.0,72.0,72.0,0.0,44.0,44.0,0.0,330.0,368.0,375.0,1961.0,3880.0,11.0,54.0,98.0,114.0,614.0,1138.0,170.0,920.0,1772.0,80.0,373.0,872.0
4,E05000030,Eastbrook,E09000002,Barking and Dagenham,E12000007,London,5886,5628,11514,3924,0,933,988,757,649,360,148,62,45,446,490,193,290,225,53,100,165,230,357,334,701,286,47,239,0,0,1533,66,75,8007,6,242,1295,816,81,364,347,395,1368,337,259,78,84,84,152,289,57,5335,25,105,1277,49,2003,1964,398,346,6791,43,5958,247,20,1647,2759,670,29,134,8243,2569,454,951,1113,1221,2761,2246,303,576,2971,1027,114,36,572,297,381,59,115,5,3,6,13,57,351,406,1486,591,5398,4172,1019,201,3410,527,519,541,724,415,501,952,371,664,676,529,1061,1150,1033,812,1597,1055,1133,6,172,33,648,64,11,1345,1647,3,991,1375,76,672,23,170,621,2366,748,791,1023,1487,372,116,930,20,241,3186,56,2,58,2,0,27,5,324,0,1682,889,291,1063,64,465,1933,42,236,54,141,43,385,679,1165,827,338,622,65,24,492,53,446,1166,1165,197250.0,210000.0,249995.0,280000.0,330000.0,330000.0,345000.0,345000.0,374000.0,410000.0,421500.0,114.0,28.0,0.0,0.0,322500.0,357500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101.0,101.0,213500.0,225000.0,263000.0,340000.0,355000.0,360000.0,375000.0,358000.0,400000.0,425000.0,450000.0,111.0,25.0,197500.0,210000.0,250000.0,282500.0,328750.0,330000.0,352500.0,338000.0,369500.0,410000.0,427500.0,116.0,30.0,124995.0,145000.0,156500.0,188000.0,235750.0,228500.0,238250.0,225000.0,195000.0,237000.0,255000.0,104.0,12.0,362.0,2287.0,4716.0,11.0,44.0,116.0,82.0,521.0,1068.0,233.0,1512.0,3029.0,36.0,210.0,503.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,362.0,2287.0,4708.0,11.0,44.0,116.0,82.0,521.0,1064.0,233.0,1512.0,3029.0,36.0,210.0,499.0

In [95]:
Ward_Census2021_df.to_excel('N:/Geodatabase/241122_Cleaned Data/Ward_Census2021_House_Price_and_Sales.xlsx', index=False, engine='xlsxwriter')

# LA

In [96]:
LAD_Census2021_df = OA_Census2021_df.groupby(by=['lad22cd', 'lad22nm','rgn22cd','rgn22nm'], dropna=False, as_index=False).sum()
#LAD_Census_df = pd.merge(LA_boundary_df,LA_df, how = 'left', on='lad22cd')
LAD_Census2021_df = pd.merge(LAD_Census2021_df,LAD_pop_per_age_df_P, how = 'left', on='lad22cd')
LAD_Census2021_df = pd.merge(LAD_Census2021_df,LAD_industry_df_P, how = 'left', on='lad22cd')
LAD_Census2021_df.head()

,lad22cd,lad22nm,rgn22cd,rgn22nm,female_population,male_population,total_population,total_households,0 people in household,1 person in household,2 people in household,3 people in household,4 people in household,5 people in household,6 people in household,7 people in household,8 or more people in household,One person household: Aged 66 years and over,One person household: Other,"Other household types: Other, including all full-time students and all aged 66 years and over",Other household types: With dependent children,Single family household: All aged 66 years and over,Single family household: Cohabiting couple family: All children non-dependent,Single family household: Cohabiting couple family: No children,Single family household: Cohabiting couple family: With dependent children,Single family household: Lone parent family: All children non-dependent,Single family household: Lone parent family: With dependent children,Single family household: Married or civil partnership couple: All children non-dependent,Single family household: Married or civil partnership couple: Dependent children,Single family household: Married or civil partnership couple: No children,Single family household: Other single family household: Other family composition,african,british_overseas_territories,antarctica_and_oceania_including_australasia,europe,other_europe,ireland,united_kingdom,america_caribbean,asia_middle_east,no_passport,"Asian, Asian British or Asian Welsh: Bangladeshi","Asian, Asian British or Asian Welsh: Chinese","Asian, Asian British or Asian Welsh: Indian","Asian, Asian British or Asian Welsh: Other Asian","Asian, Asian British or Asian Welsh: Pakistani","Black, Black British, Black Welsh, Caribbean or African: African","Black, Black British, Black Welsh, Caribbean or African: Caribbean","Black, Black British, Black Welsh, Caribbean or African: Other Black",Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups,Mixed or Multiple ethnic groups: White and Asian,Mixed or Multiple ethnic groups: White and Black African,Mixed or Multiple ethnic groups: White and Black Caribbean,Other ethnic group: Any other ethnic group,Other ethnic group: Arab,"White: English, Welsh, Scottish, Northern Irish or British",White: Gypsy or Irish Traveller,White: Irish,White: Other White,White: Roma,all_asian_ethnic_groups,all_black_ethnic_groups,all_mixed_or_multiple_ethnic_groups,other_ethnic_group,all_white_ethnic_groups,Buddhist,Christian,Hindu,Jewish,Muslim,No religion,Not answered,Other religion,Sikh,Not a student,Student,Apprenticeship,NVQ_level_1,NVQ_level_2,NVQ_level_3,NVQ_level_4_to_5,No qualifications,Vocational_and_Other_Education,Economically Inactive: Looking after home or family,Economically active (excluding full-time students): In employment: Employee: Full-time,Economically active (excluding full-time students): In employment: Employee: Part-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Full-time,Economically active (excluding full-time students): In employment: Self-employed without employees: Part-time,Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically active and a full-time student: In employment: Employee: Full-time,Economically active and a full-time student: In employment: Employee: Part-time,Economically active and a full-time student: In employment: Self-employed with employees: Full-time,Economically active and a full-time student: In employment: Self-employed with employees: Part-time,Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Economically inactive: Retired,Economically inactive: Student,Economically_Active,Economically_Active_Employeed,Economically_Active_Self_Employed,Economically_Active_Student,Economically_Inactive,Administrative and secretarial occupations,Associate professional and technical occupations,"Caring, leisure and other service occupations",Elementary occupations,"Managers, directors and senior officials","Process, plant and machine operatives",Professional occupations,Sales and customer service occupations,Skilled trades occupations,"L1, L2 and L3: Higher managerial, administrative and professional occupations",L10 and L11: Lower supervisory and technical occupations,L12: Semi-routine occupations,L13: Routine occupations,L14.1 and L14.2: Never worked and long-term unemployed,L15: Full-time students,"L4, L5 and L6: Lower managerial, administrative and professional occupations",L7: Intermediate occupations,L8 and L9: Small employers and own account workers,A caravan or other mobile or temporary structure,Detached,"In a commercial building, for example, in an office building, hotel or over a shop",In a purpose-built block of flats or tenement,"Part of a converted or shared house, including bedsits","Part of another converted building, for example, former school, church or warehouse",Semi-detached,Terraced,Lives rent free,Owned: Owns outright,Owned: Owns with a mortgage or loan,Private rented: Other private rented,Private rented: Private landlord or letting agency,Shared ownership: Shared ownership,Social rented: Other social rented,Social rented: Rents from council or Local Authority,Owned_combined,Private_Rented_combined,Social_Rented_combined,Underoccupied,Significantly Underoccupied,Overoccupied,Significantly Overoccupied,Ideal Occupation,District or communal heat networks only,Electric only,Mains gas only,No central heating,Oil only,Other central heating only,Renewable energy only,Solid fuel only,Tank or bottled gas only,Two or more types of central heating (including renewable energy),Two or more types of central heating (not including renewable energy),Wood only,1 car or van in household,2 cars or vans in household,3 or more cars or vans in household,No cars or vans in household,Bicycle,"Bus, minibus or coach",Driving a car or van,"Motorcycle, scooter or moped",On foot,Other method of travel to work,Passenger in a car or van,Taxi,Train,"Underground, metro, light rail, tram",Work mainly at or from home,10km to less than 20km,20km to less than 30km,2km to less than 5km,30km to less than 40km,40km to less than 60km,5km to less than 10km,60km and over,Less than 2km,"Works mainly at an offshore installation, in no fixed place, or outside the UK",Works mainly from home,legal children_0_to_15,working_age_adults_16_66,non_working_age_adults_66_above,age_0_to_1,age_1_to_9,age_10_to_19,age_14_to_25,age_20_to_29,age_30_to_39,age_40_to_49,age_50_to_59,age_60_to_69,age_70_to_79,age_80_to_89,age_90_to_99,age_100_over,,Advertising,"Agriculture, Forestry and Fishing",Architecture and Engineering,"Arts, Entertainment and Recreation",Broadcasting,Education,"Electricity, gas, steam and air conditioning supply",Employment Agencies,Film and TV,Finance and Insurance,Health and Social Care Services,Hospitality and Food Services,Information Technologies,International Organisations,Leasing,Legal and Accounting,Maintenance Services,Management and Management Consulting,Manufacturing,Mining and Quarrying,Office Administration Services,Other,Personal Service Provision,Printing,"Professional, Scientific and Technical Services",Public Administration,Publishing,Real Estate,Repair of Electronics and Goods,Scientific Research and Development,Security Services,Telecommunications,Transportation and Storage,Travel Services,Veterinary Services,"Water Supply, Sewerage and Waste Management",Web Search and Data Processing,Wholesale and Retail Trade,Industry_pop
0,E06000001,Hartlepool,E12000001,North East,47658,44670,92328,40934,0,13616,13841,6781,4526,1520,449,119,68,5629,7971,786,687,3666,405,2245,2423,1743,3886,2514,4246,4513,192,112,0,17,943,67,96,70073,27,237,20685,278,216,336,477,295,322,57,64,173,241,118,146,284,267,87751,38,171,1081,20,1602,443,678,551,89061,180,48516,220,26,1206,37003,4777,284,167,70157,17197,5203,7069,10965,13791,18519,17279,1842,4290,22724,9571,659,213,2238,1444,2661,166,708,0,5,8,16,363,5428,2813,17900,3481,39510,33169,4554,903,33912,3388,4479,4388,4322,3346,3621,5819,3589,4742,5263,5074,11066,11750,10541,4538,12652,8245,5580,115,8083,262,3983,318,162,14533,13461,71,12773,11058,851,6329,243,5609,3992,23831,7180,9601,12146,20010,1148,147,7477,214,1874,33658,335,121,533,57,24,187,186,3718,15,16649,9257,2932,12111,560,1240,22440,75,3128,507,2276,626,274,34,6568,5619,1770,7308,578,357,3155,723,5905,5793,6568,17653,58623,16058,918,10565,11100,12491,10605,11347,10482,13708,11542,8306,3953,705,21,3809,106,149,694,590,23,3763,584,157,46,628,6354,1845,468,1,123,481,779,182,3810,428,268,153,575,64,114,2632,29,544,22,65,260,247,1452,58,47,444,21,5734,37749
1,E06000002,Middlesbrough,E12000001,North East,73037,70889,143926,60257,0,19966,18801,9818,7080,2805,1128,417,251,7729,12227,1992,1558,4490,574,3083,3190,2950,6235,3243,7052,5341,616,1546,2,21,4163,205,275,106551,46,3205,27565,602,669,2805,2042,8990,3340,162,311,663,1105,640,571,2008,1445,114426,160,435,3218,327,15108,3813,2979,3453,118566,431,66164,1439,40,14694,52401,7702,461,594,102403,32597,7037,11234,15262,19975,30116,27281,3040,7517,33038,14187,865,381,3090,2280,4388,400,2075,11,13,14,87,1430,7890,5059,23258,7978,58229,49700,6616,2600,51702,4851,6131,7583,7617,4398,5577,9006,5407,5897,7684,6746,15816,17165,17449,11527,17355,12237,7889,51,10385,306,6457,640,158,25482,16773,116,17200,15909,1392,11277,324,7230,6779,33109,12669,14009,17256,29145,2107,419,11344,226,3554,48397,730,52,1023,69,14,310,182,5683,19,24146,12577,3593,19976,1129,2272,30740,97,5135,982,4057,2041,470,27,9468,3738,1420,13052,832,665,9081,1058,7945,9106,9468,29986,92810,21126,1621,18723,18036,22621,20493,19695,15972,18105,15928,10762,5195,991,22,4797,157,82,831,786,26,5282,439,240,74,1203,11756,3034,781,1,194,558,1257,168,3902,604,495,247,897,87,142,3610,32,762,48,152,451,581,3102,98,75,397,35,9048,56431
2,E06000003,Redcar and Cleveland,E12000001,North East,70421,66085,136506,61643,0,20671,21900,9604,6554,2141,596,140,77,9753,10929,1009,982,6846,609,3247,3384,2632,5174,3717,6265,6851,286,98,0,30,853,56,194,105915,20,190,29055,162,206,176,339,283,183,49,35,236,456,212,274,209,318,131802,86,349,1157,13,1166,267,1178,527,133407,278,72358,139,37,978,54941,7247,491,70,106363,23387,8698,10988,15669,21319,27996,24731,2993,5611,33050,14164,975,309,3333,2427,3530,230,1038,1,0,17,40,481,7274,3372,32030,4440,57788,48482,7044,1326,52727,5002,6605,7445,6482,4797,5327,8416,4754,6800,8276,8955,17120,16791,13924,6026,19909,12435,8898,85,12435,383,3993,793,313,27941,15684,41,22651,17214,1346,8407,345,6383,5269,39865,9753,11652,17887,32085,1347,179,10168,135,2597,50624,558,610,660,109,185,348,306,5452,69,26089,15302,4970,15325,631,1573,33884,123,4107,918,3015,744,552,18,10004,9994,1911,6555,989,821,9145,1242,5690,9236,10004,24189,84014,28333,1176,14688,15117,16793,14036,15515,15200,20667,18061,15016,6926,1286,24,5387,185,283,1075,996,14,5188,537,177,54,854,10322,2815,614,2,175,646,1364,181,4532,1052,312,188,1045,78,161,3698,36,919,51,181,400,358,2676,119,128,467,33,8317,55620
3,E06000004,Stockton-on-Tees,E12000001,North East,100061,96525,196586,83756,0,25987,28726,13762,10297,3317,1020,408,243,10799,15189,1681,1659,7877,670,4959,4567,3410,6682,4924,11571,9343,428,712,2,55,2391,129,397,156135,104,1372,34955,229,691,1805,1434,4867,1813,129,247,727,1135,466,410,1089,555,177520,143,527,2610,145,9026,2189,2738,1644,180945,533,100385,810,58,6675,76836,9932,551,784,148532,37322,10560,15320,23016,29030,46672,29454,4033,7677,53758,19937,1537,467,5048,3437,5129,405,1771,6,5,18,53,767,8228,5853,37039,6858,89313,75871,10489,2258,65655,8441,10913,8867,9414,8971,6992,16690,7311,8848,16007,10105,20153,22270,17935,9488,30988,19209,11851,79,22189,351,6440,725,182,35503,18289,79,27701,27660,1818,12367,388,6471,7164,55361,14185,13635,23169,45115,2038,422,12986,271,3786,69456,712,387,831,89,53,420,389,7340,31,34298,23683,7058,18738,1258,2267,50923,192,5427,1316,4379,1312,529,45,18821,9933,2081,14090,1091,1206,16016,1555,9431,12240,18821,38585,125285,32724,1916,23162,23638,24970,21607,26187,24141,27942,23527,17124,7820,1418,28,7319,327,259,1969,1446,50,8847,850,364,102,2231,14889,3879,1443,2,366,1131,1709,374,6771,938,531,308,1429,143,315,6455,50,1223,44,346,638,958,4233,206,167,586,46,13503,86447
4,E06000005,Darlington,E12000001,North East,55137,52686,107823,48931,0,16693,17252,7350,5279,1678,429,127,52,6844,9869,1010,782,4605,366,3092,2442,1862,3882,2433,5805,5663,247,242,0,42,3474,57,238,82895,57,727,19891,759,304,1090,619,200,455,133,106,373,520,207,380,599,328,97335,437,342,3521,102,2972,694,1480,927,101737,352,56196,455,36,1843,42780,5293,407,444,83491,18802,6212,8261,12722,16123,25508,16985,2254,3913,31325,10743,903,257,2850,2027,2681,216,949,5,6,11,22,372,4166,2535,21935,3237,50786,43233,6037,1209,35786,4978,5990,4894,6231,5239,3849,8467,4639,5015,9126,5233,11380,13410,8977,4638,17149,10902,7275,79,9328,238,5268,744,175,19149,13938,20,16225,14469,1040,9035,197,2812,5101,30694,10075,7913,14832,24330,1105,142,8496,155,2868,39814,462,666,370,84,38,269,232,3917,38,21341,11908,3426,12244,965,1397,25491,115,4971,483,2731,721,409,16,11961,4515,3826,9055,518,748,3521,844,8073,6230,11961,19693,68481,19633,1040,11824,12414,13727,11805,13530,13560,15625,12963,10130,4960,974,22,3760,147,311,688,803,27,4293,184,240,50,1455,7872,2295,680,2,307,648,1066,300,4154,135,402,202,773,85,144,4199,56,522,56,130,256,1199,2869,80,101,295,41,8468,49295

In [97]:
LAD_Census2021_df.to_excel('N:/Geodatabase/241122_Cleaned Data/LAD_Census2021.xlsx', index=False, engine='xlsxwriter')

## 4. Load OA, LSOA, MSOA, Ward, LA Shapefiles

### 4.1 OA

In [ ]:
OA_boundary_df = gpd.read_file("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Output_Areas_(Dec_2021)_Boundaries_Full_Extent_EW_(BFE)\Output_Areas_(Dec_2021)_Boundaries_Full_Extent_EW_(BFE).shp")
OA_boundary_df.drop(['Shape__Are', 'Shape__Len', 'GlobalID'], 1, inplace = True)
OA_boundary_df.rename(columns = {'OA21CD':'oa21cd'}, inplace = True)
OA_boundary_df.head()

### 4.2 LSOA

In [ ]:
LSOA_boundary_df = gpd.read_file("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Lower_Layer_Super_Output_Areas_(Dec_2021)_Boundaries_Full_Extent_(BFE)_EW/Lower_Layer_Super_Output_Areas_(Dec_2021)_Boundaries_Full_Extent_(BFE)_EW.shp")
LSOA_boundary_df.drop(['FID','Shape__Are', 'Shape__Len', 'GlobalID'], 1, inplace = True)
LSOA_boundary_df.rename(columns = {'LSOA21CD':'lsoa21cd'}, inplace = True)
LSOA_boundary_df.head()

### 4.3 MSOA

In [ ]:
MSOA_boundary_df = gpd.read_file("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data\MSOA_(Dec_2021)_Boundaries_Full_Extent_(BFE)_EW\MSOA_(Dec_2021)_Boundaries_Full_Extent_(BFE)_EW.shp")
MSOA_boundary_df.drop(['Shape__Are', 'Shape__Len', 'GlobalID'], 1, inplace = True)
MSOA_boundary_df.rename(columns = {'MSOA21CD':'msoa21cd'}, inplace = True)
MSOA_boundary_df.head()

### 4.4 Wards

In [ ]:
Ward_boundary_df = gpd.read_file("C:/Users/abhimanya.achara/OneDrive - priorpartners.com\Documents/UK DATA/2021 Census Data/Wards_(December_2021)_GB_BFE\Wards_(December_2021)_GB_BFE.shp")
Ward_boundary_df.drop(['Shape__Are', 'Shape__Len', 'GlobalID','WD21NMW','BNG_N','BNG_E','LONG','LAT'], 1, inplace = True)
Ward_boundary_df.head()

### 4.5 LA

In [ ]:
LA_boundary_df = gpd.read_file("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Local_Authority_Districts_(December_2022)_Boundaries_UK_BFC/LAD_DEC_2022_UK_BFC.shp")
LA_boundary_df.drop(['SHAPE_Leng', 'SHAPE_Area','BNG_N','BNG_E','LONG','LAT','GlobalID'], 1, inplace = True)
LA_boundary_df.rename(columns = {'LAD22CD':'lad22cd'}, inplace = True)
LA_boundary_df.head()

# 5. Combine datasets

### 5.1 OA boundaries + Census Data

In [ ]:
OA_Census_df = pd.merge(OA_boundary_df,Census2022df, how = 'left', on='oa21cd')
OA_Census_df_HH_df = OA_Census_df.loc[(OA_Census_df['lad22nm'] == 'West Berkshire') | (OA_Census_df['lad22nm'] == 'Buckinghamshire') | (OA_Census_df['lad22nm'] == 'Cherwell') | (OA_Census_df['lad22nm'] == 'Oxford') | (OA_Census_df['lad22nm'] == 'South Oxfordshire') | (OA_Census_df['lad22nm'] == 'Vale of White Horse') | (OA_Census_df['lad22nm'] == 'West Oxfordshire')]
OA_Census_df_HH_df.to_file("N:/Geodatabase/GIS_Geodatabase_Data/oa_boundaries_2022_FOR_NATALIA_02.geojson", driver='GeoJSON')
OA_Census_df_HH_df.head()

### 5.2 LSOA boundaries + Census + IMD

In [ ]:
msoa_income_df = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/msoa_income_2020.csv")
msoa_income_df.rename(columns = {'MSOA21CD':'msoa21cd'}, inplace = True)
msoa_income_df.head()

In [ ]:
LSOA_Census_df = pd.merge(LSOA_boundary_df,LSOA_df, how = 'left', on='lsoa21cd')
LSOA_Census_df = pd.merge(LSOA_Census_df,MSOA_pop_per_age_df_P, how = 'left', on='msoa21cd')
LSOA_Census_df = pd.merge(LSOA_Census_df,MSOA_industry_df_P, how = 'left', on='msoa21cd')
LSOA_Census_df = pd.merge(LSOA_Census_df,msoa_income_df, how = 'left', on='msoa21cd')
#LSOA_Census_df.to_file("P:/0_Practice/06_GIS/01_Data_Store/UK/For the geodatabase/lsoa_boundaries_2022.geojson", driver='GeoJSON')
LSOA_Census_df.head()

In [ ]:
LSOA_Census_df.drop(['MSOA21NM'],1,inplace = True)
LSOA_Census_df.head()

In [ ]:
LSOA_Census_df.to_file("N:/Geodatabase/GIS_Geodatabase_Data/lsoa_boundaries_2022.json")

In [ ]:
imd_lsoa = pd.read_csv("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/File_7_-_All_IoD2019_Scores__Ranks__Deciles_and_Population_Denominators_3(2).csv")
imd_lsoa.rename(columns = {'LSOA11cd':'lsoa21cd'}, inplace = True)
imd_lsoa.head()

In [ ]:
LSOA_Census_df = pd.merge(LSOA_Census_df,imd_lsoa, how = 'left', on='lsoa21cd')
LSOA_Census_df_SO_df = LSOA_Census_df.loc[(LSOA_Census_df['lad22nm'] == 'Southampton')]

### 5.3 MSOA boundaries + Age+Income+Industry

In [ ]:
MSOA_Census_df = pd.merge(MSOA_boundary_df,MSOA_df, how = 'left', on='msoa21cd')
MSOA_Census_df = pd.merge(MSOA_Census_df,MSOA_pop_per_age_df_P, how = 'left', on='msoa21cd')
MSOA_Census_df = pd.merge(MSOA_Census_df,MSOA_avg_income_df, how = 'left', on='msoa21cd')
MSOA_Census_df = pd.merge(MSOA_Census_df,MSOA_industry_df_P, how = 'left', on='msoa21cd')
MSOA_Census_df = pd.merge(MSOA_Census_df,MSOA_health_df, how = 'left', on='msoa21cd')
#MSOA_Census_df.to_file("N:/Geodatabase/Admin/msoa_boundaries_2022.shp")
#MSOA_Census_df.head()

In [ ]:
MSOA_Census_HH_df = MSOA_Census_df.loc[(MSOA_Census_df['lad22nm'] == 'West Berkshire') | (MSOA_Census_df['lad22nm'] == 'Buckinghamshire') | (MSOA_Census_df['lad22nm'] == 'Cherwell') | (MSOA_Census_df['lad22nm'] == 'Oxford') | (MSOA_Census_df['lad22nm'] == 'South Oxfordshire') | (MSOA_Census_df['lad22nm'] == 'Vale of White Horse') | (MSOA_Census_df['lad22nm'] == 'West Oxfordshire')]
MSOA_Census_HH_df.to_file("N:/Geodatabase/GIS_Geodatabase_Data/MSOA_boundaries_2022_FOR_NATALIA_02.json")
MSOA_Census_HH_df.head()

### 5.4 Ward + Census + Median Housing Cost+Life Expectancy

In [ ]:
Ward_Census_df = pd.merge(Ward_boundary_df,Ward_df, how = 'left', on='WD21CD')
Ward_Census_df = pd.merge(Ward_Census_df,Median_House_df, how = 'left', on='WD21CD')
Ward_Census_df = pd.merge(Ward_Census_df,Num_House_df, how = 'left', on='WD21CD')
#Ward_Census_df = pd.merge(Ward_Census_df,ward_life_expectancy_df, how = 'left', on='WD21CD')
Ward_Census_df.drop(['WD21NM_y'],1,inplace = True)
Ward_Census_df.rename(columns = {'WD21NM_x':'WD21NM'}, inplace = True)
Ward_Census_df.head()
#Ward_Census_df.to_file("N:/Geodatabase/Admin/ward_boundaries_2022.shp)
#Ward_Census_df.head()

In [ ]:
#Ward_Census_SW_df = Ward_Census_df.loc[(Ward_Census_df['lad22nm'] == 'Cambridge') | (Ward_Census_df['lad22nm'] == 'East Cambridgeshire') | (Ward_Census_df['lad22nm'] == 'Fenland')| (Ward_Census_df['lad22nm'] == 'Huntingdonshire')|(Ward_Census_df['lad22nm'] == 'Peterborough')| (Ward_Census_df['lad22nm'] == 'South Cambridgeshire')]
Ward_Census_df.to_file("C:/Users/abhimanya.achara/OneDrive - priorpartners.com/Documents/UK DATA/2021 Census Data/Updated info/Ward_boundaries_2022.json")
Ward_Census_df.head()

### 5.5 LA + IMD

In [ ]:
LAD_Census_df = pd.merge(LA_boundary_df,LA_df, how = 'left', on='lad22cd')
LAD_Census_df = pd.merge(LAD_Census_df,LAD_pop_per_age_df_P, how = 'left', on='lad22cd')
LAD_Census_df = pd.merge(LAD_Census_df,LAD_industry_df_P, how = 'left', on='lad22cd')
#LAD_Census_df.to_file("N:/Geodatabase/Admin/LAD_boundaries_2022.shp")
LAD_Census_df.head()

In [ ]:
LAD_Census_df.to_file("N:/Geodatabase/Admin/LAD_boundaries_2022.json")

In [ ]:
LAD_Census_df.to_csv("N:/Geodatabase/Admin/LAD_boundaries_2022.csv")

In [ ]:
LAD_Census_df.head()